### ISSUE TITLE
Question: More complex migrations

### ISSUE THREAD

**Issue by gflarity** [db-migrate/node-db-migrate#134]
Thanks for the this module, use it all the time and it's always been very reliable.

Question:

I find myself wanting access to the actual Postgres driver from within a migration transaction. This is to programatically select specific values to be inserted into a new column I'm adding before setting it not null. Is there a cannonical way to do this or should just create a multiple step migration and run my own script in between? 

Here's a high level overview of what I'm trying to do:

- create a column
- perform somewhat complex logic to populate a column correctly (in node.js not pure sql)
- make that column not null

Thanks,
GF

**Comment by wzrdtales** [comment]
refers to #215

**Comment by wzrdtales** [comment]
also runSql already delivers all functionality needed
