### ISSUE TITLE
MongoDb supported?

### ISSUE THREAD

**Issue by Vadorequest** [db-migrate/node-db-migrate#145]
Hi.

I would like to know if mongoDb is supported, I'm looking for a migration module for mongoDb.

Thank you!

**Comment by toymachiner62** [comment]
Any plans to support mongodb? There's not a great lib out there for mongodb migrations yet. Only a couple of half baked solutions that i've come across.

**Comment by wzrdtales** [comment]
@toymachiner62 
Yes, I plan to support it see also my related project https://github.com/wzrdtales/node-ultimate-migrate/issues/7

I think I will create a little roadmap what is going to be done the next weeks/months

**Comment by toymachiner62** [comment]
That would be great. The company that I work for is looking to ditch https://github.com/toymachiner62/node-mongo-seeds/issues/2 for a real migration library in the next 2 weeks or so (And build one if one doesn't exist) as we're very close to moving to production. Any chance I could help you bang this out in the next few weeks? Will you be responsive to pull requests?

Initially I created node-mongo-seeds as a way to quickly get all devs working off the same data, and never meant for it to go to production.

**Comment by wzrdtales** [comment]
I will be totally responsive to pull requests and I appreciate them ;)

There would be a chance to do this, I'm working on a number of projects currently but I think I can free a weekend and some afternoons. But I wont guarantee for it.
