### ISSUE TITLE
How to use timestamp with time zone using postgresql?

### ISSUE THREAD

**Issue by nisnardi** [db-migrate/node-db-migrate#154]
I need to set some column attributes as timestamps with time zone support using postgresql. I tried timestamp and datetime without any luck as both created the column without time zone:

created_at timestamp without time zone NOT NULL,
updated_at timestamp without time zone NOT NULL,

Is there a way to set the time zone support on the columnSpec definition?

Thanks
##

**Comment by rpmonteiro** [comment]
Any solution for this?

**Comment by wzrdtales** [comment]
@rpmonteiro Not yet, PRs would be appreciated, if you want you can go ahead and take a stab.

**Comment by shto** [comment]
I ran into the same issue. I ended up saving the date as a `string` value and storing it in the database with `date.toISOString()`. This ensures to save the date as UTC-based.

Then when retrieving it, I used `Date.parse(date)` in order to turn the string into a proper UTC-based date time.
