### ISSUE TITLE
[FEATURE] It would be nice to support column positioning with "after" keyword

### ISSUE THREAD

**Issue by ericchaves** [db-migrate/node-db-migrate#159]
When adding a column in mysql (not sure about other databases) we can specify after which column we want to position the new one or use the keyword 'first' if it should be the first column.

It would be great if we could define this positioning when adding new columns to existing tables.

Cheers,
##

**Comment by wzrdtales** [comment]
Marked as nice to have, has a very low priority and might be implemented in some far future. Feel free to open a pull request to directly contribute this feature

**Comment by Diluka** [comment]
Any update on this issue?
`AFTER` is important. It can make sure the database is actually as the same as designed.
`*` is relied on the order of the columns.

**Comment by wzrdtales** [comment]
@Diluka No, it is not important for the scope as it is really just cosmetic without any real world benefits, if you really want this, feel free to submit a pr to the driver though,
