### ISSUE TITLE
Maintainers Needed - please read

### ISSUE THREAD

**Issue by kunklejr** [db-migrate/node-db-migrate#169]
Over the past year or so, `db-migrate` has become a relatively popular project in the node community. Its popularity and the associated community demand have outpaced my ability to maintain it at a level I can be proud of and that it deserves. 

When the project was initially created I was using node and db-migrate every day, making it really easy to add new features, fix bugs, etc. However, my job changed about a year ago and and node was no longer part of the job description. For a long time (too long) I held on to the notion that I could keep up with things on nights and weekends, but life kept getting in the way. Helping my kids with schoolwork, coaching my sons' sports teams, ramping up on the new job, and hanging out with my wife once in a while ate up all that time. And I've finally realized that none of that is going to change.

It's not fair to let everyone's effort to report issues and submit pull requests fall prey to my selfish desire to hang on to my most popular project. I truly appreciate all the interest and contributions to the project, even if my slow response implies otherwise. But now it's time to make a change.

So today I'm asking for volunteers to officially help maintain the project. I'm not asking anyone to take over the project right away. A small group of people who commit to helping when they can is probably a good start, and certainly needed to ensure the project remains healthy and useful to the community. So if you have the time and are interested, please let me know.

Thanks,
Jeff

**Comment by wzrdtales** [comment]
Hi together,

I'm currently working on a project called [umigrate](https://github.com/wzrdtales/node-ultimate-migrate). It's a reverse migrator with diffing capabilities and should provide migration abilities by itself. For this purpose this project is wrapping db-migrate currently and I intend to to keep db-migrate as the migrator.
But over the time, more and more stuff opened to me which isn't covered by db-migrate yet. Umigrates design aims to be independent from the used migrator in the future, but I'm hardly intrested providing with it together a migration solution I completely trust.

Thats the why I would also be interested in maintaining this project, but more then actively developing at it and pushing it forward.

Currently db-migrate is missing travis, a code style definition and has outdated dependencies/docs. These are things that should be added. I especially would need to know the code style, to format the code correctly for this project.

@kunklejr 
You may contact me here via Github, or XMPP (tobi@wizardtales.com) or mail (magic@wizardtales.com) if interested.

**Comment by wzrdtales** [comment]
@kunklejr Is there currently anyone maintaining this project? It seems to be pretty dead right now :/
Hope you can find time for an answere on the weekend.

**Comment by kunklejr** [comment]
@wzrdtales Please see your email for a message I just sent you.

**Comment by wzrdtales** [comment]
@kunklejr thanks, have answered you.
