### ISSUE TITLE
PostgreSQL Sequence

### ISSUE THREAD

**Issue by acestudiooleg** [db-migrate/node-db-migrate#187]
When I create new table, I want to automatic create sequence for new table? where key 'sequence'=true

```
    exports.up = function (db, callback) {
  db.createTable('pets', {
    id: { type: 'int', primaryKey: true, sequence: true }, //automatic set default_value= nextval('pets_id_seq':regclass)
    name: 'string'  // shorthand notation
  }, callback);
}
```
##

**Comment by neerolyte** [comment]
`autoIncrement: true` seems to do this already:
http://db-migrate.readthedocs.org/en/v0.9.x/API/SQL/#createtabletablename-columnspec-callback
