### ISSUE TITLE
override default templates

### ISSUE THREAD

**Issue by gflarity** [db-migrate/node-db-migrate#212]
Hi, 

Love this module!

Question: Is there way to override the default templates used for migrations?

We use postgres and always include a begin and commit statement in our migrations.  Just want to add it to the default.

Thanks
##

**Comment by wzrdtales** [comment]
You can open a pull request adding new templates.

However, I'm looking into introduce a per migration transaction by default. So if a single migration fails everything gets rolled back and migration process stops right there.

But yet this is not within the scope of v0.9.0, but I always appreciate pull request ;)

**Comment by wzrdtales** [comment]
Related to #216

**Comment by AdriVanHoudt** [comment]
Would it be an option to do `require('db-migrate/lib/migration')` and override the prototypes?

**Comment by wzrdtales** [comment]
No, but we look to extend db-migrate to support real templates for migrations and make them extensible.

**Comment by wzrdtales** [comment]
Btw. the question raised at the beginning also included they want to use this to enforce the usage of transactions. Actually db-migrate always place a transaction begin and commit before and after every migration.

**Comment by wzrdtales** [comment]
closed in favour of #514
