### ISSUE TITLE
Provide a general usage API

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#214]
Retire the old bin/db-migrate and define a reusable api, while leaving bin/db-migrate as link for global installations.
##

**Comment by wzrdtales** [comment]
API is so far implemented, documentation is still missing though.

**Comment by emanchado** [comment]
Any progress on this? I'm interested in it, too :-) I tried reading the source but couldn't figure out how to use it :-/

**Comment by wzrdtales** [comment]
There are already docs about this topic:
http://db-migrate.readthedocs.org/en/latest/API/programable/

But I suspect you're using the current stable release, all of this is part of the v0.10.x release which is coming soon.

**Comment by emanchado** [comment]
Ah, didn't find it, thanks. Looking forward to 0.10!

**Comment by emanchado** [comment]
Is there any ETA for 0.10, BTW?

**Comment by wzrdtales** [comment]
@emanchado Sry for having not answered yet, to little time and to much todo in the last weeks.

In fact there is no real ETA, but  I plan to push through everything which is missing for the release yet, except the tests and release a pre-release of 0.10 while I work on finishing the docs and tests. I work through everything that stacked up the last weeks now :)
