### ISSUE TITLE
Replace optimist

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#224]
Replace optimist with a better component. As it's no longer support by the developer and doesn't met the requirements anymore.
##

**Comment by wzrdtales** [comment]
Was moved to v0.11.0, actually we leave it in place for v0.10.x as we're going to take a look at several solutions and make decision afterwards.

**Comment by listepo** [comment]
https://github.com/tj/commander.js

**Comment by wzrdtales** [comment]
When replacing optimist, also rework the way db-migrate initialize. Currently db-mgrate needs ~0.22ms for pure init before anything gets printed to the console.

Just by moving the command line parser to be the first item after instance identification will enable us a initialization time of ~0.07ms.

**Comment by wzrdtales** [comment]
We had an increase from ~0.09ms from version 0.9.x to 0.10.x, the reason for this is tunnel-ssh.

**Comment by wzrdtales** [comment]
Opened item #387 to immediately fix the issue with tunnel-ssh.

**Comment by ebaynaud** [comment]
That becomes important because of a [vulnerability](https://snyk.io/vuln/SNYK-JS-MINIMIST-559764) found in the version of minimist that optimist depends on. (In addition, mkdirp should be upgraded as well)

**Comment by rfrm** [comment]
#679
