### ISSUE TITLE
foreign key definition dont works with Postgresql

### ISSUE THREAD

**Issue by rkmax** [db-migrate/node-db-migrate#237]
I have the migration below, but the foreign keys are not added

```js
var dbm = require('db-migrate'),
    async = require('async'),
    type = dbm.dataType;


exports.up = function(db, callback) {
    async.series([
        db.createTable.bind(db, 'roles', {
            id: {type: 'int', primaryKey: true, autoIncrement: true},
            name: 'string'
        }),
        db.createTable.bind(db, 'user_has_roles', {
            user_id: {
                type: 'int',
                notNull: true,
                foreignKey: {
                    name: 'user_has_roles_user_id_fk',
                    table: 'users',
                    rules: {
                        onDelete: 'CASCADE',
                        onUpdate: 'RESTRICT'
                    },
                    mapping: 'id'
                }
            },
            role_id: {
                type: 'int',
                notNull: true,
                foreignKey: {
                    name: 'user_has_roles_role_id_fk',
                    table: 'roles',
                    rules: {
                        onDelete: 'CASCADE',
                        onUpdate: 'RESTRICT'
                    },
                    mapping: {
                        role_id: 'id'
                    }
                }
            }
        }),
        db.addIndex.bind(db, 'user_has_roles', 'user_has_roles_unique', ['user_id', 'role_id'], true),
    ], callback);
};

exports.down = function(db, callback) {
    async.series([
        db.dropTable.bind(db, 'user_has_roles')
        db.dropTable.bind(db, 'roles'),       
    ], callback)
};
```

**Comment by wzrdtales** [comment]
which database?

**Comment by rkmax** [comment]
@wzrdtales Postgresql see the title

**Comment by wzrdtales** [comment]
Comes in v0.10.0
https://github.com/kunklejr/node-db-migrate/commit/e82f78dc4a053cbe93b2b34fa15590c5fa708309#diff-04c6e90faac2675aa89e2176d2eec7d8L441

This note was removed from the master readme, but this feature was introduced first in v0.9.0 and only for mysql. Please wait for v0.10.0 to use this on postgres.

https://github.com/kunklejr/node-db-migrate/blob/v0.9.x/README.md

**Comment by wzrdtales** [comment]
I will leave this question open, for others that may don't recognize this. Will be closed on release of v0.10.0

**Comment by rkmax** [comment]
@wzrdtales thanks, For when you have planned 0.10.0 relase?

**Comment by wzrdtales** [comment]
Something in the next 4-6 weeks, there is still a list of features which are flagged for v0.10.0 that needs to be finished. Also I'm investing a high amount of my time currently to several other projects I'm involved, thus I can't made a real finite announce.

**Comment by wzrdtales** [comment]
But to leave some hope, I make good progress. We will see how fast I write down those things. Most concepts are already made though.

**Comment by rkmax** [comment]
@wzrdtales A 0.9.8 would be very appreciated :+1:. add support to postgres

**Comment by wzrdtales** [comment]
Well I don't think this fits to be released as a patch, more then to be released as a minor and thus this would break with semver.

**Comment by rkmax** [comment]
Bad luck, I'll wait then, I'll take eye on the issues, maybe I can work with something

**Comment by wzrdtales** [comment]
Well if you really want to use this feature right now, you could use the project from this commit
https://github.com/kunklejr/node-db-migrate/commit/7aeea1f69427a719a035d6e265d246a7693f8b0a

This is state should be stable enough, at least it has passed all tests, also the tests which are currently only on my local drive.

**Comment by rkmax** [comment]
@wzrdtales Great!

**Comment by rue** [comment]
It’s not explicitly noted here, but if somebody else evaluating this tool is reading, the _separate_ `addForeignKey` works with Postgres.

Where are we with 0.10? It’s 5 months over the original estimate… :)

**Comment by wzrdtales** [comment]
@rue So true, I really did not expected to have this less time..., but I'm currently much more active again :). Going to push the next changes up on thursday or friday.

I currently finally move the drivers into their own repos (they're already but in fact still exist in the migrator repo) and have some local changes for the VC Seeder, changes at the handling of local variables, API changes for the new programable API, extensions to the docs and some other stuff.

**Comment by wzrdtales** [comment]
closed as of the beta release including this and soon following final release.
