### ISSUE TITLE
Question: Why is there no data type TINYINT?

### ISSUE THREAD

**Issue by ranzer** [db-migrate/node-db-migrate#243]
Why is there no data type TINYINT in  db-migrate/lib/data_type.js file?

**Comment by wzrdtales** [comment]
I reference here to this:
https://github.com/kunklejr/node-db-migrate/issues/86#issuecomment-17732218

But the dataTypes are going to be extended, at least dataTypes which are not some strange datatypes are going to be added.

For example array types are to specific to postgres or enums are to specific and this dataTypes are made to be generic. In short tinyInt or BYTE will be added in the near future.
