### ISSUE TITLE
Question: Is it possible to generate migration files from existing database scheme?

### ISSUE THREAD

**Issue by ranzer** [db-migrate/node-db-migrate#244]
I have already created database scheme and I would like to generate appropriate migration files for it. Can db-migrate read existing scheme and generate migration files for it?

**Comment by wzrdtales** [comment]
This isn't something that db-migrate should do, or will ever do. But there is a project from me that is doing what you're searching for.

Please view my other project https://github.com/wzrdtales/node-ultimate-migrate, this is exactly doing what you're searching for. But it's currently still in beta and yet there is only support for mysql.
