### ISSUE TITLE
How to query exist data before migration

### ISSUE THREAD

**Issue by rkmax** [db-migrate/node-db-migrate#248]
Example

I need add a new `notNull: true` column, but the table has rows. so

1. I need get current the data from the table
2. add the new column with the `notNull: true` property
3. insert updated records
4. update the column definition with `notNull: true`

```js
dbm = dbm || require('db-migrate');
var type = dbm.dataType,
    async = require('async');

exports.up = function(db, callback) {

  async.series([
      db.addColumn.bind(db, 'users', 'email', {
        type: type.STRING
      }),
      // get the current and update
      db.changeColumn.bind(db, 'users', 'email', {
        type: type.STRING,
        notNull: true
      }),            
  ], callback);
};

exports.down = function(db, callback) {
  db.removeColumn('users', 'email', callback);
};
```

How i can get the current data?

**Comment by wzrdtales** [comment]
Data operations are not exactly a part of the migrations. This more or less belongs to seeding data.

Yet you can't select data, but there are features which are going to be introduced within v0.10.x
I reference here to this:
https://github.com/db-migrate/node-db-migrate/issues/215

and this:
https://github.com/db-migrate/node-db-migrate/issues/230

So currently you can't do this via any method which is intended to do this. But this doesn't mean it is impossible.

You need to fallback to runSql and select your data by native queries, but why you don't just add a defaultValue to your definition. With a defaultValue you can set notNull to true unless it is keyed with unique or primary.

**Comment by rkmax** [comment]
@wzrdtales yeah are unique values

**Comment by wzrdtales** [comment]
Then you need to fallback to runSql right now.

**Comment by rkmax** [comment]
Thanks that was what I did?

For example

```
exports.up = function (db, callback) {
  async.series([
    db.addColumn.bind(db, 'users', 'email', {
      type: type.STRING
    }),
    function (cb) {

      return db.runSql('SELECT * FROM users', [], function (err, results) {
        var inserts = [];
        results.rows.forEach(function (row) {
          inserts.push(db.runSql.bind(
              db, 'UPDATE users SET email = ? WHERE id = ?', [row.username + '@example.com', row.id]
          ));
        });
        async.series(inserts, cb);
      });
    },
    db.changeColumn.bind(db, 'users', 'email', {
      type: type.STRING,
      notNull: true
    }),
    db.addIndex.bind(db, 'users', 'email_unique', ['email'], true),
    db.addIndex.bind(db, 'users', 'username_unique', ['username'], true)
  ], callback);
};
```

**Comment by wzrdtales** [comment]
That is probably a solution, if this works for you.
