### ISSUE TITLE
.addColumn fail on Postgresql if the column definition has a foreignKey

### ISSUE THREAD

**Issue by rkmax** [db-migrate/node-db-migrate#255]
The following fails

```js
exports.up = function(db, callback) {
  db.addColumn('practices', 'primary_topic_id', {
    type: type.INTEGER,
    notNull: true,
    foreignKey: {
      name: 'primary_topic_id_fk',
      table: 'topics',
      rules: {
        onDelete: 'CASCADE',
        onUpdate: 'RESTRICT'
      },
      mapping: 'id'
    }
  }, callback);
};
```

```
[ERROR] error: no existe la relación «undefined»
    at Connection.parseE (/home/rkmax/node-project/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/home/rkmax/node-project/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/home/rkmax/node-project/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

I have to do the following

```js
exports.up = function (db, callback) {
  async.series([
    db.addColumn.bind(db, 'practices', 'primary_topic_id', {
      type: type.INTEGER
    }),
    db.changeColumn.bind(db, 'practices', 'primary_topic_id', {
      type: type.INTEGER,
      notNull: true,
      foreignKey: {
        name: 'primary_topic_id_fk',
        table: 'topics',
        rules: {
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT'
        },
        mapping: 'id'
      }
    })
  ], callback);
};
```

**Comment by rkmax** [comment]
I forgot mention I'm using `7bfeea1f` version

**Comment by wzrdtales** [comment]
@rkmax yes, I know, I do rember #237

**Comment by rkmax** [comment]
:+1:

**Comment by wzrdtales** [comment]
I opened a new branch https://github.com/db-migrate/node-db-migrate/tree/maintainedTesting

You can find there a version based on 7aeea1f with the bugfix applied.

**Comment by rkmax** [comment]
@wzrdtales thanks

**Comment by rkmax** [comment]
@wzrdtales with the last issue solve this still reopen :(

**Comment by wzrdtales** [comment]
please provide the necessary information to reproduce and actual error logs

**Comment by wzrdtales** [comment]
are you sure, you're using the right version?

https://github.com/db-migrate/node-db-migrate/blob/master/test/driver/pg_test.js#L498-L525

I have also covered this with a test and it's passing

**Comment by rkmax** [comment]
Example adding a new column

```js
db.addColumn.bind(db, 'topics', 'category_id', {
      type: type.INTEGER,
      foreignKey: {
        name: 'category_id_fk',
        table: 'categories',
        rules: {
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT'
        },
        mapping: 'id'
      }
})
```

The field was added to the table but not as foreign key. this is the DDL generated after apply the migration

CREATE TABLE topics
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR,
    category_id INT,
);


I'm using this https://github.com/kunklejr/node-db-migrate/tarball/faa55cad348d2968582cfd5811c9f540f9e58696

Let me check if I'm calling the wrong db-migrate

**Comment by wzrdtales** [comment]
This would be v0.9.7 and this fix is only applied to https://github.com/db-migrate/node-db-migrate/tree/maintainedTesting yet.

**Comment by wzrdtales** [comment]
Never mind, confused of the title of the tarball, just checked the hash.

**Comment by rkmax** [comment]
Man, I'm very sorry. seems my GUI Tool is not updating the info properly, I've checked directly with psql and table information was wrong.

**Comment by wzrdtales** [comment]
ok no problem. if have any problems again please don't forget to provide error messages and a proper way to reproduce so I can faster solve your problem ;)

**Comment by rkmax** [comment]
Thanks man, much thanks for your help and quickly responses
