### ISSUE TITLE
How to implement an "are you sure?"

### ISSUE THREAD

**Issue by wrouesnel** [db-migrate/node-db-migrate#256]
I like to have my db-migration script able to go all the way down to "no database" since it makes resetting dev instances (and testing db migration scripts) easy. But this slightly terrifies me because you could use the same thing to wipe out a production database.

Are any patterns to have my first-level (or any destructive) migration script print a big "ARE YOU SURE?" before it does something - or maybe do a SQL dump before it runs.

**Comment by wzrdtales** [comment]
There are no such pattern, you would have to use just your own javascript piece and I don't see why one would ever call a reset on a production system?
Migrations should be delivered in a state that is building up on top of the last delivered migrations when the final deployment to the production system is done. If this is not the case, then there is something terribly wrong in the usage with migrations itself.
