### ISSUE TITLE
Which difference exists between .runSql and .all methods

### ISSUE THREAD

**Issue by rkmax** [db-migrate/node-db-migrate#260]

**Comment by wzrdtales** [comment]
runSql does only run if the dryRun boolean is not set. all gets executed even if the dryRun boolean is set.

all is not a method you should use in your migrations though.

**Comment by rkmax** [comment]
So if I have special migrations those where I use SELECT raw queries i can use .all in that way I can run the migration with --dry-run and works fine. @wzrdtales thanks should include that informacion in the readme
