### ISSUE TITLE
Postgres missing support for "ALTER TABLE ... ALTER COLUMN ... TYPE ..."

### ISSUE THREAD

**Issue by fydo23** [db-migrate/node-db-migrate#262]
I was looking at https://github.com/db-migrate/node-db-migrate/blob/master/lib/driver/pg.js#L246 and was sad to see that it's impossible to alter an existing column's types in postgres.

I'm thinking, check if `type` is in `columnSpec` to trigger:

     var sql = util.format('ALTER TABLE "%s" ALTER COLUMN "%s" TYPE %s', tableName, columnName, columnType);

Fy.

**Comment by fydo23** [comment]
I modified the `function setNotNull()` to the following:

    function setNotNull() {
        var alter_column = "";
        if (columnSpec.type != undefined){
          var using = util.format("USING %s::%s", columnName, this.mapDataType(columnSpec.type));
          if (columnSpec.using != undefined){
            using = columnSpec.using;
          }
          alter_column = util.format('ALTER COLUMN "%s" TYPE %s %s, ', columnName, this.mapDataType(columnSpec.type), using);
        }
        var setOrDrop = columnSpec.notNull === true ? 'SET' : 'DROP';
        alter_column = alter_column + util.format('ALTER COLUMN "%s" %s NOT NULL', columnName, setOrDrop);

        var sql = util.format('ALTER TABLE %s %s', tableName, alter_column);
        
        this.runSql(sql, setUnique.bind(this));
      }

Which seems to work. This adds the extra complexity of having an optional `using` param in  the `columnSpec` to allow for custom data conversion, (ie, bytea to int).

**Comment by wzrdtales** [comment]
Actually there was pull request about this
#209

Unfortunately an incomplete one, not only it is lacking tests, it also failed with the existing ones. Currently this is not in scope of v0.10.x and earliest would be in v0.11.x. But you're free to open a merge request handling tests, this is always appreciated :)

**Comment by Dynom** [comment]
I would greatly appreciate a more thorough overview of what's supported and what isn't supported per database.


I was scratching my head about why the following
```
exports.up = function(db, callback) {
  db.changeColumn(
    'foo', 
    'bar',
    {
      type: 'int'
    },
    callback
  );
};
```

Produced the following ridiculous SQL statements:
```
[INFO] dry run
BEGIN;
ALTER TABLE "foo" ALTER COLUMN "bar" DROP NOT NULL
ALTER TABLE "foo" ALTER COLUMN "bar" DROP DEFAULT
..
```

Until I found this issue.

**Comment by wzrdtales** [comment]
@Dynom Yes you're right, I'm working on the documentation and informations like this will also be documented there. Thats part of the goal which is set for the v0.10.x release.

Btw. the newest docs are always on readthedocs now, I will clean up the readme soon.

https://readthedocs.org/projects/db-migrate/?badge=latest

**Comment by Dynom** [comment]
Thanks for the update @wzrdtales I'll make sure to readthedocs more often (-;

**Comment by wzrdtales** [comment]
closed as it was already merged
