### ISSUE TITLE
Can't use choose postgres schema if DATABASE_URL exists

### ISSUE THREAD

**Issue by apechimp** [db-migrate/node-db-migrate#267]
If the `DATABASE_URL` environment variable is set, the configuration file is not read, so there is no way to choose a schema when using postgres. Would a PR for adding a commandline option for setting a schema be welcome?

**Comment by wzrdtales** [comment]
@apechimp This is one issue, that might be needed to be carefully handled. This might result in an undefined behavior for some users. A pull request is always welcome though, but in this case this might cause trouble afterwards.

**Comment by wzrdtales** [comment]
@apechimp May be it would be the better solution to enrich the parse-database-url project with this feature. https://github.com/pwnall/node-parse-database-url

Also there would be the possibility to change the schmea via the scope config, see also https://github.com/db-migrate/node-db-migrate#scope-configuration

**Comment by apechimp** [comment]
Good suggestions! I too don't think the PR I proposed was a very good idea :wink: I'll submit a patch to parse-database-url.
