### ISSUE TITLE
How to check pending migration?

### ISSUE THREAD

**Issue by shaimr** [db-migrate/node-db-migrate#273]
Hey,

I want to disable my app when pending migration exists. How can i do it?
(I prefer configuration, but code is also a possibility)

Thanks,
Shai.
##

**Comment by antoineverger** [comment]
I think you might have to wait ´til the 0.10 milestone (https://github.com/db-migrate/node-db-migrate/milestones/v0.10.0) is released. It will expose the db-migrate api so you can use it as a module in your app and then, you should be able (to be confirmed) to check if you have pending migrations.

**Comment by shaimr** [comment]
When is it planned to be?

**Comment by antoineverger** [comment]
I´m not a committer on the project so can not say. If we help on that, it will obviously go faster ;)

**Comment by wzrdtales** [comment]
@antoineverger @shaimr 
Concerning the plan for the release of v0.10.x, I think I will try to fetch some time to publish what exactly is planned, in what order, how the time schedule is setup and so on. To say, there is no fixed date for the release of v0.10.x, there will be a pre-release for v0.10.x, but later more on this topic.
I'm currently working on about 20 projects, I have planned time for db-migrate for tomorrow, and I'm working on it every day and finish little things, I hope it is not as hot tomorrow here in Germany as yesterday though, I'm quite unproductive while a heat of 32°C+ :/
