### ISSUE TITLE
release updated mysql dependency to avoid bignumber.js bug?

### ISSUE THREAD

**Issue by jefforulez** [db-migrate/node-db-migrate#279]
is it possible for to do a hotfix release with the updated mysql version dependency so that the bignumber.js "critical bug" is avoided?

$ npm install

npm WARN deprecated bignumber.js@2.0.0: critical bug fixed in v2.0.4

db-migrate@0.9.17 node_modules/db-migrate
├── ...
├── mysql@2.5.5 (require-all@1.0.0, bignumber.js@2.0.0, readable-stream@1.1.13)

the current ~2.7.0 version would be great.   https://github.com/db-migrate/node-db-migrate/blob/master/package.json#L34

thanks!

**Comment by wzrdtales** [comment]
Hey,

sry for beeing so late. I had a few tough weeks and needed to manage some kind of things and am back working effectively now :)

I will check if the upgrade has any negative effect and if not then releasing an upgrade.

**Comment by wzrdtales** [comment]
updated mysql dependency released with v0.9.18
