### ISSUE TITLE
Feature: down all migrations one command and allow use db-migrate as module

### ISSUE THREAD

**Issue by rkmax** [db-migrate/node-db-migrate#281]
I have many migrations that represents all my database, when I run tests I use the migrations to recreate a test database in a known state usualy I pass something like

```js
var exec = require('child_process').exec;
var Promise = require('bluebird');

function execAsync(cmd) {
  return new Promise(function(resolve, reject) {
    exec(cmd, function(err, stdout, stderr) {
      if (err) { reject(err); } else { resolve({stdout: stdout, stderr: stderr}); }
    });
  }
}
module.exports = {
  down: function() {
    return execAsync('db-migrate down -c 100');
  },
  up: function(down) {
     return Promise.resolve()
       .then(function() {
         if (down) { return this.down() }  else {
           return Promise.resolve();
         }
       }.bind(this))
       .then(function() {
          return execAsync('db-migrate up');
       });
  }
}
```

would be great if I can pass something like `--all` to the down command and if I can use db-migrate as module

```js
  var migrate = require('db-migrate');

  ...
  return migrate.down({all: true}).then(function() { return migrate.up(); });
```

**Comment by wzrdtales** [comment]
@rkmax I'm working on this :)
There is a reset method, that already does what you search for and the db-migrate as a module with a stable programable api is also part of the v0.10.x version.

I need to finish and test the last details of the seeder and of the internal structure of db-migrate (restructuring the driver architecture, promisifying and so on...), after this I will release a pre release of 0.10.x, while I will finish the docu and the missing tests.

Has worked for a while on this 0.10.x for now and I changed a lot of things, but I think we will be finally there shortly!

**Comment by rkmax** [comment]
thanks @wzrdtales for all your hard work

**Comment by wzrdtales** [comment]
refers to #214 

Notes: reset commands already fullfills the described need.
