### ISSUE TITLE
Incompatibility to io.js-3.0

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#286]
# Broken on io.js 3

As some of you may have mentioned, that the CI is failing on builds upwards version 3.0.

This is because of an incompatibility of the sqlite driver, which does not compile anymore. Also NAN has released a major release, which means that many projects using native modules are pretty broken right now.

This goes for sqlite3 which we use and also pg-native, which we included by default.

I used the time I spent on this, to clean up a bit. I removed the tests for different versions of postgresql, thus we test only on the current stable version now. Also I defaulted the project to mariadb, it covers all mysql functionality anyway, travis ci now **finally** supports mariadb as an addon though. The last thing I changed, was to remove the pg-native module, you can install it yourself anytime if you want it, as it is only optional.

## Conclusion

Just wait a bit before switching to io.js 3, either the modules get fixed and get compatible to io.js 3 or the drivers already have moved out of db-migrate itself and get available as standalone.
Or better, just use nvm!

I leave you this note as I'm going to remove io.js 3 from the builds for now, until this issue is fixed. In one or another way... .

**Comment by jhs67** [comment]
Release 3.1.0 of sqlite3 package is available, and this works with iojs 3 and node 4. Indeed, the master branch of this repo seems to work fine with node 4 (and the sqlite driver as well).

**Comment by wzrdtales** [comment]
Yes since today iojs-3 builds fine again. https://travis-ci.org/db-migrate/node-db-migrate/builds/79347057

closing this note.
