### ISSUE TITLE
is it possible to use with es6 syntax?

### ISSUE THREAD

**Issue by almasakchabayev** [db-migrate/node-db-migrate#289]
cannot make it work with es6 imports

**Comment by wzrdtales** [comment]
Ok..., please be so kind and open an issue with a bit more of love. Clearly missing your own interest in this issue, as you're leaving out:

Why you need it and details how it may should look and feel like.
Maybe already a suggestion on how a solution could look like.

Just opening an issue with no content at all and just saying "cannot make it work", is some kind of rude.

Ok...
After we got this let's go in some deeper. Actually deploying a module, available as a command to the operating system, makes this not an easy task:
https://github.com/db-migrate/node-db-migrate/blob/master/bin/db-migrate#L1

As the executable which gets called is adressed with a shebang.

There is a trick to acomplish that, but yet I can't ensure this works on all platforms (OS X, *nix, Windows):
http://sambal.org/2014/02/passing-options-node-shebang-line/

This needs to be verified first, another option would be to integrate an es6 parser. While this might not be the fastest solution, it would work across all node versions.

The last optionality is to wait for node.js to completely support es6 without the `--harmony` flag. io.js for example does support already many features of es6 without provding the `--harmony`, not sure if imports are already working so far. 
If you want to try io.js then use io.js version 2.x.x and not version 3.x.x. Version 3 was just released a few weeks ago and thus many dependencies and native modules are not completely building yet. Also read #286 concerning this.

**Comment by wzrdtales** [comment]
Also an option would be to pass it as an environment variable, with a call style like:

NODE_ARGS='--harmony --harmony-modules' db-migrate

Would also be an way to accomplish that. Not sure about the windows support yet.

**Comment by wzrdtales** [comment]
Ok, after having a look at this, npm currently doesn't support a behavior that would make it possible to solve this problem without calling a subprocess from node itself.

I guess I will do it in a similar way, in which mocha has done it.

**Comment by jonathansamines** [comment]
Hi, i just was trying to run a es6 script to run, but is seems that is not supported by this module. Have you thought about adding an "--exec" option which will allow to run it with either "node itself", io or even babel if needed? I´ve seen other libraries to do it (like nodemon for example). It seems that the mocha solution, should allow this kind of behavior.

There´s a WIP for this?

**Comment by wzrdtales** [comment]
@jonathansamines Not yet a WIP, but it is planned to support it.

**Comment by wzrdtales** [comment]
Target for plugins, will be available as plugin which registers the babel pre compiler.
