### ISSUE TITLE
Make relation module optional in Migrator

### ISSUE THREAD

**Issue by charyorde** [db-migrate/node-db-migrate#293]
Can [this](https://github.com/db-migrate/node-db-migrate/blob/master/lib/migrator.js#L13) be optional?

Use case: no concept of relation in Cassandra database.

**Comment by wzrdtales** [comment]
It actually is optional :)

This is the preparation for automatic look ups of values in the new Seeders. And yes there is probably no relation in Cassandra, that is true. But it is still possible that there is some relation in your dataset, but this is just a question of the design. Most of the time you're right and NoSQL like Databases will store the whole object/document/whatever with everything in it.
