### ISSUE TITLE
can db-migrate be used on mariadb? 

### ISSUE THREAD

**Issue by sudhirravindramohan** [db-migrate/node-db-migrate#297]
It works with database type as mysql, however what are your recommendations?

**Comment by wzrdtales** [comment]
I personally only use mariadb all the time. You can use mariadb with db-migrate without thinking a second about it.

**Comment by sudhirravindramohan** [comment]
Thanks, noted and closing this ticket. In future if there is going to be divergence and a separate mariadb driver support (say via mariasql - https://github.com/mscdex/node-mariasql) we would be interested to develop this and adopt. however at the moment we will not be able to take this up.

**Comment by wzrdtales** [comment]
MariaDB probably never going to be incompatible to MySQL, but may provide features not supported by MySQL. At this time I wouldn't spent time on a mariasql driver (also I use it in all my projects though), as it is just more efficient than the MySQL driver, but in the context of a migration framework mariasql actually it doesn't add any benefit, as we execute one query by one and doesn't benefit by the non blocking features from the MariaDB library.

But if it starts to support features that are unique to MariaDB, there probably a mariasql driver going to be developed.
