### ISSUE TITLE
npm installs all drivers - sqllite, pg, mysql and mongo

### ISSUE THREAD

**Issue by ghost** [db-migrate/node-db-migrate#298]
I am using mariadb for test/production and would need that, I use sqllite for dev, however the mongo and pg drivers are not used and because it is part of the npm dependencies of db-migrate, they get installed. 

In contrast sequelize does not include these dependencies and it is upto the dependant package (my module) to define what drivers to install and use. 

I understand that there would be a thought in adopting this dependency approach, filing a ticket to hear from the maintainers on what design thoughts went into that. 

As far as I have researched, npm does not come with a way to exclude second level dependencies during install through package.json specification.

**Comment by wzrdtales** [comment]
Please just wait for v0.10.x, with v0.10.x db-migrate and the drivers get separated. This means you install db-mgirate and you install db-migrate-mysql or db-migrate-pg or whatever you need. These dependencies are going to disappear though and you will gain much more control then you have now.

**Comment by sudhirravindramohan** [comment]
Thanks I will wait for 0.10 version release. Thanks for the information.
