### ISSUE TITLE
TIME type missing from mysql driver

### ISSUE THREAD

**Issue by keneasson** [db-migrate/node-db-migrate#299]
using 'time' returns: [WARN] Using unknown data type TIME
lib/driver/mysql.js 
        return 'TINYTEXT';
      case type.DATE_TIME:
        return 'DATETIME';
+      case type.TIME:
+        return 'TIME';
      case type.BLOB:

**Comment by wzrdtales** [comment]
You can use an unsupported data type, you just get this warning message you already have seen. This is intended, as it means: Hey you can use this, but look out if everything works like it should, because this is not officially supported yet.

**Comment by keneasson** [comment]
Thanks so much for the quick reply.
I found the problem i was having: it was with timestamp and creating an Current_time. I solved it this way: lib/driver/mysql.js
    if (spec.defaultValue !== undefined) {
      constraint.push('DEFAULT');

      if (typeof spec.defaultValue === 'string'){
        if (spec.type === 'timestamp') {
          constraint.push(spec.defaultValue);
        }
        else {
          constraint.push("'" + spec.defaultValue + "'");
        }
      } else if (spec.defaultValue === null) {
        constraint.push('NULL');
      } else {
        constraint.push(spec.defaultValue);
      }
    }

there should probably be some code to check default, as you can enter an actual time, however typical use in mysql is to have a modified table with auto updating modified timestamp:
			created: {type: 'timestamp', 'null': 1},
			modified: {type: 'timestamp', "defaultValue": 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'}
this now works - note the need to set any other timestamp to null:1 as it doesn't work otherwise.

thanks for this great tool!

**Comment by wzrdtales** [comment]
With the next release current_timestamp gets also handled more comfortable, see:

https://github.com/db-migrate/node-db-migrate/blob/37a3176ad0e7d33c38b05732e93100a711e3be43/lib/driver/mysql.js#L131-L154

**Comment by keneasson** [comment]
Nice!

Sent from my HTC

----- Reply message -----
