### ISSUE TITLE
Quotes in type name cause issue (MySQL)

### ISSUE THREAD

**Issue by bherila** [db-migrate/node-db-migrate#300]
When I try to add a SET column to a MySQL database, db-migrate chokes
```js
exports.up = function(db, callback) {
  async.series([
    db.addColumn.bind(db, 'offer', 'sale_type', {type: 'SET("WineryDirect","CS")'}),
    db.addColumn.bind(db, 'offer_manifest', 'cogs', type.FLOAT)
  ], callback());
};
```

Result: 
```
[SQL] ALTER TABLE `offer` ADD COLUMN `sale_type` SET("WINERYDIRECT","CS")  
[ERROR] TypeError: Cannot read property 'type' of undefined
    at Class.Base.extend.mapDataType (/usr/local/lib/node_modules/db-migrate/lib/driver/mysql.js:16:16)
    at Class.prototype.(anonymous function) [as mapDataType] (/usr/local/lib/node_modules/db-migrate/lib/class.js:36:24)
    at Class.Base.extend.createColumnDef (/usr/local/lib/node_modules/db-migrate/lib/driver/mysql.js:51:18)
    at Class.Base.extend.addColumn (/usr/local/lib/node_modules/db-migrate/lib/driver/mysql.js:178:20)
    at /Users/ben/projects/undergroundcellar/db/node_modules/async/lib/async.js:689:13
    at iterate (/Users/ben/projects/undergroundcellar/db/node_modules/async/lib/async.js:265:13)
    at process._tickCallback (node.js:355:11)
```

when this is done with a regular SQL command it works fine: 

```js
exports.up = function(db, callback) {
  async.series([
    db.runSql.bind(db, 'ALTER TABLE `offer` ADD COLUMN `sale_type` SET("WineryDirect", "CS")'),
    db.addColumn.bind(db, 'offer_manifest', 'cogs', type.FLOAT)
  ], callback());
};
```

**Comment by wzrdtales** [comment]
@bherila The problem has nothing to do with SQL or your custom type.

The problem is the last part of your migration, which is invalid:

```javascript
db.addColumn.bind(db, 'offer_manifest', 'cogs', type.FLOAT)
```

First of all, there is currently no type.float and the second failure is. You always need to supply an object. You have just directly passed `type.FLOAT`, but actually exepected is: `{ type: type.DECIMAL }`. The chosen type decimal is just an example here, you can use just any type either defined in the current mapping of datatypes or custom specified like you did already for `SET("WineryDirect","CS")`.

**Comment by wzrdtales** [comment]
See also
https://github.com/db-migrate/node-db-migrate#generic-datatypes

**Comment by wzrdtales** [comment]
To note, many drivers support some more types. Like MySQL do, it will have  a separate documentation soon, which outlines these differences. However a nonexistent type is just "not supported", but you should be  able to use it anyway. Maybe you need to escape the quoting a bit to get it work (like you have to do when you use the enum type of MySQL)

**Comment by wzrdtales** [comment]
If you have any other questions, just ask and we will see if we can help you.

**Comment by bherila** [comment]
Thank you @wzrdtales !

I will try to find some time to contribute extra content/examples to the readme.md so that others won't run into this too :+1:

**Comment by bherila** [comment]
One other question actually: 

> First of all, there is currently no type.float and the second failure is. You always need to supply an object. 

I had found a function which attempts to "normalize" the type in the event that something is supplied that doesn't have a `type` member. I guess that shouldn't be taken advantage of?

**Comment by wzrdtales** [comment]
Yes you're right, this slipped my mind. The normalize function does parse the options argument to be a type option if you supply a string. You have supplied type.FLOAT which is undefined, so this condition wasn't called either. So yes you can either define a string, existing datatype or object.
