### ISSUE TITLE
No more ENV allowed for full database URL in 0.9.20

### ISSUE THREAD

**Issue by christemple** [db-migrate/node-db-migrate#304]
Hi guys,

I have been trying to get my database config file to support using a full database connection URL from and environment variable i.e. 

```JSON
{
  "production": { "ENV": "MONGOLABD_URI" }
}
```

It keeps throwing an error saying I need to specify a driver, however the following suggests I should be able to this: 

https://github.com/db-migrate/node-db-migrate/blob/master/lib/config.js#L26

But the version that's on Github is only at 0.9.12, and the version I am downloading via NPM is 0.9.20.

Now looking at https://github.com/db-migrate/node-db-migrate/blob/v0.9.20/lib/config.js#L26 suggests that it has regressed to a point where the config will only allow a string i.e. no `{ "ENV": "MONGOLAB_URI"}`

Is there a specific reason why the ability to use a full database connection url via and ENV variable has been removed?

Also, the `master` branches' `package.json` suggests it's `v0.9.12` (which is way behind), however it doesn't match `v0.9.12` as `master` has the code I need and `v0.9.12` does not: https://github.com/db-migrate/node-db-migrate/blob/v0.9.12/lib/config.js#L26

I have no idea how this is being maintained, should I be pulling from github `master` or NPM?

Thanks,
Chris

**Comment by wzrdtales** [comment]
Here is the v0.9.x track https://github.com/db-migrate/node-db-migrate/tree/v0.9.x
the master version is actually not relevant. The master is **newer** than the v0.9.x track and contains features and changes that are part of the incoming v0.10.x

**Comment by wzrdtales** [comment]
To answer your questions, I haden't the time when I first read your issue.

The master is currently in a WIP state and near to the first release of the v0.10.x, you can us, but always look out if the actual tests of the CI are passing.
