### ISSUE TITLE
Load options form database.json instead of command line args

### ISSUE THREAD

**Issue by mdreizin** [db-migrate/node-db-migrate#308]
It would be nice to have ability to load any options from `database.json` or `.db-migraterc` instead of command line args.

Example:

``` json
{
  "migrations-dir": "./src/migrations",
  "migration-table": "migration"
}
```
##

**Comment by wzrdtales** [comment]
All options from the CLI are also available from the config see https://github.com/db-migrate/node-db-migrate#configuration

Or do I misunderstand your problem?

**Comment by mdreizin** [comment]
@wzrdtales

Currently `db-migrate` doesn't respect `migrations-dir`, `migration-table` options from config file.

Only supported property is `sql-file` under `0.9.x` version:

```json
{
    "sql-file" : true
}
```

It would be nice if `db-migrate` can use options from config file if command line doesn't contain them.

```json
{
  "dev": {
    "driver": "pg",
    "host": "localhost",
    "database": "test"
  },
  "migrations-dir": "./src/migrations",
  "migration-table": "migration"
}
```

or

```json
{
  "dev": {
    "driver": "pg",
    "host": "localhost",
    "database": "test"
  },
  "migration": {
    "dir": "./src/migrations",
    "table": "migration"
  }
}
```

As I can see this behaviour is not supported now. Please see [node-db-migrate/v0.9.x/bin/db-migrate:139](https://github.com/db-migrate/node-db-migrate/blob/v0.9.x/bin/db-migrate#L139).

**Comment by wzrdtales** [comment]
duh! You're right, my fault. Actually this is something I have planned and wanted to do together while replacing optimist. I have moved that plans to a later point as there are other things that I'm working on currently. E.g. making the framework zero downtime friendly and other stuff, but I definitely look out to accomplis this. I also watched out for other modules that can replace optimist and probably I will go for commander.

PRs are welcome though :)

**Comment by wzrdtales** [comment]
refers to #224

**Comment by wzrdtales** [comment]
We're going to extend the defaults object with the current config for a quick fix for this issue.

**Comment by troygoode** [comment]
The `"sql-file"` option is not loaded from `database.json` if the `DATABASE_URL` env var is used.

**Comment by wzrdtales** [comment]
@troygoode Mh, yeah in the current constellation this an either or and not layered. And I don't consider this as a bug as of now.

`DATABASE_URL` is something that is only really useful to production environments, that are configured through environment configs. E.g. Docker, Heroku, ...
But it is nothing that you would use in development, and the same goes for the `sql-file` option. You don't need it in production, so the `DATABASE_URL` does not need any possibility to define it. While you can define it, just take a look at typical `DATABASE_URL` specs. E.g. on the mongodb docs https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format

Anyhow, I still don't consider this as a bug yet, unless you can show me a use case where it makes sense to have layered configurations instead.

**Comment by wzrdtales** [comment]
Also to note, you should open a new issue. Your request has nothing to do with this issue, this one is about CLI and having a `rc` style config, which is also something that is being introduced soon though.

**Comment by sa-eneidhart** [comment]
@wzrdtales was this issue ever resolved? It's closed but I tried setting `migrations-dir` in `database.json` and it didn't seem to work on 0.10.0-beta.21

**Comment by wzrdtales** [comment]
@sa-eneidhart Mh, it could be that this stalled up for quite a long time yes. In the latest version rc should be added though. Can you test the latest version?

**Comment by sa-eneidhart** [comment]
Oh, I didn't realize it had to be done in rc configs; I thought they had the same functionality. It works if I do it in `.db-migraterc`, just not in `database.json`. But that works! Thank you!

**Comment by wzrdtales** [comment]
Yes they're too different things. One really for everything around the database and the other for everything around db-migrate itself though :)
