### ISSUE TITLE
semver + Version 1.0.0?

### ISSUE THREAD

**Issue by wbecker** [db-migrate/node-db-migrate#309]
Is there any reason this hasn't launched a version 1.0.0? The public API seems pretty stable and last few releases have all just contained backwards compatible improvements, and is definitely ready for production environments. 

It would make life a lot easier if this complied with [semver](http://semver.org/), so that I could safely get new versions by putting 1.x in my package.json instead of having to check each 0.x release, which semver says should not be considered stable!
##

**Comment by wzrdtales** [comment]
As soon as the programatic API and Seeders which are going to be introduced, can be considered as stable, I will think about bumping to the first major version. However, you're right that it might be already the time to release the first major release as we're focused on keeping the API stable.

**Comment by wbecker** [comment]
Please do :smile:

**Comment by gilly3** [comment]
+1
