### ISSUE TITLE
Migrating to a specific version

### ISSUE THREAD

**Issue by edorivai** [db-migrate/node-db-migrate#313]
First off, thanks for creating this great tool!

I'd really like to be able to _just_ migrate to a specified version, without having to worry about whether the migration would be _up_ or _down_. This is already kinda possible; for `db-migrate up` I can specify the version I want to migrate to. So this leaves two problems:

1. **Determining whether to migrate up or down.**
   
   Granted, this one is of less importance. It would be more of a convenience feature.
1. **Migrating down to a specified version**

   This one is really key to me. I want to be able to perform automated updates and rollbacks of my application. The way I'd like to do that is by tying each of my application's versions to a specific _database version_. The update/rollback scripts would then run a migration for a specific version. This is currently impossible, because a rollback script would have to know _how many_ versions to roll back (as per `db-migrate down -c [count]`).

Any thoughts on this?

**Comment by wzrdtales** [comment]
This basically possible and easy to implement, and this needs to address the lowest or highest (to be) executed migration.

But I think this wouldn't be enough, if we want this feature I would also suggest to introduce tagging  of this different points in time.

**Comment by edorivai** [comment]
Yeah, I took a quick peek at the code, and it does indeed seem really easy to implement. You basically already have all of the functionality for going up. Honestly, I was kinda surprised it was possible for going up, but not for going down.

The tagging would be nice, but it wouldn't be strictly necessary for me. I will just have a configuration file that contains the version that is compatible with this version (AKA revision) of my application. So as my application evolves, I just increment the version in the config file. Rolling back will then become really easy, as the CI environment would just have to checkout a specific revision and subsequently migrate to the database version as specified in the config file.
