### ISSUE TITLE
0.10.0-beta.1 does not allow down and/or possibly up

### ISSUE THREAD

**Issue by suomi35** [db-migrate/node-db-migrate#317]
The following will produce the below error:
`npm install -g db-migrate && db-migrate down && db-migrate up`

Error:
-e/rof/.nvm/v0.10.40/bin/db-migrate -> /home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/bin/db-migrate
db-migrate@0.10.0-beta.1 /home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate
parse-database-url@0.2.2
async@1.4.2
dotenv@1.2.0
pkginfo@0.3.0
semver@5.0.3
mkdirp@0.5.1 (minimist@0.0.8)
optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
final-fs@1.6.1 (node-fs@0.1.7, when@2.0.1)
resolve@1.1.6
bluebird@2.10.2
tunnel-ssh@2.0.0 (debug@2.2.0, lodash@3.10.1, ssh2@0.4.11)
moment@2.10.6

/home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/bin/db-migrate:21
dbmigrate = DBMigrate.getInstance();
^
TypeError: Object #<Object> has no method 'getInstance'
at /home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/bin/db-migrate:21:25
at /home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:44:21
at ondir (/home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:187:31)
at onex (/home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:93:22)
at /home/rof/.nvm/v0.10.40/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:24:18
at Object.oncomplete (fs.js:108:15)

**Comment by wzrdtales** [comment]
@suomi35 Thank you for reporting.
Is it possible that you have installed locally a db-migrate version that is lower than 0.10.x?

If yes, db-migrate always prefers from 0.10.x on the local installed version. v0.9.x does not have the getInstance singleton and this would explain this failure.

This behavior is also mentioned within the breaking changes:
https://github.com/db-migrate/node-db-migrate/issues/315

**Comment by wzrdtales** [comment]
With local I do mean an installation within your project you try to execute the migrations from.

**Comment by wzrdtales** [comment]
I think I will make the startup script recognize if versions are lower than 0.10.0, so that no one has to run in this kind of issue.

**Comment by suomi35** [comment]
Thanks for the prompt attention! I am building a virtual machine via codeship and installing db-migrate in sequence with some other modules. So it should be pulling from the internet every time.
I read #315 and decided to modify as follows to grab the driver, but still get the same error:
`npm install -g db-migrate && npm install -g db-migrate-pg && db-migrate down && db-migrate up`

**Comment by wzrdtales** [comment]
Ok, does your project package.json include a lower db-migrate version as 0.10.x?

**Comment by suomi35** [comment]
`"db-migrate": "^0.9.23"`

**Comment by wzrdtales** [comment]
Yes this is the failure here. DBMigrate recognizes this and calls the 0.9.23 instead of your local project. Update this one 0.10 or just completely remove it. I will publish a patch shortly which ignores your local version if it is lower than 0.10.x and also displays an information if the local version is used.

**Comment by suomi35** [comment]
Thanks so much for the assist!

**Comment by wzrdtales** [comment]
@suomi35 My pleasure, whenever you have another question feel free to ask.

**Comment by wzrdtales** [comment]
Published a patch under 0.10.0-beta.2 including a more convient handling of this issue and better failure reporting.

**Comment by wzrdtales** [comment]
@suomi35 Considering the npm install -g db-migrate-pg  I'm also going to make this easier now that I notice that this is not working yet and make it possible to always load a driver from the local project if possible.

**Comment by suomi35** [comment]
I was about to ask you if I was missing something because it doesn't seem to be working with db-migrate-pg :) Thanks!

**Comment by suomi35** [comment]
Strangely, I still get an error about the driver not being installed. I have tried installing it with npm install -g db-migrate-pg both before and after npm install -g db-migrate. I get the error either way during the down. Is there something that has to be done in the migration scripts to point to the driver? How does db-migrate know to use the db-migrate-pg driver in the first place?
I have `"driver": "pg"` for each environment in database.json

**Comment by wzrdtales** [comment]
@suomi35 the driver pg should require for the db-migrate-pg. There is just one possibility, your using migrations from a very old schema. Can you post the failure message from the verbose mode you get please?

And also search if you're require'ing db-migrate from one of your migrations, if this is the case, this is no longer necessary and you have to replace this by the new schema or install db-migrate locally.

**Comment by wzrdtales** [comment]
You could also set the NODE_ENV to the global space this would also make node find it, but I do not suggest to do so.

**Comment by wzrdtales** [comment]
To explain, db-migrate is now self injecting into the migrations in the setup routine. I see I need to add this to the breaking changes.

**Comment by wzrdtales** [comment]
@suomi35 Have found the issue, it's located in the pg driver going to update this in an hour or so.

**Comment by wzrdtales** [comment]
@suomi35 Try to reinstall the pg driver again, I have published a patch that should fix this issue: db-migrate-pg@0.1.5

**Comment by suomi35** [comment]
Thank you for all of the explanation and the latest fix. It's all working again :)
We really appreciate your efforts on this framework.
