### ISSUE TITLE
Replace "templates"

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#320]
Remove the old "templates" and replace them with real templates, looking at handlebars and other engines. Needs to be evaluated.
##

**Comment by foysavas** [comment]
ES6 templates are probably the most future-proof and least opinionated way to do this.

Consider [`es6-template-string`](https://github.com/medikoo/es6-template-strings) as it works on node >= 0.12.

Ideally, the user should also be able to override the default templates by either passing in a path to template files or by passing in raw strings.

**Comment by wzrdtales** [comment]
@foysavas I would like to treat template extension similar to everything else. In a module fashion and also injectable through plugins.

I will have a look at your suggestion thanks for that! :)
If you want to take a stab on preparing a PR, this would be more than welcome, can't tell at which point I will move this task into the pipeline. Right now I am working on the docs. 
As always feel free to ask quesitons and I am happy to see any other suggestions you might have.

**Comment by wzrdtales** [comment]
Closed in favour of #514
