### ISSUE TITLE
Existing table

### ISSUE THREAD

**Issue by Siron** [db-migrate/node-db-migrate#325]
Started using this tool with postgres. Ran into a little bit of a blocker. 

Want to use this module for development and production, however, production already has a few tables live. Ideally, I would like to get this all working and run the migration for new environments and simply by-pass the error where the table already exists. I tried using the call back to check if(err) in the response and then move on. This however didn't work, any ideas if this is achieve-able?

**Comment by wzrdtales** [comment]
There is a if not exist option for tables, this might help you.

https://github.com/db-migrate/db-migrate-base/blob/master/index.js#L171-L174

I see now this is missing in the description but shown in the example, I will add this:
http://umigrate.readthedocs.org/projects/db-migrate/en/v0.10.x/API/SQL/#createtabletablename-columnspec-callback

**Comment by Siron** [comment]
Excellent, that should work thank you :)
