### ISSUE TITLE
Npm istall issue with version 0.10.x

### ISSUE THREAD

**Issue by Siron** [db-migrate/node-db-migrate#326]
Hello,

Whilst specifying version "db-migrate": "0.10.0-beta.4" in the package.json file then calling npm install it seems skips over installing node-db-migrate. After the install is complete all the packages have been installed apart from db-migrate. If I specify the version to be 0.9.x this issue doesn't occur. This is slightly problematic if you want to use the module's API options and run it via a .js file. Any idea what might be going on?

Package.json content - https://gist.github.com/Siron/44ec86475c7f15085a53

**Comment by wzrdtales** [comment]
I need more information from you:

- node version used
- npm version used

However, I have tried with many npm versions and node versions and all worked. How do you come to the conclusion it was skipped?

**Comment by Siron** [comment]
Information:
- Node 0.10.29
- Npm - 2.11.3

Here are the steps I used 
1. rm -rf node_module/
2. npm install 
3. ls -l node_modules

Everything is listed apart from db-migrate. If I then call npm update && npm install, then it gets installed. But I always have to call npm update first.

If I change the version to 0.9.x for db-migrate then everything is fine with just npm install. This happens across develop, integration and all other environments where jenkins handles the builds.

**Comment by wzrdtales** [comment]
First of all, you might consider updating node (0.10.40), as there are
probably many security issues with your version, apart from you're using
a quite old one.

However, I've tested with the exact same details and your package json,
no problems here.

```
ls -l node_modules/
drwxr-xr-x 4 tobi users 4,0K  7. Nov 14:08 body-parser/
drwxr-xr-x 6 tobi users 4,0K  7. Nov 14:08 bower/
drwxr-xr-x 4 tobi users 4,0K  7. Nov 14:08 coffee-script/
drwxr-xr-x 4 tobi users 4,0K  7. Nov 14:08 compass/
drwxr-xr-x 3 tobi users 4,0K  7. Nov 14:08 compression/
drwxr-xr-x 5 tobi users 4,0K  7. Nov 14:08 db-migrate/
drwxr-xr-x 6 tobi users 4,0K  7. Nov 14:08 ejs/
drwxr-xr-x 4 tobi users 4,0K  7. Nov 14:08 express/
drwxr-xr-x 5 tobi users 4,0K  7. Nov 14:08 glob/
drwxr-xr-x 3 tobi users 4,0K  7. Nov 14:08 method-override/
drwxr-xr-x 3 tobi users 4,0K  7. Nov 14:08 morgan/
drwxr-xr-x 4 tobi users 4,0K  7. Nov 14:08 request/
drwxr-xr-x 3 tobi users 4,0K  7. Nov 14:08 serve-favicon/
drwxr-xr-x 7 tobi users 4,0K  7. Nov 14:08 snapsearch-client-nodejs/
```


Am 07.11.2015 um 14:04 schrieb Siron:

**Comment by Siron** [comment]
It was a local build issue. Sorry about that. All fixed now

**Comment by wzrdtales** [comment]
@Siron Great to hear! Do not hesitate to ask again if you encounter any issues.
