### ISSUE TITLE
all scope not working

### ISSUE THREAD

**Issue by wburgers** [db-migrate/node-db-migrate#329]
Hi,

I want to use node-db-migrate to apply app version numbers to the database.
To do this I would like to use the scoping feature.
For example create a new migration file in the scope 1.0.0.
When I run `db-migrate up:1.0.0`, this works fine. But `db-migrate up:all` has no effect whatsoever.

I'm using v0.10.0-beta.4 of node-db-migrate.
The docs say that up:all should be supported.
There is only 1 new commit on the 0.10.x branch since the beta-4 release.
That commit has nothing to do with this feature.

Any clue what might be wrong?

**Comment by wzrdtales** [comment]
do you receive any error message? trying to reproduce this now

**Comment by wzrdtales** [comment]
Found the bug, fix is going to be published under beta.5

**Comment by wzrdtales** [comment]
waiting for ci now

**Comment by wzrdtales** [comment]
published

**Comment by wburgers** [comment]
Amazing!
I'll try the new release later tonight.
Thank you very much for the quick reply andere fix!
