### ISSUE TITLE
Can't set mongo host as replica sets

### ISSUE THREAD

**Issue by yaring** [db-migrate/node-db-migrate#330]
I'm using Mongodb and I want to set the host with replica sets.
https://github.com/db-migrate/mongodb/blob/master/index.js#L495
You can see it supports only one database format,
I want to do somthing like that
```
  "development": {
    "driver": "mongodb",
    "database": "somedb",
    "host": "localhost:27017/somedb,localhost:27018/somedb,localhost:27019/somedb"
  },
```

It is possible somehow?

**Comment by wzrdtales** [comment]
Short answer, no not yet.

Long answer, you're right, currently this is not supported in the way that mongodb configurations are supplied right now.

I still need to look how this can be more generalized, currently the used module https://github.com/pwnall/node-parse-database-url does not understand such a url schema.

And I think something like 

```json
  "development": {
    "driver": "mongodb",
    "database": "somedb",
    "host": [
        "localhost:27017/somedb",
        "localhost:27018/somedb,"
        "localhost:27019/somedb"
      ]
  },
```

would make more sense,  then separating with ","

**Comment by wzrdtales** [comment]
@yaring Quick Side notes on this, I will probably first introduce the config schema like the example above and measuring out what actually is the most generous way for the url schemas and taking different dbs that allow sharding in account.

**Comment by yaring** [comment]
@wzrdtales I think `db-migrate` should support connection string exactly like Mongodb does.
Maybe you can add some condition when "connectionString" is exists that it will used that instead of the more readable configuration.

Anyway, right now I can't do anything with that, right?

**Comment by wzrdtales** [comment]
Yes not yet.

**Comment by wzrdtales** [comment]
The problem with the url config is the following @yaring 
Take a look at this module https://github.com/pwnall/node-parse-database-url

This one is used some levels higher than the drivers are:
https://github.com/db-migrate/node-db-migrate/blob/master/lib/config.js#L53

Thus, this module needs to be replaced somehow and as MongoDB is really just a driver as any other, it is treated like any other. That also means I need to look if this is already the best schema to use, to say I think it probably is, wouldn't mind actually of something else, nevertheless taking a look and taking other DBs and Datastores into account is something that I'm going to do to verify that this is the best schema. Probably some could for example also use & to separate instead. However this feature is on the list and I probably will push out a fast patch for that as soon as I've made the final decision.

Thank you for reporting btw!

**Comment by yaring** [comment]
Hi @wzrdtales , Anything new about this subject? maybe can you point me and i'll try to add this feature?

**Comment by wzrdtales** [comment]
Hey @yaring,

There is already an issue at https://github.com/pwnall/node-parse-database-url/issues/6 about this. If this gets fixed, that would also make this option available to you. The changes that need to be made for mentioned here https://github.com/db-migrate/node-db-migrate/issues/330#issuecomment-166369150 would need a change in the mongodb driver initialization https://github.com/db-migrate/mongodb/blob/master/index.js#L470-L478.

I hadn't any time yet to do look at this, but it is on my list and on my mind.

**Comment by wzrdtales** [comment]
@yaring One note:

    localhost:27017/somedb,localhost:27018/somedb,localhost:27019/somedb

That string of your example, isn't this invalid? The spec tells that there can only be one db, that means this should be like this instead:

    localhost:27017,localhost:27018,localhost:27019/somedb

https://docs.mongodb.org/manual/reference/connection-string/

**Comment by wzrdtales** [comment]
This has however been implemented to define multiple hosts like in the example given above:

```json
  "development": {
    "driver": "mongodb",
    "database": "somedb",
    "host": [
        "localhost:27017",
        "localhost:27018",
        "localhost:27019"
      ]
  },
```

And this is possible too:

```json
  "development": {
    "driver": "mongodb",
    "database": "somedb",
    "port": 27017,
    "host": [
        "localhost",
        "localhost:27018",
        "otherhost"
      ]
  },
```

**Comment by wzrdtales** [comment]
This was released and published as + db-migrate-mongodb@1.1.0

**Comment by wzrdtales** [comment]
The connection string parsing will probably get fixed through the pwnall package somewhat soon. If not I will act on this.

**Comment by yaring** [comment]
@wzrdtales Awesome! Thank you!
About the connection string, it seems like the pwnall package has not been updated for over a year.

**Comment by yaring** [comment]
As for the connection string,
It seems like you're right, but it did worked for me.
Anyway I guess what you suggest is better.

**Comment by yaring** [comment]
@wzrdtales, I've look on pwnall package, it's using `url` package which parses URL and not DB URL (different behaviour).
I couldn't find any other node db url parsing but I found mongo db url parse which doing the job:
https://github.com/mongolab/mongodb-uri-node

Do you think we can add use case for Mongo to use that package instead of pwnall on your package?

**Comment by wzrdtales** [comment]
@yaring Not as long as the mongo driver does not parse the configuration by itself. Currently configuration is the job of db-migrate and not the driver. And db-migrate handles efforts to provide a reusable format for all drivers that might come to existence.

However your mentioned package might be able to handle non mongodb uris as well, I will take a look at it later though.

**Comment by yaring** [comment]
@wzrdtales Agree.
Maybe doing something like:
Try using `parseDatabaseUrl` function on driver, if not exists, use from base (kind of inheritance).

**Comment by wzrdtales** [comment]
@yaring I would not be a fan of this, but we could also pass additionally the raw unformatted config for those use cases. Also in this case db-migrate will probably be able to provide a proper handling for mongodb.

**Comment by yaring** [comment]
There is another option,
Fork parse-database-url package and add this use case over there.
@wzrdtales What do you think?

**Comment by wzrdtales** [comment]
@yaring That is what I'm going to do if @pwnall is not going to do it within the next 2 weeks.

**Comment by yaring** [comment]
@wzrdtales I can do it myself.
I'll send you a link to my fork after this change in couple of hours  and you will review it?

**Comment by wzrdtales** [comment]
@yaring Also to note if the potential PR would not be accepted after a month I would also hard fork that package and republish it.
But it is just fair to give the maintainers that time, we all have stuff to do :)

**Comment by wzrdtales** [comment]
@yaring You could do that and open the PR for it, if everything is ok and you put a tag on it I could link to the tag instead to the package version for a while.

**Comment by yaring** [comment]
@wzrdtales, Check it out and let me know what you think :)
https://github.com/pwnall/node-parse-database-url/pull/7

**Comment by wzrdtales** [comment]
I'm not sure about https://github.com/yaring/node-parse-database-url/blob/master/lib/parse-database-url.js#L35-L38 those lines. That seems a bit like wasting cycles, because actually you do the following:

- You parse the uri to extract the host and ports with the mongodb-uri model
- You build the string back to the original

That doesn't make sense from that point, I would rather add that bit of functionality to the mongodb driver to be aware of instead than doing this like that, though.

The next thing is about https://github.com/yaring/node-parse-database-url/blob/master/lib/parse-database-url.js#L42. Why do you convert it to a string? It isn't really necessary to do this.

Apart from that, this looks ok though, also to note that your test only covers mutlitple hosts, but not single ones.

**Comment by yaring** [comment]
* I agree it's a little wasting, but that's how the other package works - it returns an array and we want return comma separated string. which mongodb driver did you mean?
* Well, I wanted to keep the same returns values and same types, and the `port` return as string for all the others includes the "before fix" state.
* I've added support for single one on the commit after, you probably missed it:
https://github.com/yaring/node-parse-database-url/blob/master/test/parse_cases.json#L95

**Comment by wzrdtales** [comment]
- The db-migrate mongodb driver and the database-url package of pwnall also parses the port to a property of the config object. I think this should be designed more to fit the general behavior of the package than to fit the current expected configuration for this of db-migrate.

- Ok Ic the node url module does indeed also return a string for the parsed port
- Thats probably true :)

**Comment by pwnall** [comment]
Hey guys! 

Sorry, last time I checked, I couldn't find any indication that the mongodb driver supports the host array format. If that definitely works, I can look into the node-parse-database-url PR. I think I'll try to do the parsing without invoking an extra library before using the PR as is.

So... are we sure that the mongo driver will accept an array of hosts?

Thank you!

**Comment by pwnall** [comment]
Please take a look at the parse-database-url branch aiming to fix this issue [1] and join the conversation in [2].

[1] https://github.com/pwnall/node-parse-database-url/tree/fix_mongo
[2] https://github.com/pwnall/node-parse-database-url/issues/6
