### ISSUE TITLE
Usage in js script

### ISSUE THREAD

**Issue by jaumard** [db-migrate/node-db-migrate#334]
Is there any documentation or example for using node-db-migrate from a js script instead of command line ?

**Comment by wzrdtales** [comment]
programatic access is defined as feature for the v0.10.x version which is currently in beta. There are not that much docs about this yet: http://umigrate.readthedocs.org/projects/db-migrate/en/v0.10.x/API/programable/

But you can take a look at https://github.com/db-migrate/node-db-migrate/blob/v0.10.x/api.js#L96-L362

Expect that there might be  somethings that do not work yet, but feel free to report issues or bugs, those are normally fixed asap.

**Comment by jaumard** [comment]
Thanks ! I will look at this. Closing this :)

**Comment by wzrdtales** [comment]
No problem. Not to forget: Feel free to ask question as they come up.
