### ISSUE TITLE
Question: Renaming a collection key

### ISSUE THREAD

**Issue by pstephenson02** [db-migrate/node-db-migrate#342]
Hi,
I've been reading through the the documentation and the source a bit, but I'm working a project that uses Mongoose ODM with a couple of simple models. I would like to write a migration to rename one of the indexes on my model. e.g.

``` js
...
export const schema = new Schema({
  theirid: {
    type: String,
    required: true,
    index: true,
  },
...
```

would like to rename `theirid` to just `id`

It doesn't appear that the NoSQL API exposes a method to rename a specific index on a collection, although this method exists on the [native driver](https://github.com/mongodb/node-mongodb-native#updating-a-document).

According to the Mongoose docs, I have access to the [native driver](https://github.com/Automattic/mongoose#driver-access) through `MyModel.collection`.

Would it be possible to use this native driver api in one of the generated migrations from node-db-migrate? Or perhaps to extend the [MongoDbDriver](https://github.com/db-migrate/mongodb/blob/master/index.js) module? Any advice you have is appreciated.

Thanks in advance!
##

**Comment by wzrdtales** [comment]
Hey @pstephenson02 

You're right this is currently not implemented. You can actually try to use _run https://github.com/db-migrate/mongodb/blob/master/index.js#L260

Also this might be very limited, may be it would be the best if we would open a feature issue for this
to improve the driver here.
