### ISSUE TITLE
db-migrate up:all fails when using separate scope configurations

### ISSUE THREAD

**Issue by jcowley** [db-migrate/node-db-migrate#350]
The [documentation on scoping ](http://umigrate.readthedocs.org/projects/db-migrate/en/latest/Getting%20Started/the%20commands/?highlight=Scope%20Configuration#scoping) describes using `db-migrate up:all` to execute all scopes. However, this command fails if you use multiple scope configurations.

Here's my directory structure. 

```
migrations/
├── scope1/
│   ├── 20160209221257-test-migration.js
│   ├── config.json
│   └── sqls/
│       ├── 20160209221257-test-migration-down.sql
│       └── 20160209221257-test-migration-up.sql
└── scope2/
    ├── 20160209233047-test-migration.js
    ├── config.json
    └── sqls/
        ├── 20160209233047-test-migration-down.sql
        └── 20160209233047-test-migration-up.sql
```
Each config.json file contains the database name like so:

```json
{
  "database": "my_database_name"
}
```

running `db-migrate up:scope1` or `db-migrate up:scope2` works fine. However, running `db-migrate up:all` fails with:

```
[INFO] Enter scope "/"
[ERROR] Error: ER_NO_DB_ERROR: No database selected
```

I'm happy to dig into the source and submit a PR with a fix. However, I just want to confirm that I'm understanding the expected behavior.

**Comment by wzrdtales** [comment]
Yes this should normally work, can you please also provide a verbose run and your used node and dbmigrate version? I will try to  reproduce this later

Thank you for reporting!

**Comment by jcowley** [comment]
Node version v0.12.10

(Note: Host name removed).

```
> db-migrate up:all -v
[INFO] Using dev settings: { host: '[redacted]',
  user: 'db-migrate',
  password: '******',
  driver: 'mysql',
  multipleStatements: true }
[INFO] require: ./mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /home/ubuntu/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[ERROR] Error: ER_NO_DB_ERROR: No database selected
    at Query.Sequence._packetToError (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
    --------------------
    at Protocol._enqueue (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Connection.query (/usr/lib/node_modules/db-migrate/node_modules/mysql/lib/Connection.js:201:25)
    at Class.Base.extend.all (/usr/lib/node_modules/db-migrate/lib/driver/mysql.js:414:34)
    at Class.Base.extend.allLoadedMigrations (/usr/lib/node_modules/db-migrate/lib/driver/mysql.js:424:10)
    at Function.Migration.loadFromDatabase (/usr/lib/node_modules/db-migrate/lib/migration.js:217:10)
    at /usr/lib/node_modules/db-migrate/lib/migrator.js:103:17
    at /usr/lib/node_modules/db-migrate/lib/migration.js:211:5
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by wzrdtales** [comment]
Question, does the database you specified in the scope config already exists?

I'm trying to reproduce this tomorrow with your provided information, wont get it today anymore.

**Comment by jcowley** [comment]
Yes, it does exist. And just to restate: running `db-migrate up:scope1` and `db-migrate up:scope2` work and successfully apply the migrations. You can run `db-migrate up:all` before or after running the scope specific calls and it will fail both times with the same error above.

**Comment by wzrdtales** [comment]
Cannot reproduce this, please also provide your used db-migrate version and MySQL or MariaDB version.

**Comment by wzrdtales** [comment]
I just saw something:

```json
{ host: '[redacted]',
  user: 'db-migrate',
  password: '******',
  driver: 'mysql',
  multipleStatements: true }
```;

You do not have specified a database config in your database json, this is the cause of the failure.

**Comment by wzrdtales** [comment]
So the top has to be always configured currently, may be this is something that would make sense to change, but by default `:all` expects also the default to exist.

**Comment by jcowley** [comment]
Doesn't that defeat the purpose of having different scopes? I have two different databases, which is my motivation for separating them.

Or are you saying you provide a default in the top, then you can override with the latter scopes?

**Comment by wzrdtales** [comment]
Actually you need to have the top scope, it will always try to call that. But Ic the use case and deactivating the default one if wanted is possibly something I also would want to add as a feature.

**Comment by wzrdtales** [comment]
you do not even need any migrations in the default one, but your database.json configuration must contain a database and it will also create a migrations table.

**Comment by jcowley** [comment]
What's the use case for the separate scope configurations[ described in the current docs](http://db-migrate.readthedocs.org/en/latest/Getting%20Started/the%20commands/#scope-configuration) then? It describes having sub scopes with individual database or schema overrides. I assumed this was to allow you to target different databases with each sub-scope.

**Comment by jcowley** [comment]
Also, FWIW, you can leave the database out of database.json and specify the database in the scope-specific config. That works for targeting individual databases (on the same host) for each scope. The only thing that doesn't work is 'all'.

**Comment by wzrdtales** [comment]
yes, this and more. While the top "scope" is always the default configuration, leaving out the top scope completely is something that was not considered that time. You can also treat the default one as one scope using the direct configuration and building the other scopes around. 

And yes, you can leave out the database config, but only as long you don't execute the default "scope". The default also do not loads a scope config as it is itself not a scope.

**Comment by jcowley** [comment]
Ah, I see. I can make it work by specifying a database in the default, then overriding it in the scopes. Yeah, I'm not using the default scope for anything in my setup, since I have multiple databases there really isn't a default.

I'd still be interested in submitting a PR to allow database to only be specified in the scopes. I think if people have more than one database, they're not really thinking of it in terms of a "default" database. If you have multiple databases, there isn't a default.

**Comment by wzrdtales** [comment]
I'm open to PRs, and as already stated I would consider that as a feature to be added. The only thing left is to define how to actually define the default scope being ignored.

This could be a configuration setting directly in database.json, maybe we think a bit more in another direction and think about adding an option to the scope configs: `excludeFrom: "all"` and also make the default one loading a scope config if available.
This mentioned configuration option would also match with the plans to add groups of scopes in some far future.

**Comment by jcowley** [comment]
> The only thing left is to define how to actually define the default scope being ignored.

Since I'm new to using db-migrate, I might be missing some expected behavior here, but... to keep it simple, could this just be: 

* if migrations exist in the default scope:
  * use the settings in database.json
* if scope migrations exist:
  * use the settings in database.json by default
  * overeride _any_ settings defined in the scope's config.json

I have not looked into the relevant code yet, but based on the behavior and your description it sounds like the code is expecting migrations to exist in the default scope and is attempting to connect to the database before loading any (non-default) scopes.

**Comment by wzrdtales** [comment]
No not really, db-migrate first establishes the connection to the database including all configuration parameters, executes the create migration table method and then it calls the migrator. The migrator will now check which migrations to execute.

Also you are thinking a bit to simple:

- What happens if you do not specify a scope config?
Should we really search through all subdirectories if there are any configs containing the needed configs and if they contain migrations. I don't think this is a good solution it would just terribly slow db-migrate down, to just not use the default "scope" which is also adressable as every other scope though.
- database.json is already used by default if there is no scope config

**Comment by jcowley** [comment]
> What happens if you do not specify a scope config?

I would expect it to fail.

I'm still trying to wrap my head around the intended purpose of scopes. It would seem that if you're using scopes to separate migrations on different databases, the notion of a "default scope" doesn't make sense: e.g. you have 3 databases, which one do you consider the "default"? In this type of setup , the current behavior (requiring a "default" database) is a bit dangerous. If you forget to drop a config.json in one of your scopes, you apply a bunch of database migrations to the wrong db.

But, like I said, I just started using db-migrate so I might be missing some common use cases (or misunderstanding the general purpose of scopes). I'm looking at it from my use case: I have 2 databases, so I'm using scopes to separate the migrations for each of those databases.

**Comment by wzrdtales** [comment]
Scopes are not necessarily only for different databases. They are also to just organize your migrations into *scopes*.
Lets say you have user and product tables, and you create the scope user and product. At first scopes are to have the option to better separate your migrations.

But, also do scope enable to have different configurations on them, or change just a few settins. Currently scopes do only support the features described in the docs and not more, but I want to extend them to also make them able to connect to different databases on other servers and to use other drivers, but this actually something that has a very low priority currently.

**Comment by jcowley** [comment]
Ah, okay. Well, thanks for the clarification and bearing with me on all the back and forth. Thanks as well for creating a really useful library. 

I do still think the current behavior (requiring a default 'database' definition in database.json) is a bit unexpected when you are using a scope for each individual database. But maybe that's not such a common use case.

I submitted [a PR](https://github.com/db-migrate/english-docs/pull/6) with some clarifications on the scope configuration. Aside from the what we've discussed in this issue, the required file name for the scope config wasn't documented. I had to look at the source code to figure out it was looking for a file name 'config.json'.

**Comment by wzrdtales** [comment]
Yes it is unexpected if you intend to use it for different databases only, but not if you think of just separating migrations without changing the database. I use scopes really often to structure them though. But also for that we will find a solution that works.

I have seen the PR and will take another look later.

And also no problem, if you have any other questions, do not hesitate I will be happy to answer.
