### ISSUE TITLE
Add an example how to seed VC data

### ISSUE THREAD

**Issue by koistya** [db-migrate/node-db-migrate#352]
##

**Comment by staff0rd** [comment]
https://docs-0-10.dbmigrate.wizardtales.com/API/Seeder

**Comment by StlthyLee** [comment]
@staff0rd the link you have posted to the documentation for seeder doesn't work, it's throwing a 502.

**Comment by perrygeorget** [comment]
@staff0rd can you provide an updated link?  I have no luck with it either.

**Comment by wzrdtales** [comment]
closing and referring to #292 more to this topic later this week
