### ISSUE TITLE
elasticsearch driver

### ISSUE THREAD

**Issue by mllanes** [db-migrate/node-db-migrate#355]
Does anybody knows if support for elasticsearch is or would be developed in the near future? If not, is there any 3rd party implementation for it out there?
Thanks.
##

**Comment by wzrdtales** [comment]
small tip: every db-migrate driver needs to start with `db-migrate-`, I've seen yet only a cassandra driver and the hana driver that you can the wip in the pull requests developed by @MitchK.

You can search like this for drivers:
https://www.npmjs.com/search?q=db-migrate+cassandra

In your case there is currently no such driver:
https://www.npmjs.com/search?q=db-migrate+elastic

I currently do not plan to develop an elasticsearch driver myself, but if you want to do you I support everyone who is developing a driver and has questions.
