### ISSUE TITLE
Cassandra driver

### ISSUE THREAD

**Issue by charyorde** [db-migrate/node-db-migrate#356]
^^ https://github.com/charyorde/db-migrate-cassandra

#### Todos
- Implement `createTable, renameColumn, removeColumn` APIs to be fully Cassandra compatible. Need db-migrate-base to take extra options argument.
- Implement seeders for `renameTable`. Currently, renaming a table is not supported in Cassandra 
- Add tests

**Comment by wzrdtales** [comment]
@charyorde Have already seen it a while ago :)

I also want to make a public directory where community drivers as well as officially supported drivers are listed. I generally want everything more friendly to new users, first steps taken for the documentation (yes I move again, I move away from readthedocs, because of missing search support   for mkdocs which is not likely to be fixed anytime soon https://github.com/rtfd/readthedocs.org/issues/1487).

Keep up the work and let me know if you have some questions, I will be happy to answer.

**Comment by charyorde** [comment]
I decided to create a new issue for support purposes.

As stated above, I'll need extra options passed to the `createTable, renameColumn, removeColumn` base APIs in order to support Cassandra `WITH` property and `AND` properties. 
For example, `ALTER TABLE users
  WITH compaction =
  { 'class' : 'SizeTieredCompactionStrategy', 'min_threshold' : 6 };`

Perhaps, this is what the `changeColumn` API can handle?

**Comment by wzrdtales** [comment]
The base api doesn't needs to be adjusted for this, you can always extend and overwrite everything from the base. As soon as you're doing this you will need to document this for your users to make them know of that extended features that are only specific to your driver.

I'm not sure if this is something for `changeColumn` as you're not really changing a column.

**Comment by wzrdtales** [comment]
`ALTER TABLE users WITH compaction = { 'class' : 'SizeTieredCompactionStrategy', 'min_threshold' : 6 };`

For actions like this, there is very probably a `changeTable` missing right now. This is something that I will also add for `MariaDB` and `MySQL`, to change for example the engine of the table. If you want to add `changeTable` as API option, this is also something that will made into the standard of the API of db-migrate. The definition will be the same as for changeColumn, except for the column param naturally.

**Comment by charyorde** [comment]
Noted.

On another note, what triggers the create of migrations table? Is it `db-migrate create` or `db-migrate up`

**Comment by charyorde** [comment]
This explains it:
```
function executeUp(internals, config, callback) {

  ...

    migrator.driver.createMigrationsTable(function(err) {
      assert.ifError(err);
      log.verbose('migration table created');

      migrator.up(internals.argv, internals.onComplete.bind(this,
        migrator, callback));
    });
  });
}```

**Comment by wzrdtales** [comment]
Y. Just the up, down and some other functions are creating this table, but not create which creates a boilerplate migration.

**Comment by charyorde** [comment]
@wzrdtales I can't seem to get the [cassandra driver](https://github.com/charyorde/db-migrate-cassandra/blob/master/test/database.json#L7) to resolve as expected.

Looking at this [line](https://github.com/db-migrate/node-db-migrate/blob/master/lib/driver/index.js#L46) , I was expecting it to lookup the NPM module (db-migrate-cql), but I'm getting the `Cannot find module 'db-migrate-cql'` error when I run `db-migrate up --config database.json -e dev`.

The db config file looks like this:
```
{
  "dev": {
    "keyspace": "db_migrate_test",
    "user": "cassandra",
    "password": "cassandra",
    "driver": {
        "require": "db-migrate-cql"
    },
    "host": "localhost",
    "hosts": ["127.0.0.1"]
  },

  "sql-file": true
}
```
If I reference the driver locally, it works.

**Comment by charyorde** [comment]
Installing globally resolve this: `npm i -g db-migrate-cql`

**Comment by wzrdtales** [comment]
@charyorde This is a configuration schema I am going to deprecate.
https://github.com/db-migrate/node-db-migrate/blob/master/lib/driver/index.js#L45-L46

This circumvents the enforced naming schema. You would configure it like this normally:

```json
{
  "dev": {
    "keyspace": "db_migrate_test",
    "user": "cassandra",
    "password": "cassandra",
    "driver": "cql",
    "host": "localhost",
    "hosts": ["127.0.0.1"]
  },

  "sql-file": true
}
```

**Comment by wzrdtales** [comment]
I also just saw that your driver is another cassandra one, thought it would be the one I already known of :)

https://www.npmjs.com/search?q=db-migrate+cassandra

Btw. don't forget to add documentation to your driver, so the users now about methods like `createKeyspace`  are available ;)

**Comment by charyorde** [comment]
Cool. `"driver": "cql",` works as well.

On `createKeyspace`, does db-migrate support database creation if not exist before start of migration?

**Comment by wzrdtales** [comment]
Principially yes, but currently there are known issues that this does not work yet.

**Comment by wzrdtales** [comment]
This one here https://github.com/db-migrate/node-db-migrate/issues/338

**Comment by ramakrishnan** [comment]
HI @wzrdtales,

I did some initial work on getting a Cassandra driver for node-db-migrate. https://github.com/ramakrishnan/db-migrate-cassandra, see if this helps you.

**Comment by charyorde** [comment]
@wzrdtables, I need some help with getting out of TTY after the db migrate script is done executing. 

Even though I did implemented the close handler as seen at https://github.com/charyorde/db-migrate-cassandra/blob/master/index.js#L297 , but when the db-migrate script finished executing, it gets stuck at
```
[INFO] Processed migration 20160520102242-add-userstat
INFO] Done
```
Any ideas on how to get around this please?
Appreciate your help.

**Comment by charyorde** [comment]
@wzrdtales , I need some help with getting out of TTY after the db migrate script is done executing. 

Even though I did implemented the close handler as seen at https://github.com/charyorde/db-migrate-cassandra/blob/master/index.js#L297 , but when the db-migrate script finished executing, it gets stuck at
```
[INFO] Processed migration 20160520102242-add-userstat
INFO] Done
```
Any ideas on how to get around this please?
Appreciate your help.

**Comment by wzrdtales** [comment]
Sure let me quickly setup a docker env for this.

**Comment by wzrdtales** [comment]
@charyorde That error is simple, you're not calling the method to actually close the driver, but you define an event listener. An event that is never going to be called though.

Like this, this can't work though: https://github.com/charyorde/db-migrate-cassandra/blob/master/index.js#L298-L300

Here is a working example:

```javascript
close: function(callback) {
    return new Promise( function( resolve, reject ) {

      this.connection.shutdown(function(err) {
        if( err ) {
          return reject( err );
        }
        log.verbose("Cassandra connection closed")
        resolve();
      });
    }.bind(this) )
    .nodeify(callback);
  }
```

**Comment by charyorde** [comment]
Thanks @wzrdtales . Works great. Published a new version with this fix.

**Comment by wzrdtales** [comment]
@charyorde Currently cleaning up the issues, I will close here now. Please feel free to hit me up anytime if you've got any questions.
