### ISSUE TITLE
switching to different dbs on the same mongo server instance

### ISSUE THREAD

**Issue by tal-ni** [db-migrate/node-db-migrate#366]
I'm trying to understand how can i work with multiple dbs on the same mongo instance/server. 
(for example localhost:27017)

I read in the docs that there is a scope configuration that can allow me to switch between dbs on the same instance.

Can you please explain and elaborate on this how can i define this sub configuration:
1. should it be in the same file configuration?
2. should i create a sub directory under configuration folder with the same migration name?
3. Can you please provide a live configuration example how can i run one migration on multiple dbs on the same server instance?

Here is what written in the documentation

Scope Configuration

You can also configure the scope to specify a sub configuration. Currently you can only define database and schema within this config.

**This config file is used to tell db-migrate to switch to the database** or schema. Databases is used for most databases, except postgres which needs the schema variable.

It's currently also not possible to switch the database over this config with postgres.

{
  "database": "test",
  "schema": "test"
}

You also wrote to me in email that :”db-migrate provide yet only the possibility to switch to another **db/collection on the same server** with the same connection”.

This is exactly what I need.   I need to switch from one db to another db on the same server and run the same migration on those different dbs  on the same server.

Is this supported?

I “played” with the configuration and sub configuration but was not able to figure out how this solution can this be achieved.

Can you please  supply some of example so I can understand how to solve this problem>

Thanks in advance.
##

**Comment by wzrdtales** [comment]
This is supported as soon as switchDatabase is implemented on the driver you're using, concerning mongodb:

https://github.com/db-migrate/mongodb/blob/master/index.js#L64-L79

In this case this is in place, I look to try to give you an example in the next days.

**Comment by rcosta-gcare** [comment]
Anyone able to switchDatabase?? I'm trying to figure how to use this.

**Comment by WClouds** [comment]
@wzrdtales Hi, is there any examples about how to use switchDatabase? I am working with multiple dbs on the same mysql server/instance, and I need to switch db when migrating.
