### ISSUE TITLE
node v6 support

### ISSUE THREAD

**Issue by timelessvirtues** [db-migrate/node-db-migrate#375]
Password authentication error for all migrations using Node v6.0.0 or v6.1.0.  Works fine using 4.x & 5.x.

**Comment by wzrdtales** [comment]
I will add node 6 to the ci to track its status.

**Comment by wzrdtales** [comment]
added https://github.com/db-migrate/node-db-migrate/commit/baabd7e77693afdd62356e4473365df16419e418

https://travis-ci.org/db-migrate/node-db-migrate/builds/129820334

**Comment by wzrdtales** [comment]
tracked as upstream issue https://github.com/db-migrate/sqlite/issues/2

**Comment by wzrdtales** [comment]
Waiting for sqlite to update.

**Comment by wzrdtales** [comment]
@timelessvirtues Can you please also tell me which driver you tested where you had your problems?

**Comment by timelessvirtues** [comment]
Postgres driver talking with 9.5.2

**Comment by wzrdtales** [comment]
Alright.

**Comment by wzrdtales** [comment]
tracked as upstream issue https://github.com/db-migrate/pg/issues/9

**Comment by wzrdtales** [comment]
@timelessvirtues For postgres an fix is available, going to pull that in into the driver release and probably also apply it to the 0.9.x track.

**Comment by wzrdtales** [comment]
# Postgres Status
- [ ] 0.9.x
- [x] 0.10.x beta track

released as
+ db-migrate-pg@0.1.10

**Comment by wzrdtales** [comment]
# Sqlite Status

- [ ] 0.9.x track
- [ ] 0.10.x beta track

Current state: Waiting for upstream

**Comment by wzrdtales** [comment]
Node 6 support should be given as of now
