### ISSUE TITLE
Undefined on sql file if migrations folder doesn't exist

### ISSUE THREAD

**Issue by RafaelSalguero** [db-migrate/node-db-migrate#376]
With the option `sql-file` = true, when creating the first migration, if the `migrations` folder doesn't exists, it is created but the file names have undefined on its name:

```
20160517180317-undefined-down.sql
20160517180317-undefined-up.sql
```

If the migrations folder already exists the files are correctly named

```
20160517180317-initial-down.sql
20160517180317-initial-up.sql
```

**Comment by wzrdtales** [comment]
Can't reproduce this, can you please post your used db-migrate version node version and the executed commands including a verbose run? Thanks

**Comment by RafaelSalguero** [comment]
sure
`db-migrate --version` = `0.10.0-beta.11`

`node --version` = `v5.11.1`

**database.json** :
```
{
    "dev" : {
        "driver" : "pg",
        "user" : "postgre",
        "password" : "123456", 
        "host" : "localhost",
        "database" : "example",
        "schema" : "public"
    },
    "sql-file" : true
}
```

**Running the command without migrations folder**
`db-migrate create initial --verbose`

```
[INFO] Detected and using the projects local version of db-migrate. 'c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\node_modules\db-migrate\index.js'
[INFO] Using dev settings: { driver: 'pg',
  user: 'postgre',
  password: '******',
  host: 'localhost',
  database: 'example',
  schema: 'public' }
[INFO] Created migration up sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517181559-undefined-up.sql
[INFO] Created migration down sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517181559-undefined-down.sql
[INFO] Created migration at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\20160517181559-initial.js
``` 

**Running the command with existing migrations folder**

`db-migrate create initial --verbose`

```
[INFO] Detected and using the projects local version of db-migrate. 'c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\node_modules\db-migrate\index.js'
[INFO] Using dev settings: { driver: 'pg',
  user: 'postgre',
  password: '******',
  host: 'localhost',
  database: 'example',
  schema: 'public' }
[INFO] Created migration up sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517181659-initial-up.sql
[INFO] Created migration at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\20160517181659-initial.js
[INFO] Created migration down sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517181659-initial-down.sql
```

**Comment by RafaelSalguero** [comment]
Ups I forgot to say that I have a  `db-migrate.cmd` file with the following content:

```
node node_modules/db-migrate/bin/db-migrate %*
```

This is only so I can use the short `db-migrate` command without the need for installing it globally

**Comment by wzrdtales** [comment]
Still can't reproduce this, I guess I will need to get on a windows machine to reproduce this.

**Comment by wzrdtales** [comment]
First of all, if using locally it is highly recommended to install db-migrate globally. db-migrate does prefer your local version over the global one anyway if it can find one from v0.10.x upwards.

And second, I have tried now many times with different things, but I was not able to reproduce your error even on windows.

Third: you don't need to create a cmd file for db-migrate. Npm does that for you already, take a look into your node_modules/.bin folder. You can always add this temporarily to your path.

**Comment by wzrdtales** [comment]
To be more specific, it is only not recommended to use db-migrate not installed globally if and only if you're using it with the programable api.

**Comment by RafaelSalguero** [comment]
I did a little debugging and found that when the directory doesn't exists the method call of `createMigrationDir` on the method `executeCreateMigration` executes after the `createSqlFile`, this is where the variable `internals.argv.title` is assigned, when the directory already exists this method finishes before the `createSqlFile`, thus the variable is already assigned

**Comment by wzrdtales** [comment]
Do you anything else you might have forget? I have tested now on two systems, arch linux and windows and wasn't able to reproduce your issue. I have used your config and the exact same commands. I have create a db-migrate.cmd with your mentioned content but nothing, everything works as it should.

**Comment by RafaelSalguero** [comment]
Adding the following logs on this lines yield to different results when the directory already exists or not:

```js
//just before assigning title variable
548:  console.log("create migrations createMigrationDir assign title");

//just before calling the if (shouldCreateSqlFiles(internals, config))
592: console.log("shouldCreateSqlFiles " +  internals.argv.title );

//just before calling var migrationUpSQL = new Migration(internals.argv.title + ...
642:     console.log("createSqlFile internals " +  internals.argv.title );
```

The results are different:

**When the directory exists**
```
shouldCreateSqlFiles undefined
create migrations createMigrationDir assign title
createSqlFile internals initial
[INFO] Created migration up sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517183754-initial-up.sql
[INFO] Created migration at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\20160517183754-initial.js
[INFO] Created migration down sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517183754-initial-down.sql
```

**When directory doesn't exists**
```
shouldCreateSqlFiles undefined
createSqlFile internals undefined
[INFO] Created migration up sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517183809-undefined-up.sql
create migrations createMigrationDir assign title
[INFO] Created migration down sql file at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\sqls\20160517183809-undefined-down.sql
[INFO] Created migration at c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton\server\migrations\20160517183809-initial.js

```

I hope this helps.

**Comment by wzrdtales** [comment]
Hm yeah this seems to be a very rarely occuring bug, but I have found the source:
https://github.com/db-migrate/node-db-migrate/blob/v0.10.x/api.js#L591-L598

That callback might be called to early, I really don't know why this is not in the callback of the migration. Going to fix this.

**Comment by wzrdtales** [comment]
Waiting for ci, bugfix release follows soon.

**Comment by wzrdtales** [comment]
published as
+ db-migrate@0.10.0-beta.12

Please let me know if you have any further problems.

**Comment by RafaelSalguero** [comment]
Thank you!
