### ISSUE TITLE
--dry-run prints even executed migrations

### ISSUE THREAD

**Issue by SilentScope** [db-migrate/node-db-migrate#377]
When I run 'db-migrate up:mydb' I get:

[INFO] loaded extra config for migration subfolder: "mydb/config.json"
[INFO] No migrations to run
[INFO] Done

When I run 'db-migrate up:mydb --dry-run' I get:

[INFO] dry run
[INFO] loaded extra config for migration subfolder: "giga/config.json"
................
all the previous migrations are printed

**Comment by wzrdtales** [comment]
Please **always** provide everything needed to reproduce your issues.

This includes:
- a verbose run
- used db-migrate version
- used db-migrate driver
- used node version
- used npm version

And if necessary also migrations amd config details to reproduce.

**Comment by SilentScope** [comment]
Version: 0.10.0-beta.12
I expect to see only SQL migrations that should be performed when running with --dry-run option

May be I am doing smth wrong?

**Comment by wzrdtales** [comment]
Still missing the verbose run, used driver and so on. Without any information I can't help you and currently I have exactly nothing to see any behavior or do have steps to reproduce it.

**Comment by SilentScope** [comment]
Attached test: [db-migrate-issue-377.zip](https://github.com/db-migrate/node-db-migrate/files/281315/db-migrate-issue-377.zip)

I use:
- Node.js 4.4.3
- NPM 2.15.1
- MySQL 5.5.49 (please update database JSON - I use non standard port)

Top run test: npm run up

I expect dry run to say: No migrations to run, however, I get SQL printed

**Comment by SilentScope** [comment]
By the way - thanks for quick previous responses :)

**Comment by wzrdtales** [comment]
Got it thanks, tracked as upstream issue here:
https://github.com/db-migrate/mysql/issues/5

**Comment by SilentScope** [comment]
I tried the workaround https://github.com/db-migrate/mysql/issues/5 (using all) but it did not help.

**Comment by wzrdtales** [comment]
@SilentScope It is not a workaround but a fix suggestion which needs a change at the driver level. I will look at this in a few hours.

**Comment by wzrdtales** [comment]
fixed, published as
+ db-migrate-mysql@1.1.7

You can upgrade to this new driver version as of now.

**Comment by SilentScope** [comment]
It works as expected now - thanks a lot! :)
