### ISSUE TITLE
Updating to v0.9.25 breaks existing migrations

### ISSUE THREAD

**Issue by mathi123** [db-migrate/node-db-migrate#378]
I am not able to run migrations anymore, after updating to v0.9.25

Node version: v5.10.0, v6.2.1
Npm version: v3.9.3
db-migrate version: v0.9.25
db-migrate-pg version: v0.1.10

When I downgrade to db-migrate@v0.10.0-beta.12, all is working again.

Are there any breaking changes? If so, where can I find them?

Verbose run:
```
db-migrate up --verbose
[INFO] Using dev settings: { driver: 'pg',
  user: 'pg-mitasco',
  password: '******',
  database: 'mitasco-dev3',
  host: 'localhost' }
[INFO] require: ./pg
[INFO] connecting
[INFO] connected
[SQL] select version() as version
[SQL] SHOW search_path
[SQL] SET search_path TO "$user","public"
[SQL] SELECT table_name FROM information_schema.tables WHERE table_name = 'migrations' AND table_schema = 'public'
[INFO] migration table created
[INFO] loading migrations from dir /Users/Ubuntu/WebstormProjects/mitasco/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM "migrations" ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20160515183034-a
[SQL] BEGIN;
[ERROR] TypeError: Promise is not a constructor
    at exports.up (/Users/Ubuntu/WebstormProjects/mitasco/migrations/20160515183034-a.js:23:12)
    at Migration._up (/Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/lib/migration.js:172:32)
    at Migration.up (/Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/lib/migration.js:184:8)
    at Object.Migrator.up (/Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/lib/migrator.js:84:7)
    at /Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/lib/migrator.js:116:18
    at .callback (/Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/lib/driver/pg.js:17:44)
    at Query.handleReadyForQuery (/Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/node_modules/pg/lib/query.js:89:10)
    at .<anonymous> (/Users/Ubuntu/.nvm/versions/node/v6.2.1/lib/node_modules/db-migrate/node_modules/pg/lib/client.js:163:19)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
```

**Comment by wzrdtales** [comment]
Um, was it intended that you downgraded to 0.**9**.25 when you have been on 0.**10**.x before?

**Comment by wzrdtales** [comment]
current version of 0.10.x track is https://github.com/db-migrate/node-db-migrate/blob/v0.10.x/package.json#L34

**Comment by wzrdtales** [comment]
I guess you really accidentally downgraded without noticing this.

**Comment by mathi123** [comment]
Hmm, yes my question is quit stupid indeed then. 

Yet my travis build stopped working suddenly, because of that error.
The default package npm gets is a 0.9.xx one?

I am wondering how I got that 0.10.x package, and started working with it in the first place...

**Comment by mathi123** [comment]
same for Travis, it worked before,
must have been because it got a 0.10.x package? 

I am still confused, anyways I will close and force a 0.10.x package in my travis build:

```
before_script:
  - npm install -g db-migrate@@v0.10.0-beta.12 db-migrate-pg
```

Thx for the reply!

**Comment by wzrdtales** [comment]
That is strange indeed, npm always pulls a version first that has no suffix like `-betaxxx`. NPM would get 0.9.x as a default.

**Comment by mathi123** [comment]
FYI, looking back in my travis build history,
looks like npm on travis did pull a beta package, without the suffix:
<img width="924" alt="schermafbeelding 2016-06-05 om 21 16 26" src="https://cloud.githubusercontent.com/assets/3677437/15807612/f248bd46-2b62-11e6-9daf-7f106ce0bfec.png">

**Comment by wzrdtales** [comment]
Either we have a cache problem or the behavior of npm has changed somehow.
