### ISSUE TITLE
Unable to parse migration name

### ISSUE THREAD

**Issue by DarthLabonne** [db-migrate/node-db-migrate#379]
When I try to run "up" (with or without --dry-run), I end up with this error:

> [ERROR] TypeError: Cannot read property '1' of null
>     at Class.extend.parseName (/home/me/Documents/project/node_modules/db-migrate/lib/skeleton.js:162:17)
>     at Class.Skeleton.extend.init (/home/me/Documents/project/node_modules/db-migrate/lib/migration.js:35:24)
>     at Class.prototype.(anonymous function) [as init] (/home/me/Documents/project/node_modules/db-migrate/lib/class.js:36:24)
>     at new Class (/home/me/Documents/project/node_modules/db-migrate/lib/class.js:49:17)
>     at /home/me/Documents/project/node_modules/db-migrate/lib/migration.js:336:16
>     at Array.map (native)
>     at /home/me/Documents/project/node_modules/db-migrate/lib/migration.js:335:10
>     at tryCatcher (/home/me/Documents/project/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise.successAdapter [as _fulfillmentHandler0] (/home/me/Documents/project/node_modules/bluebird/js/release/nodeify.js:23:30)
>     at Promise._settlePromise (/home/me/Documents/project/node_modules/bluebird/js/release/promise.js:556:21)
>     at Promise._settlePromise0 (/home/me/Documents/project/node_modules/bluebird/js/release/promise.js:604:10)
>     at Promise._settlePromises (/home/me/Documents/project/node_modules/bluebird/js/release/promise.js:683:18)
>     at Async._drainQueue (/home/me/Documents/project/node_modules/bluebird/js/release/async.js:138:16)
>     at Async._drainQueues (/home/me/Documents/project/node_modules/bluebird/js/release/async.js:148:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (/home/me/Documents/project/node_modules/bluebird/js/release/async.js:17:14)
>     at tryOnImmediate (timers.js:534:15)

I tried renaming the migration file but it won't work.

I'm using version 0.10.0-beta.12 and NodeJS v5.11.1

**Comment by wzrdtales** [comment]
db-migrate enforces a specific name schema. Please create migrations only with the db-migrate command:

    db-migrate create nameofyourmigration

A valid migration name would be `20160216092736-test.js` for example. If you have any further problems, feel free to ask right away.

**Comment by DarthLabonne** [comment]
Nope, it doesn't change anything.
I'm already using the db-migrate command to generate the file.

db-migrate create add-state-to-table
db-migrate create test

Those files are created:
migrations/20160620014326-add-state-to-table.js
migrations/20160620014419-test.js

I still get the aforementioned error.

**Comment by wzrdtales** [comment]
Then please provide all informations that are needed to reproduce.

Please post the output of a complete verbose run, db-migrate driver + version, example migration that fails for you

**Comment by wzrdtales** [comment]
Also please report your operating system, that might be an issue too.

**Comment by wzrdtales** [comment]
Fact is the failure from above is here:
https://github.com/db-migrate/node-db-migrate/blob/v0.10.x/lib/skeleton.js#L160-L163

Your mentioned names would work though: http://regexr.com/3dlf4, I expect that there is something else wrong. Please post all needed informations to continue on this topic.

**Comment by wzrdtales** [comment]
The best case btw. would be if you prepare a gist that you can verify to reproduce the exact behavior you experience.

**Comment by wzrdtales** [comment]
Any updates on that topic? Did you figured it out or still having problems? If yes please provide a reproducable case to make us able to help you.

**Comment by DarthLabonne** [comment]
Nope. Doesn't work for me so I used something else instead.

Here is a sample migration:

```javascript
'use strict';

var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  db.createTable("routers", {
        "id": {
            "type": "int",
            "primaryKey": true,
            "autoIncrement": true
        },
        "ip_address": {
            "type": "inet",
            "unique": true,
            "notNull": true
        }
    });
};

exports.down = function(db) {
  db.dropTable("routers");
};
```
Filename is `20160615035022-create-router-table.js` and generated with the db-migrate command.
Anyway, I have a strict deadline so I just used something else instead so you can close this issue.

**Comment by wzrdtales** [comment]
Sry for you, but if you're not able to provide details no one is able to help you. We must be at least be able to reproduce.

**Comment by oncletom** [comment]
I faced the same issue, and it happens it was because I had an  `.eslintrs.js` file within the `./migrations` folder.

**Comment by ivan-jorge001** [comment]
If there is any js file inside the /migration/ it will fail
