### ISSUE TITLE
Modernize the syntax in new migration files

### ISSUE THREAD

**Issue by tuckerconnelly** [db-migrate/node-db-migrate#383]
Recommend using [airbnb's eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) and using all of the new es6 features that Node supports
##

**Comment by wzrdtales** [comment]
I say to this yes and no.

A maybe yes to airbnbs eslint config, I will have a look at it though :)

But I definitely say no to es6 by default yet. I still want to have a backwards compatibility down to 0.10 also I think about dropping that support somewhat soon.

Though as you just talk about the migration files, I don't think also that it would be right to recommend a specific styleguide, if it would even make sense to actually recommend such thing, although there might be nothing wrong in metioning. Besides of airbnbs there are many that are quite good too though.

**Comment by wzrdtales** [comment]
May be you elaborate a bit more and go into detail, how you imagine to make things better, so I and everyone else gets a better understanding.
And again about the es6 thing, yes I am on your side on this generally, but not in terms of compatibility. But I want to have better templates anyway and thought about adding support for custom templates to give more powerful access to scaffolding.
If you want to take a stab on this, feel welcome to do though :)

**Comment by wzrdtales** [comment]
@tuckerconnelly Would you mind to may be elaborate a bit more on what you exactly wanted? Otherwise I'm closing here.

**Comment by tuckerconnelly** [comment]
I created my own migration library, https://github.com/tuckerconnelly/es-migrate

**Comment by wzrdtales** [comment]
Ah ok cool thing :)
Still waiting for the day where async really b/c supported and does not needs to be transpiled though :)

So am I right that you just wanted to have migration templates make use of the async/await features?

**Comment by tuckerconnelly** [comment]
That and no semicolons :) and a way to sync to a particular database version (instead of imperatively describing how to up/down to get there), so you can associate a docker image with a database version

**Comment by wzrdtales** [comment]
> Or, more generally, a way to create custom templates without forking.

That is something that is going to be added.

> Also, a way to sync to a particular database version (instead of imperatively describing how to up/down to get there), so you can associate a docker image with a database version

So you want what instead? A dump or what exactly are you thinking of?

**Comment by tuckerconnelly** [comment]
Instead of `db-migrate up` and `db-migrate down`, I can do `es-migrate sync 123456`, and it'll do whatever ups or downs it has to do to get there to get to version `123456`. This is useful because when I deploy a new version of the app, I know it'll definitely automatically be synced the version of the database it's compatible with.

This is similar to Rails' `db migrate VERSION=123456`

I'm good though :) I don't need anything from db-migrate, es-migrate is enough for me.

**Comment by wzrdtales** [comment]
@tuckerconnelly No worries, I just try to understand your use case and the `sync` method makes sense though. Good thing you're fine with your own lib though :)

Thanks for giving your input.

**Comment by wzrdtales** [comment]
Refers to #388, #397

**Comment by wzrdtales** [comment]
Refers to #313

**Comment by wzrdtales** [comment]
Closing here.

Current efforts:

 - Sync was included.
 - Flexible Template #514
 - New migration schema for atomic operations and zero downtime friendliness #508
