### ISSUE TITLE
beta published

### ISSUE THREAD

**Issue by gflarity** [db-migrate/node-db-migrate#389]
Hi, new upgraded db-migrate today and the latest version seems to be 0.10.0-beta.15. The beta is a bit concerning to us. I'm assuming it's not ready to be widely used if it's beta?

Please consider doing this in the future: 
https://coderwall.com/p/l_7acq/publish-beta-versions-of-npm-modules

**Comment by wzrdtales** [comment]
Thanks good hint!

Concerning the beta title, every published version to npm is tested on the ci, so everything that worked before would still work. And I know many using the beta version already and that for quite a while, it is unlikely that you would run into big trouble. Beta also not always means that a software is unstable in general, but that some features change or that are listed for this release may not work completely and are not in a final state. But in terms of db-migrate at least, the beta note is really that this is a pre-release with new features that aren't yet final, while everything that worked before is kept focus on to keep it backwards compatible. 

There is just one little detail you would need to know if you consider using the 0.10.x version:

You need to install the driver for your database additionally, as they have been moved out into separate projects to allow db-migrate to be more flexible and extensible. There are also already some community drivers out there, relying on this.

Actually the only thing right now in 0.10.x that is or better was listed as feature are seeders. I have recently moved seeders into the next milestone, so they are not part of that 0.10.x milestone anymore and should not be expected to work yet.
