### ISSUE TITLE
Callback not being triggered on "up" on DBMigrate instance

### ISSUE THREAD

**Issue by apires** [db-migrate/node-db-migrate#390]
Hi all,

This is how we're triggering the migrations in our code (perhaps this is the wrong way):

```javascript
  const DBMigrate = require('db-migrate');
  const m = DBMigrate.getInstance(true, {config: {env: db }, env: 'env'});

  console.log("Loading test DB...");

  m.up(function(err){
    if(err){ console.log('Error loading test DB.'); console.log(err); }

    console.log('data loaded!');
    done(err);
  })
```

When we do that I noticed that the callback for "UP" doesn't get called; seems like the API expects the callback to always be the third parameter but the documentation around the function makes it seem like the number of arguments is variable, and this causes the callback to disappear.

I propose something like this to address this issue, if indeed it's not user error and we were not supposed to call `up` directly. Similarly we're calling `down` in other places.

```javascript
  up: function(specification, scope, callback) {
    var cb = callback;

    if (arguments.length > 0) {
      if (typeof(specification) === 'string') {

        this.internals.argv.destination = specification;
      } else if (typeof(specification) === 'number') {

        this.internals.argv.count = specification;
      } else if(typeof specification === 'function'){
        cb = specification;
      }

      if (typeof scope !== 'function' ) {
        this.internals.migrationMode = scope;
      } else {
        cb = scope;
      }
    }
    executeUp(this.internals, this.config, cb);
  },
```

**Comment by wzrdtales** [comment]
Hey @apires

Can you please tell me which db-migrate version you use? There have been some changes to the programable API allowing exactly what you are trying.


You can find some examples here:
https://github.com/db-migrate/api-examples

In callback style:
https://github.com/db-migrate/api-examples/blob/master/index.js

And what I suggest to everyone, in the new promise style:
https://github.com/db-migrate/api-examples/blob/master/promise.js

**Comment by wzrdtales** [comment]
The latest up code also looks like:

https://github.com/db-migrate/node-db-migrate/blob/v0.10.x/api.js#L162-L185

So may be you're not on the latest db-migrate version which includes that since a short time period.

**Comment by apires** [comment]
You're right, we're a bit behind: 
```
    "db-migrate": "^0.10.0-beta.11",
    "db-migrate-pg": "https://registry.npmjs.org/db-migrate-pg/-/db-migrate-pg-0.1.9.tgz",
```

I'll update to the latest version of the package and re-write to follow that style. I'll open an issue if I find anything wrong with that.

Thank you for the quick response!
