### ISSUE TITLE
bug: db-migrate create:scope doesn't create directory, nor uses one if it exists

### ISSUE THREAD

**Issue by fmalk** [db-migrate/node-db-migrate#394]
I'm running the default 0.9.x branch on Windows 10.

Currently, I have to run `db-migrate create:somescope newfile`, copy generated files to the intended `somescope` directory, and if I use `--sql-file` then I'd have to copy those SQL files to `somescope/sqls` as well, or I'd have to edit the migration to correctly reference its parent folders.

What is working for me as intended is `db-migrate up:somescope`, which does run the migrations under that folder. But since the docs refer to `create:scope`, and what I've searched at https://github.com/db-migrate/node-db-migrate/blob/3fca5102a893bde43b5de749278728b906486595/api.js#L588 seems to indicate this must be a bug.

**Comment by wzrdtales** [comment]
This is already fixed on the 0.10.x track, the support is actually completely missing on the 0.9.x track though and was introduced later on. I need to look if I'm going to backport this to 0.9.x.

**Comment by fmalk** [comment]
Got it.
It's just that `0.9.x` is still the current stable release, and `npm` installs it by default.

**Comment by wzrdtales** [comment]
Yeah that is going to change, I'm currently straightening everything to push out the 0.10.x. I have recently moved for example the seeders out of scope for 0.10.x, thus the last big item before the release is to rewrite all tests and add tests for the new programable api.
I need to rewrite all tests b/c we're currently still using vows, and vows does have some bugs which makes it impossible to actually test some things and I really mean impossible. Also vows does not seem to maintained anymore though. So the switch over is needed unfortunately.
