### ISSUE TITLE
Add plugin support

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#396]
# Foreword

There are many features out there that are being denied to be introduced into db-migrate at all. For a good reason, db-migrate wont ever support every use case and wish a user might have and it should not. db-migrate should provide a clean and stable way that it is intended to work and not an overall bloated module that is capable of everything.

But most of the time there are legitimate reason for feature requests or denied pull request, that just wont make it into the db-migrate core as of now or even never will. To solve this problem and give back the freedom to the users db-migrate will offer a plugin system, allowing to hook into different parts of the migration process and even override some parts.
# Specification

The plugin support needs a way to register plugins and load them again. We won't introduce any new file like a dbmigrate-plugin.json, but we will use the package.json directly instead and searching for the term `db-migrate-plugin-(.*)`.
Also we need different hooks and overrides which are to be defined.
A plugin itself should expose information about itself, this should include compatibility, naturally the hooks and also a description.
Additionally we should provide best practices for plugins to avoid multiple things:
- avoid plugin creators to introduce unnecessary boot up times making db-migrate slow (e.g. loading to much modules directly instead of delaying this step to the actual call of the hook)
- instructing to keep plugins as simple as possible
##

**Comment by GeeWee** [comment]
I see you've done some work here. It seems like currently plugins cannot provide their own templates. Is that correct - and is that something you would like to see added?

**Comment by wzrdtales** [comment]
@GeeWee yes and yes :)

**Comment by GeeWee** [comment]
I'm very interested in getting this to play nicely with typescript - so I might drop a PR at some point. Do you have any thoughts about how to implement this functionality?

**Comment by wzrdtales** [comment]
I actually considered a complete rewrite of how the current "templates" work: https://github.com/db-migrate/node-db-migrate/blob/master/lib/migration.js

And also about making them powerful with templates for often used migrations or more specific boilerplates. So what I had thought of already would that templates would consist out of three parts:

The main layout, the action layout and the config layout.

Main layout would include config and action. Config explains it self and action items would build the complete up and down actions and would get as input an array with the method names to call and their parameters, the rest would be up to the template generator. This way also different kinds of javascript or even other languages like elm or coffeescript should work.

**Comment by wzrdtales** [comment]
If you want to give this a shot, the stage is yours though :)

**Comment by GeeWee** [comment]
Hm, if you're planning on doing a rewrite anyways, I think I'd rather see if I can do some work on the typescript plugin in the meantime, and use something like [plop ](https://github.com/amwmedia/plop)to autogenerate the migrations for us.
Thanks for the quick response though!
