### ISSUE TITLE
Add basic plugin logic and first hooks

### ISSUE THREAD

**Issue by wzrdtales** [db-migrate/node-db-migrate#397]
# Foreword

See #396 

# Specifications

- Plugin register logic from package.json
- Hooks for
  - [x] config
  - [x] additional command
  - [x] register precompiler

**Comment by coldacid** [comment]
@wzrdtales I see there's a YAML config plugin, but have you written anything about the contract for the 'init:config:overwrite:require' hook yet? I'm looking at the possibility of pulling configuration through node-config so knowing the requirements and expectations of the hook would be quite helpful.

Given that node-config provides its own system for handling environments, I would need the hook to be provided with the requested environment.

**Comment by coldacid** [comment]
Alternatively, being able to specify a JS file that exports a function taking the environment and returning the configuration would be nice.

**Comment by wzrdtales** [comment]
@coldacid This not yet official though, no not having written any docs and thus no contracts yet.

About the js file, you can do this already. Just name it database.js or how you want to name it and let db-migrate know it should load database.js. This will actually `require` the database.js and is thus executed as javascript.

**Comment by wzrdtales** [comment]
And `init:config:overwrite:require` actually expects to get a json object back, that is in the same schema that the default database.json is though.

**Comment by wzrdtales** [comment]
So basically, you can have whatever config you want you just need to return the defined schema by db-migrate.

And this is always:

```json
{
  topLevel": "someValue",
  "default": "defaultEnv",
  "defaultEnv": {
    "someconfig": "VALUE"
  },
  "anotherEnv": {}
}
```

So the only special thing is actually that db-migrate can have many environments defined. And on the `topLevel` config is mostly just the "default" config, which specifies which is the default config, which is `dev` if default is not defined.

**Comment by coldacid** [comment]
So then I should be able to add a `database.js` to my config directory, `require('config')` in there and just emit the database info from my app config as the `default` property on an object? Nice.

This'll make things a bit easier for me when I get to work tomorrow... :D

**Comment by wzrdtales** [comment]
Not exactly sure if you got everything right, the `default` property defines the default environment to use. Your config should be on the environment itself though.

Just take a look here:

https://docs-0-10.dbmigrate.wizardtales.com/Getting%20Started/configuration

You also find the commandline option which is used to specify your database.js as config instead.

**Comment by coldacid** [comment]
Ah, okay. Just that it seems there's no way to get the environment provided on the command line from the `database.js` file I write without parsing `process.argv` myself.

**Comment by wzrdtales** [comment]
Yes this is true, there is actually nothing passed by yet, but the filename. But I will take this suggestion and pass this hook necessary information, that is relevant for config.

**Comment by coldacid** [comment]
Thanks!
