### ISSUE TITLE
How to use variables in migration sql scripts

### ISSUE THREAD

**Issue by gilly3** [db-migrate/node-db-migrate#398]
I have a migration that creates a table.  I would like to grant permissions.  The trouble is the user may differ between environments, so I need to pass a variable to the script to specify the user:

``` sql
grant select on my_new_table to :reader;
grant select, insert, update on my_new_table to :writer;
```

How can I pass variables to SQL migration scripts?
##

**Comment by wzrdtales** [comment]
Hey first of all, permissions is something not really supported by db-migrate and I'm not sure if permissions really are something that should be set via migrations, if you have use case that does make sense just let me know, may be it could be  a feature for the future and I'm open to opinions and ideas :). But  you can naturally just use `runSql`.

To solve your problem, this shouldn't be that much of a problem, your migration is actually executed javascript, this means that you actually have access to everything from node.js. Including `process.env`. One option would be thus to pass this variable in via your environment.

**Comment by gilly3** [comment]
Ok, I'll dig in and look.

But, just to address the philosophical point of whether permissions belong in migrations...

Maybe I'm using Postgres incorrectly, but when I last looked, there's nothing like permissions inheritance.  For example, the following script only applies to tables that exist at the time it is run:

```sql
grant select on all tables in schema public to app_reader;
```

So, when I add a table later, the `app_reader` user doesn't automatically have permission on that table.  A `grant` statement is required.  Maybe there's a way to get postgres to allow permissions to be inherited or automatically created when a new table is created without the explicit `grant`, but I'm not aware of any.

With that in mind, I don't see how the permissions step wouldn't be part of db-migrate.  It's a mandatory part of creating tables (unless your app is connecting as the user that created the table, which is a bad idea).

**Comment by wzrdtales** [comment]
> With that in mind, I don't see how the permissions step wouldn't be part of db-migrate. It's a mandatory part of creating tables (unless your app is connecting as the user that created the table, which is a bad idea).

Ok with that statement given, it is not part of db-migrate in this case, b/c this is pretty much directed to postgresql,  I can't mind similar problems on other DBs. So this would be a driver related topic more than for db-migrate itself. I'm not quite sure though if postgres is configureable to make your use case work. https://www.postgresql.org/docs/9.0/static/sql-grant.html
But I think that `ON DATABASE` and `ON SCHEMA` should apply also on newly created tables in the database or schema.

**Comment by gilly3** [comment]
> But I think that ON DATABASE and ON SCHEMA should apply also on newly created tables in the database or schema.

I know, right?  It totally _should!_  Sadly, `SELECT` permissions cannot be granted directly to databases or schemas.  Attempting to do so results in error.  The closest is `ALL TABLES IN SCHEMA`, which only includes the currently existing set of tables, and not tables created in the future.

I only added db-migrate to my project after my database had been built.  So, I have separate scripts outside of db-migrate for creating the database, users, and granting permissions.  It seems like it would be cleaner if I had used db-migrate from the beginning, including using it to create the database.  I've thought about going back and converting those scripts to work with db-migrate for consistency.  But, if I did so, how would I manage permissions according to db-migrate best practices?  A second script for managing permissions, to be run externally from db-migrate?  It begs the question, why not just put everything in that second script?

**Comment by wzrdtales** [comment]
As already said, this is not a topic for db-migrate itself anymore, but for the driver in this case: https://github.com/db-migrate/pg

I'm not an active user of postgres tbh, so I really would need to reproduce what you say, but it sounds like the permission system of pg is a bit broken, I guess I need to give that a more intensive look though. However, your use case is very much about pg, thus I wont consider adding permission stuff globally as part of db-migrate yet, but possibly for the pg driver.
