### ISSUE TITLE
Install fails for 0.10.0-beta.15 on windows 10

### ISSUE THREAD

**Issue by liammclennan** [db-migrate/node-db-migrate#405]
`npm install db-migrate@latest`

```
npm WARN install Couldn't install optional dependency: Unsupported
└─┬ db-migrate@0.10.0-beta.15  invalid
  ├── db-migrate-shared@1.0.2
  ├── dotenv@1.2.0
  ├── moment@2.11.2
  ├─┬ parse-database-url@0.3.0
  │ └── mongodb-uri@0.9.7
  ├── semver@5.1.1
  └─┬ tunnel-ssh@4.1.0
    ├── lodash.defaults@4.2.0
    └─┬ ssh2@0.5.0
      └─┬ ssh2-streams@0.1.6
        ├── semver@5.3.0
        └── streamsearch@0.1.2
```

**Comment by wzrdtales** [comment]
This is way too less information, please provide the complete log output and also the currently used node version + npm version.

**Comment by liammclennan** [comment]
node 5.2.0
npm 3.3.12

I've since discovered that the module is actually installed despite the error in the output. No npm log is generated.

**Comment by wzrdtales** [comment]
hm ok, well I currently have no way to reproduce this (no windows at all flying around here except for a windows 7 one, but not installed). So does everything works for you now?

**Comment by liammclennan** [comment]
Install seems ok. Failing now for a different reason https://github.com/db-migrate/node-db-migrate/issues/345

**Comment by wzrdtales** [comment]
@liammclennan Ok good to know this is solved. Look at my latest answer in #345 that should also lead you into the right direction. If not please feel free to reach out :)
