### ISSUE TITLE
Scope is not saved in the migration table when using programmatic api

### ISSUE THREAD

**Issue by igorsechyn** [db-migrate/node-db-migrate#409]
When using db-migrate programmatic api to run migrations with scope, I found that the name of the migration saved in the DB is missing the path to the scope. This is the code I would use to run "up" migrations:

```
const api = DBMigrate.getInstance(true, getMigratorOptions());
return api.up(3, "test", () => {
  console.log('done');
});
```

The names of the run migrations in the DB will not have the "test/" prefix. Running the same migration from the command line fixes the problem. After a short investigation I believe the reason could be a missing `this.internals.matching = opts` in `api.js#run`, which is being set in the `run` command, used when executing the cli. Setting it manually on the `api` object also fixes the problem, but seems to be a hack

Is there something, that I may be missing or is it really a bug?

**Comment by wzrdtales** [comment]
`api.js#run`, well this is probably not located there. If using the programable API, run is never called, if it would, you would do something wrong. Actually `run` is the non programable mode.

Also I just tested against your claims, the problem is that the API is missing the matching option. Going to fix this ASAP.

**Comment by igorsechyn** [comment]
> api.js#run, well this is probably not located there. 

Sorry I meant `up` or `down` method. I was not calling the run method.

> Actually run is the non programable mode

It is probably worthwhile updating the documentation as well, in https://db-migrate.readthedocs.io/en/latest/API/programable/ the example does suggest to use `run` method. 

> Also I just tested against your claims, the problem is that the API is missing the matching option. Going to fix this ASAP.

Awesome. Thank you:)

**Comment by wzrdtales** [comment]
Bugfix published as
+ db-migrate@0.10.0-beta.16
