### ISSUE TITLE
Question: Is execution of multiple migrations atomic?

### ISSUE THREAD

**Issue by igorsechyn** [db-migrate/node-db-migrate#410]
If i have multiple new migrations and I execute `up`, are they executed as one atomic operation? i.e. if one migration fails, will other migrations be reverted?
##

**Comment by wzrdtales** [comment]
No. This is also a bit more complicated than you think.

You have to think of many things that can actually happen and would need to reverse, this begins on the migration that fails. The biggest problem actually is that transactions of many RDBMS, e.g. MySQL, do only work for `DML` and not for `DDL`, that means that the reversal of the actual migration would need to reverse on a potentially on an incomplete migration. There might be some easy cases to reverse this actually, like dropping a table that should have been created and ignoring if it has not been created. But there are many other cases, in fact some operations are not just safely reversable without transactions. In the case of transactions that work for `DDL` this is not that much of a problem anymore. However as stated, many RDBMS do not support this.

Anyhow, to come back to your question:

No, and there is no reason for them to be. A *migration* is atomic itself. That means every single migration is surrounded by a transaction, for some DBs this would result in resetting the transaction on a failure while this migration. A set of *migrations* should however not be atomic, that does not make any sense to be a default behavior. But it could possibly introduced via an optional setting, that might be named `rollbackOnFailure: true` or something like that. 

I do see where you would see a benefit for this feature, I suspect you're looking for programmatic migrations and want to go back to the old state on failure I guess? In this case this really could be helpful though. I consider this as a feature request as of now :)

**Comment by wzrdtales** [comment]
Closing in favour of #508
