### ISSUE TITLE
Upgrade dotenv to version 2.0.0

### ISSUE THREAD

**Issue by LinusU** [db-migrate/node-db-migrate#413]
[dotenv](https://npmjs.com/packages/dotenv) has released a new major version. The breaking change is that it removes variable interpolation.

I think we should update while the latest version is still beta, so that this will make it into the next release. Thanks!

**Comment by LinusU** [comment]
This is actually already fixed in master, but not yet released. @wzrdtales would it be possible to cut a new release from master? ❤️

**Comment by wzrdtales** [comment]
@LinusU There is some work here https://github.com/db-migrate/node-db-migrate/tree/transitionHelper
that needs to be finished before releasing the latest master. The latest master does include some breaking changes though (final removal of some globals), thus I want to ship the transitionHelper before actually going ahead.

**Comment by LinusU** [comment]
Sounds fair, thanks for the quick response 👍

**Comment by wzrdtales** [comment]
Latest db-migrate was just released including this change.
