### ISSUE TITLE
Use env in migrations?

### ISSUE THREAD

**Issue by djMax** [db-migrate/node-db-migrate#416]
is it possible to use environment information (not NODE_ENV, the db-migrate env) in migration scripts? I'm wondering if I can model "seeding" as a migration that only runs in a particular env.
##

**Comment by wzrdtales** [comment]
@djMax Well, every migration gives you full access to the node js api, due to being javascript itself.

Just access `process.env` and control this yourself.

**Comment by wzrdtales** [comment]
And if you ment the db-migrate env, from reading your question again, I just noticed you probably ment this (NODE_ENV is actually also not the same as `process.env`), you can access this though. 

if you ment this information, that is not yet passed though. But you could access it over the internals: `internals.currentEnv || internals.argv.env`

**Comment by wzrdtales** [comment]
But we could very easily add this to the base driver.

**Comment by djMax** [comment]
Yes, I meant the db-migrate env. Would be nice to have access to that and the corresponding config in the migrations (perhaps in setup or in the driver/db arg of the up/down methods.
