### ISSUE TITLE
async is undefined

### ISSUE THREAD

**Issue by ibenschop** [db-migrate/node-db-migrate#418]
Updating to beta17 is causing our migrations to fail as an error is thrown > [ERROR] ReferenceError: async is not defined. We locked it back to beta16 which works. Notice that dependencies have changed. Should we nog include async in each migration?

**Comment by wzrdtales** [comment]
Hey @ibenschop 
Please read: https://github.com/db-migrate/node-db-migrate/issues/417, this will help you. I always tag breaking changes in the issues with the related tag. So you can take a look there to catch up on this kind of informations.

We deprecated some globals, `async` and `dbm`, as their names are too likely to collide and we push the library even more now into a state where it is actually really useful for progamable usage.

**Comment by wzrdtales** [comment]
You will also find in the issue linked above what exactly you would have to change. In short, if it is just async, then you need to install async locally in your project.

**Comment by wzrdtales** [comment]
Also to note:
If you're using the 0.10.x track, you also got already access to the promise style migrations. So you probably are better off using those instead of async ;), but that is naturally your decision.

If any other question, don't hesitate to ask.

**Comment by ibenschop** [comment]
Hi Tobias,

Thanks for your swift reply and direction. Much appreciated and keep up the
great work!

**Comment by wzrdtales** [comment]
No problem, closing as resolved. Feel free to open a new issue if you run into any.
