### ISSUE TITLE
Allow to pass configuration when loading plugins

### ISSUE THREAD

**Issue by RemyJeancolas** [db-migrate/node-db-migrate#419]
It would be a great idea to allow passing configuration when loading a plugin.
For example, for [plugin-typescript](https://github.com/db-migrate/plugin-typescript), internally we use [ts-node](https://github.com/TypeStrong/ts-node#programmatic-usage), and ts-node `register` method accepts an options object that we can't pass for now.
Updating the `loadPlugin` method to accept optional parameter(s) (for example an `options` object) could solve the problem.
##

**Comment by wzrdtales** [comment]
@RemyJeancolas loadPlugin won't get any optional parameters. It is really just loading the plugin, this is only in place to have an easy way to delay load modules within a plugin, which in turn was part of the design to have a plugin system that is not slowing everything down, but the actual hook that is affected. However, a Hook might get added some parameters or options added, So just go ahead and suggest what would be useful to add to a specific hook, in your case `migrator:migration:hook:require` would be interesting.

But generally I have already thought about always passing through configurable options to any plugin, namespaced by their name. But yet net thought about if it would make sense to add those to the `.rc` configs that are being introduced soon or to the DB config, or even both.
