### ISSUE TITLE
dbmigrate.registerAPIHook is not a function

### ISSUE THREAD

**Issue by WebStyle** [db-migrate/node-db-migrate#425]
on Node.js v6.6.0.
Error:
```bash
$ db-migrate up
[ERROR] TypeError: dbmigrate.registerAPIHook is not a function
    at /usr/lib/node_modules/db-migrate/bin/db-migrate:36:13
    at /usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:44:21
    at ondir (/usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:187:31)
    at onex (/usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:93:22)
    at /usr/lib/node_modules/db-migrate/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by wzrdtales** [comment]
Hey @WebStyle,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:

- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by wzrdtales** [comment]
Just saw that local resolving ends up in an issue, as the hook might not be there yet.

Please post the next time all needed information, as we have a hard time to figure out which problem you're facing with that amount of information provided.

**Comment by WebStyle** [comment]
Thank you!!!
