### ISSUE TITLE
SQLite defaultValue checking shouldn't be a boolean check

### ISSUE THREAD

**Issue by rikvdk** [db-migrate/node-db-migrate#430]
The SQLite driver uses a boolean check to see if the defaultValue was specified. Values considered false in javascript (eg 0) can currently not be used.

Drivers are currently using 3 different checks:

- [sqlite/index.js#L89]( https://github.com/db-migrate/sqlite/blob/035eb1cc0a721613b10110df23a98d8fa99eeba9/index.js#L89)
- [mysql/index.js#L137](https://github.com/db-migrate/mysql/blob/04b54f0bbc04d2064db3a614bfb2ae01fbecc8b4/index.js#L137)
- [pg/index.js#287](https://github.com/db-migrate/pg/blob/d032ea5f0bf858a2a44444b94f7b32ce06d5e50c/index.js#L287)

**Comment by wzrdtales** [comment]
@rikvdk Hey,

thanks for reporting this! This is, as you identified not wanted. Actually the correct version is the mysql one, I will push out a fix for this in a few hours as soon as I travel in.
