### ISSUE TITLE
Where can I find the documentation how database.json should be structured?

### ISSUE THREAD

**Issue by Paxa** [db-migrate/node-db-migrate#431]
Where to find documentation about how `database.json` should be like?

**Comment by wzrdtales** [comment]
@Paxa Here you go :)
https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/

If you have any other questions, feel free to reach out.

**Comment by wzrdtales** [comment]
I close this issue at this point, as the question is considered being answered. If you are missing anything else feel free to open another issue.

**Comment by Paxa** [comment]
Ok, thanks
