### ISSUE TITLE
TypeError: destination.substring is not a function

### ISSUE THREAD

**Issue by WebStyle** [db-migrate/node-db-migrate#432]
When I down migration:
```javascript
exports.up = function (db, callback) {
  db.runSql('ALTER TABLE tableName ADD CONSTRAINT keyName UNIQUE (key1, key2)', function (err) {
    if (err) return callback(err);
    callback();
  });
};

exports.down = function (db, callback) {
  db.runSql('ALTER TABLE tableName DROP CONSTRAINT keyName', function (err) {
    if (err) return callback(err);
    callback();
  });
};
```
Error:
```bash
[INFO] Defaulting to running 1 down migration.
[ERROR] TypeError: destination.substring is not a function
```

**Comment by wzrdtales** [comment]
Hey @WebStyle,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:

- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by WebStyle** [comment]
Thank you, i'm upgraded db-migrate. Its works!!!
