### ISSUE TITLE
DOWN result in error thrown [ERROR] TypeError: destination.substring is not a function

### ISSUE THREAD

**Issue by ibenschop** [db-migrate/node-db-migrate#433]
We are running db-migrate-0.10.0-beta.16. When running a down migration we get an error thrown: `[ERROR] TypeError: destination.substring is not a function
    at isIncludedInDown (/Users/ian/Code/resolver-dev-all/resolver-object-service/node_modules/db-migrate-shared/util.js:18:37)`

Debugging and Stack tracing results in destination having a number value which is passed down as count but it's expecting a string.

**Comment by wzrdtales** [comment]
Probably related to an issue from this morning #432 

Please try updating to the latest version and report back if this does not fix the problem for you. If it does please close this issue.

**Comment by ibenschop** [comment]
We opted to use beta12 since upgrading t beta17 or up will have more impact on our implementation. Thanks

**Comment by wzrdtales** [comment]
You mean from beta16 on?
I think you refer to #417, if so, this is fine but you should be able to go to anything below beta16 until you're ready to upgrade though, you may need to invest a bit of time to upgrade if you are still using a very old migration template.

**Comment by ibenschop** [comment]
Yes from beta16 to beta12. Yes we will upgrade in the future for sure. Thanks
