### ISSUE TITLE
Using prepared statements in runSql fails

### ISSUE THREAD

**Issue by subatomicglue** [db-migrate/node-db-migrate#438]
Maybe the problem is there isn't an example in the [documentation for runSql](https://db-migrate.readthedocs.io/en/latest/API/SQL/), so maybe I just dont know how to call it using the ? replacement parameters mentioned.

Incidentally, [the docs](https://db-migrate.readthedocs.io/en/latest/API/SQL/) seems to be missing a comma for both runSql() and all():  i.e. runSql(sql, [params,] callback)  and    all(sql, [params,] callback)  after the params]

I am trying to add a user and grant permissions, and since I dont want to do this for every db OUTSIDE of db-migrate (I just want it to happen magically), I'm putting it in db-migrate.  (but whether or not that belongs in db-migrate is not the issue I need to discuss here).

Trying to use ? replacement params, seems to give an error:

The Error:
`[ERROR] Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('readonly') IDENTIFIED BY ('specialpassword')' at line 1`

The Migration script:

``` javascript
'use strict';

require('dotenv').config({silent: true, path: '.env'});
var async = require('async');
var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db, callback) {
  async.series([
    db.runSql.bind(db, "CREATE USER '?' IDENTIFIED BY '?'", [process.env["MYSQL_USERNAME_READONLY"], process.env["MYSQL_PASSWORD_READONLY"]], callback),
    db.runSql.bind(db, "GRANT SELECT ON * . * TO '?'", [process.env["MYSQL_USERNAME_READONLY"]], callback)
  ], callback);
};

exports.down = function(db, callback) {
  async.series([
    db.runSql.bind(db, "DROP USER '?'", [process.env["MYSQL_USERNAME_READONLY"]], callback)
  ], callback);
};

exports._meta = {
  "version": 4
};
```

Dry Run:

```
db-migrate --dry-run up
[INFO] dry run
CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL);
SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC;
SET AUTOCOMMIT=0;;
START TRANSACTION;;
CREATE USER '?' IDENTIFIED BY '?' [ [ 'readonly', 'specialpassword' ], [Function: r] ]
GRANT SELECT ON * . * TO '?' [ [ 'readonly' ], [Function: r] ]
INSERT INTO `migrations` (`name`, `run_on`) VALUES (?, ?) [ [ '/20161027150636-readonlyuser', '2016-10-27 11:07:05' ] ]
[INFO] Processed migration 20161027150636-readonlyuser
COMMIT;;
[INFO] Done
```

And in mysql:

```
mysql> CREATE USER '?' IDENTIFIED BY '?' [ [ 'readonly', 'specialpassword' ] ];
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[ [ 'readonly', 'specialpassword' ] ]' at line 1
```
##

**Comment by subatomicglue** [comment]
To fix this, I simply inlined the variables, but I'd still like to know how to make the ? params work.

```javascript
exports.up = function(db, callback) {
  async.series([
    db.runSql.bind(db, "CREATE USER '"+process.env["MYSQL_USERNAME_READONLY"]+"' IDENTIFIED BY '"+process.env["MYSQL_PASSWORD_READONLY"]+"'", callback),
    db.runSql.bind(db, "GRANT SELECT ON * . * TO '"+process.env["MYSQL_USERNAME_READONLY"]+"'", callback)
  ], callback);
};

exports.down = function(db, callback) {
  async.series([
    db.runSql.bind(db, "DROP USER '"+process.env["MYSQL_USERNAME_READONLY"]+"'", callback)
  ], callback);
};
```

**Comment by wzrdtales** [comment]
You're just using `async` completely wrong. You can't do this like you do, go their docs and read them again, there is no callback that you should pass in, you should omit it! :)

Anyway: Using async is not recommended anymore. You have promises available to you, just turn your given example into this. which is easier and should work as well:

```javascript
'use strict';
var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  
    return db.runSql("CREATE USER '?' IDENTIFIED BY '?'", [process.env["MYSQL_USERNAME_READONLY"], process.env["MYSQL_PASSWORD_READONLY"]])
    .then( () => db.runSql("GRANT SELECT ON * . * TO '?'", [process.env["MYSQL_USERNAME_READONLY"]]) );
};

exports.down = function(db) {

  return db.runSql("DROP USER '?'", [process.env["MYSQL_USERNAME_READONLY"]]);
};

exports._meta = {
  "version": 4
};
```

And why do you require `dotenv`? db-migrate already does this, and you don't specify a new .env file. so this is not really needed.

**Comment by wzrdtales** [comment]
@subatomicglue Did you managed to get it work now?

I was short on time yesterday, so I left out the explanation. So to explain why your example wont work is that you supply an invalid amount of parameters.

So you basically called:

    db.runSql('query ?', [param1], callback, function() {});

But this wont work, the API expects that you pass the callback as last parameter, but as you use `async` and you still did not omitted the callback, there was a duplicate callback passed to runSql. I guess I will look to have this method to check if there is an invalid amount of parameters being passed, to avoid such confusion.
So you basically need to leave out the callback param, as `async` always passes its own callback into the function, that is actually how `async` works. But as suggested above: I highly suggest to switch over to promises, they work out of the box, are easier to read and to write and you do not need any additional library for doing this.

**Comment by wzrdtales** [comment]
I haven't heard anything from you yet again, can this issue be closed?

**Comment by subatomicglue** [comment]
Yes!
>
>

-- 
Sent from Gmail Mobile

**Comment by subatomicglue** [comment]
Thank you so much for the thoughts/suggestions and turning my async code into promises.  Appreciated.   Please close

**Comment by wzrdtales** [comment]
No problem. Do not hesitate to reach out if you should have any other question

**Comment by cullylarson** [comment]
I'm having the same problem. Question mark placeholders don't seem to be replaced. I'm using MySQL.

Here's my code:

```
db.runSql('INSERT INTO groups (id, isActive, isLocked, name, description, created) VALUES(?, TRUE, TRUE, ?, ?, NOW())', [id, name, description])
```

These are the values of id, name, description:

```
{
  id: '4dfad450-7c17-11e9-8808-0242ac170002',
  name: 'Users',
  description: 'Test.'
}
```

And here's the error I'm getting:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (id, isActive, isLocked, name, description, created) VALUES(?, TRUE, TRUE'
```

It looks like the raw SQL is begin executed, without question marks being replaced.

**Comment by wzrdtales** [comment]
If you use **named** parameters, then you also need to pass **named** parameters.

See this

https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md

and 

https://github.com/sidorares/node-mysql2/blob/58c1056edd21ad42e2e755959b75f76b502e3f72/documentation/Extras.md


If you need mentorship to learn how db-migrate works and also how the corresponding drivers underneath db-migrates own technology work, I gladly refer you to git-start:

https://git-start.com/help-request/create/db-migrate%2Fnode-db-migrate

**Comment by wzrdtales** [comment]
Another note to your provided code samples.

**Never** use callbacks. They are deprecated for use and you should use only promise instead. All methods in db-migrate that are intended to be used by the user, so all functions that do not start with `_` and `all`, return a promise. So does runSql, so there is no need to pass a callback to it. Just use the promise and if wanted async/await.

To the problem again: This is how it is supposed to work. The question marks are never replaced and this is correct. This is called a prepared statement, which has nothing to do with db-migrate but is very basic database knowledge, for which I kindly ask you to read the documentation of the mysql driver and mysql itself about prepared statements or as linked ask for a mentoring session.

And as I realized while reading my answer again:

I don't mean to be rude, but I have very limited time, that I can invest for **free** into open source, and I am glad to answer everything related to the functionality of db-migrate, so don't feel scared to ask db-migrate related things, but this one is not related to db-migrate but the driver beneath. And another note: Please do not post into closed issues. Open a new one if you really think you're stumbling over one and refer to other closed issues if needed.

**Comment by cullylarson** [comment]
I appreciate the reply.

> If you use named parameters, then you also need to pass named parameters.

I'm not using named parameters.

> See this
>
> https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md

The [db-migrate/mysql](https://github.com/db-migrate/mysql) driver does not use `mysql2` and so does not support prepared statements.

> To the problem again: This is how it is supposed to work. The question marks are never replaced and this is correct. This is called a prepared statement...

`runSql` is trying to execute the SQL with the question marks still there. It's not creating a prepared statement.

The db-migrate documentation for `runSql` says:

> Arguments
> - sql - the SQL query string, possibly with ? replacement parameters
> - params - zero or more ? replacement parameters

That seems to state that `sql` can have question marks for replacement parameters and that they will be replaced with values from `params`. All the examples I've seen of `runSql` seem to work in this way.

> ...this one is not related to db-migrate but the driver beneath.

Thanks. I'll post it as an issue on [db-migrate/mysql](https://github.com/db-migrate/mysql).

**Comment by wzrdtales** [comment]
> The db-migrate/mysql driver does not use mysql2 and so does not support prepared statements.

It does...

https://github.com/db-migrate/mysql/blob/b90fdec37a73f4bbd75264ebc00bec2890812e49/package.json#L32

**Comment by wzrdtales** [comment]
> The db-migrate/mysql driver does not use mysql2 and so does not support prepared statements.

Nvm, it does use mysql:v2

https://github.com/db-migrate/mysql/blob/b90fdec37a73f4bbd75264ebc00bec2890812e49/package.json#L32

but this is nothing that matters much. https://github.com/mysqljs/mysql#preparing-queries Is the same from functionality standpoint.

> That seems to state that sql can have question marks for replacement parameters and that they will be replaced with values from params. All the examples I've seen of runSql seem to work in this way.

It is a replacement character. But the ``DATABASE`` replace it, in a safe manner. That is the whole point of prepared statements and avoiding SQLis by that (at least most of the time).

**Comment by wzrdtales** [comment]
So in short. `db-migrate` does not do anything with your query and replaces anything. This is completely in the hands of the driver and the `database`. Either being the driver using the escaping methods of the `database` or the `database driver` or submitting prepared statements by default. Latter is not so different from using the escaping methods of the db directly, b/c that is what they do with the prep statement.

**Comment by wzrdtales** [comment]
And as a last node: `db-migrate` always uses the prepared statement like queries (so "replacement characters"). It is on the driver beneath what it does with that. Some use the escaping capabilities directly. Others automatically use prep statements by default.

What you do with `runSql` is completely on to you though. And it is just a direct pass through to the default query method of the concerned driver.

**Comment by PRR24** [comment]
> I'm having the same problem. Question mark placeholders don't seem to be replaced. I'm using
> If anyone finds this in the future and wants a quick workaround, use this function instead of db.runSql:
> 
> ```js
> const runSql = (db, query, params) => new Promise((resolve, reject) => {
>     db.runSql(query, params, (err, data) => {
>         if(err) reject(err)
>         else resolve(data)
>     })
> })
> ```
More straight forward solution would be to add null as last parameter
```js
db.runSql('INSERT INTO groups (id, isActive, isLocked, name, description, created) VALUES(?, TRUE, TRUE, ?, ?, NOW())', [id, name, description], null)
```
