### ISSUE TITLE
[ERROR] TypeError: Object 1 has no method 'substring'

### ISSUE THREAD

**Issue by blueshirts** [db-migrate/node-db-migrate#440]
I am getting an error when doing a migrate down.  

In the recent version of seeder.js it looks to call utils.filterDown with 2 parameters.

https://github.com/db-migrate/node-db-migrate/blob/v0.10.0-beta.20/lib/seeder.js#L306

In the package.json for db-migrate it references db-migrate-shared of version 1.1.2.

    "db-migrate-shared": "^1.1.2”,

Prior versions reference ^1.0.2 though because of the caret I am getting upgraded to version 1.1.2.

    "db-migrate-shared": "^1.0.2",

For example:

    db-migrate@0.10.0-beta.16 node_modules/db-migrate
    ├── db-migrate-shared@1.1.2

So far as I can tell the db-migrate-shared.utils.filterDown function seems to take 3 parameters.  For example:

https://github.com/db-migrate/shared/blob/v1.1.2/util.js#L54

You have to go back to version 1.0.2 to find a version of filterDown that takes 2 parameters.

https://github.com/db-migrate/shared/blob/v1.0.2/util.js#L125

This seems to be causing me the following error when migrating down.

    [ERROR] TypeError: Object 1 has no method 'substring'
      at isIncludedInDown (/opt/web/apps/uac/node_modules/db-migrate/node_modules/db-migrate-shared/util.js:18:37)
      at /opt/web/apps/uac/node_modules/db-migrate/node_modules/db-migrate-shared/util.js:58:12

I could be mistaken with some of the details though I was able to work around this issue by deleting my db-migrate package and add a peer dependency to the specific shared version.

    "peerDependencies": {
        "db-migrate-shared": "1.0.2"
      },

**Comment by wzrdtales** [comment]
Which db-migrate version did you used?

**Comment by wzrdtales** [comment]
If beta.16 please update to at least beta.17 where this problem should be already fixed

**Comment by blueshirts** [comment]
I tried Beta 20.  I could be missing something but all the new versions of seeder seem to send 3 parameters into utils.filterDown.  filterDown in all newer versions seems to take 3 parameters.  You may not see the issue unless you delete and re-download node_modules.  I am picking up db-migrate-shared@1.1.2 because of the following line in package.json.

    "db-migrate-shared": "^1.0.2",

**Comment by wzrdtales** [comment]
@blueshirts That is b/c seeder is not marked as stable and is being postponed. Sorry for the confusion, you wont be able to use it as of now. I still need to get it out of the CLI, I am currently working on the docs to get them in a state afterwards we going to release the 0.10.x version. Seeders are about to come in any of the future version after 0.10.x though.

**Comment by blueshirts** [comment]
Looks like the same call is also in migrator.js so I probably have the wrong reference that was causing the problem.

    $ grep -R filterDown *
    lib/migrator.js:      var toRun = dbmUtil.filterDown(completedMigrations, count);
    lib/seeder.js:      var toRun = dbmUtil.filterDown(completedSeeds, count);

Looks like this reference is updated in beta 19.

https://github.com/db-migrate/node-db-migrate/blob/v0.10.0-beta.19/lib/migrator.js

**Comment by wzrdtales** [comment]
Ah yes you're right:

https://github.com/db-migrate/node-db-migrate/compare/v0.10.0-beta.18...v0.10.0-beta.19#diff-ab64bdc9e95eb3722ad8f302f6b92250R206
