### ISSUE TITLE
Migration fail to write to migration table

### ISSUE THREAD

**Issue by Kilgaloon** [db-migrate/node-db-migrate#442]
Like title says, everything goes fine, table is created etc etc, but migration table doesn't get populated. When i do db-migrate up it just hangs, nothing gets returned.

**Comment by wzrdtales** [comment]
Hey @Kilgaloon,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:

- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by Kilgaloon** [comment]
Okay, here it comes.

Node version: 7.0.0
Npm version: 3.10.8
Db-migrate version: 0.10.0-beta.20
db-migrate-mysql: 1.1.10

Verbose output:

[INFO] Using dev settings: { driver: 'mysql',
  user: '*******',
  password: '******',
  host: '********',
  database: '********' }
[INFO] require: db-migrate-mysql
[INFO] connecting
[INFO] connected
[INFO] creating table: migrations
[SQL] CREATE TABLE IF NOT EXISTS `migrations` (`id` INTEGER  PRIMARY KEY AUTO_INCREMENT NOT NULL, `name` VARCHAR (255) NOT NULL, `run_on` DATETIME  NOT NULL)
[INFO] migration table created
[INFO] loading migrations from dir /var/www/html/syncplay/migrations
[INFO] loading migrations from database
[SQL] SELECT * FROM `migrations` ORDER BY run_on DESC, name DESC
[INFO] preparing to run up migration: 20161109100117-port-for-party
[SQL] SET AUTOCOMMIT=0;
[SQL] START TRANSACTION;
[SQL] ALTER TABLE `parties` ADD COLUMN `info_port` INTEGER  DEFAULT 0

This is point where it just stops and hangs

**Comment by wzrdtales** [comment]
Please don't cut the result of the verbose run. If you hide all information that are giving any clue about your actual problem, then we can't help you.

**Comment by Kilgaloon** [comment]
Point is i didn't cut out anything, thats where verbose output stops, and hangs, it will never move from that point.

**Comment by wzrdtales** [comment]
Ok can you please provide me a migration where this happens

**Comment by Kilgaloon** [comment]
Ok so, i noticed whats going on here, migrations that hangs when you try to migrate are the ones where exports.up doens't return null. when i added null everything passed just fine.

**Comment by wzrdtales** [comment]
ah yes ok, I already assumed that you had something like that in your migration. `return null` is equal to `return Promise.resolve()` and you need to return either a promise or null otherwise it is waiting forever. The same goes naturally if you would use callbacks.

As this is solved I close this issue now. If you should have any other problem, feel free to reach out.
