### ISSUE TITLE
How to access config in migration

### ISSUE THREAD

**Issue by staff0rd** [db-migrate/node-db-migrate#445]
How can I access the config in a migration?  For example - what driver is currently being used?

**Comment by wzrdtales** [comment]
@staff0rd 

Fist a question: Why do you want this? Just from the point that you raise, I want the config in the migrations, I would say, this is never going to be supported officially. So I need the usecase from you, what exactly you need and why.

If your need is simply knowing which driver is used, there is a function named `checkDBMS`, which currently has no function, but is defined to check if the string you input match the currently used driver. This would as soon as completely implemented be a solution for your example.

**Comment by staff0rd** [comment]
Which driver is being used is pretty much it - basically so I can write database specific migration code.  For example, for my dev/local environment I'm using sqlite, however for test and production i'd use postgres.

I'd expect to be able to write migrations that can sync schema to either of those db from the same set of migrations, so I'd need to (at times) check the driver to call vendor-specific functions.  (For example now(), CURRENT_TIMESTAMP() etc).

**Comment by wzrdtales** [comment]
Yes makes sense. This was also the intention behind checkdbms .  I will have a look to add the missing bit and put that into the pipeline.
