### ISSUE TITLE
How to update a mongodb collection

### ISSUE THREAD

**Issue by lampe** [db-migrate/node-db-migrate#447]
I have the following code:
```js
exports.up = function(db, callback) {
  db.createCollection('table', function() {
    db.insert('table', {
      name: 'micha'
    }, function() {
      db.update('table', {
        name: 'cedric',
        surname: 'camelot'
      }, {
        name: 'micha'
      }, callback);
    });
  });
};
```

Baiscly what i want is to update specific fields.

What iam getting is:
```bash
[ERROR] TypeError: db.update is not a function
```

**Comment by BorntraegerMarc** [comment]
@wzrdtales Can you give an answer to this question? As I think a lot of people have this question

**Comment by wzrdtales** [comment]
@BorntraegerMarc Thanks for hitting me up again, things can get lost quite quickly. I often read issues but have no time to immediately answer them. Later they do not pop up again in the notifications though. It is never bad to just ping me up once again, to make me notice :)

@lampe 
There is a theoretical implementation already there though. Although it is not available on the public api:
https://github.com/db-migrate/mongodb/blob/master/index.js#L432

You could however currently run `_run` directly with 'update' as first argument, see
https://github.com/db-migrate/mongodb/blob/master/index.js#L260

**Comment by xfg** [comment]
@wzrdtales why not simply pass mongodb driver as argument to up/down functions ? In the moment I should use `_run` that get access to most [api of mongodb driver](http://mongodb.github.io/node-mongodb-native/2.2/api/). This is very strange.

**Comment by BorntraegerMarc** [comment]
I would also be grateful for a mongodb driver that we could use at our own free will. anyhow a short question. Running this:
```
return db._run('update', 'rooms', {
        query: {},
        update: {$set: {slug: 'emma2'}},
        options: {}
    });
```
does not update every entry in the `rooms` collection. Do you know why @wzrdtales ?

**Comment by wzrdtales** [comment]
Hey hey,

as announced in some of my last answers, still busy with the conference, next week everything will return to normal for me though.

@BorntraegerMarc Maybe the translated call does not work out: https://github.com/db-migrate/mongodb/blob/master/index.js#L343

This translates to `collection('rooms').update({}, {$set: {slug: 'emma2'}, {}, callbackFunction);`
