### ISSUE TITLE
Triggering a migration form code

### ISSUE THREAD

**Issue by jonathan-rodan** [db-migrate/node-db-migrate#448]
To make it easier for new developers joining the company, I want to run the migrations on the startup of a service (only for the development environment).

Would it be possible to export a usable interface that can be called form code?

I would like to be able to do something like:

```
  DBMigrate = require( 'node-db-migrate' );
  dbmigrate = DBMigrate.getInstance();
  dbmigrate.run();
```

Some functions might need to be exposed to allow the code to specify the `cwd`.

**Comment by wzrdtales** [comment]
@jonathan-rodan 
Hey first of all, sry for answering that late, I was and still am moving to a new accomodation and therefore nearly no free minute.

This is already possible, you're asking for a programable access right? If so:

https://db-migrate.readthedocs.io/en/latest/API/programable/#handle-the-oncomplete-callback-outside-of-db-migrate

And for the cwd you can pass a configuration object into `getInstance` not sure if there is already a doc, I'm coming back to you later again.
