### ISSUE TITLE
Document a contract for accessing db-migrate as a module

### ISSUE THREAD

**Issue by jpravetz** [db-migrate/node-db-migrate#45]
This is not so much an issue as a request.
I'm including db-migrate as a module require() and writing my own equivalent of bin/db-migrate. This is because I need to manage and migrate a dynamically generated list of databases (e.g. one per customer). 
The API is documents for use as a command line application, but  not for use as a module, and I just want to make a request that an effort be made to stabilize this module API.
Thanks.
##

**Comment by wzrdtales** [comment]
refers to #214
