### ISSUE TITLE
RC configuration is ignored

### ISSUE THREAD

**Issue by maxsummers** [db-migrate/node-db-migrate#451]
Hello!

I've created the `.db-migraterc` file at root of my project with the following content:

```json
{
  "config": "./config/base/migrations.json",
  "migrationsDir": "./src/application/migrations"
}
```

But, when I run `db-migrate create test` it tell me that it can't find the configuration file in: `database.json`.

How do I specify path to config file and migrations directory in RC-file?

Thanks.

**Comment by wzrdtales** [comment]
@maxsummers This is not yet released, the latest docs really are the latest docs though and include stuff not yet there :). There is also a 0.10.x and 0.9.x doc tree where only released stuff is included.

I will have some more time the next days (was quite busy the last weeks moving to a new accomodation though) and will push out a new version including the RC configs.

**Comment by Tomino2112** [comment]
Hi @wzrdtales any update on this?

**Comment by Amos47** [comment]
@Tomino2112 and @maxsummers 

I posted a possible solution for this, but not sure if either of you have any ideas for testing it, or could tell me if I'm on a track for your use cases.

**Comment by nmccready** [comment]
Why was this closed I appear to be having the same problem.
