### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by foucdeg** [db-migrate/node-db-migrate#453]
Hello,
I use db-migrate on my project, to create a test database from scratch as part of each build on TravisCI.
db-migrate outputs every SQL query it runs, which produces around 80K lines of log in my build, and that makes it difficult for me to scroll down my build logs looking for errors.

Can db-migrate have a "silent" mode where it only outputs one line per migration?

**Comment by wzrdtales** [comment]
Hey @foucdeg 

Yes there is a silent mode, but db-migrate is really silent in this and don't say anything. Your described behavior is the verbose behavior, normally db-migrate does not do what you tell.

Can you give us a bit more insight about what you're executing on travis?

**Comment by pomerantsev** [comment]
Hi @wzrdtales!
I found this thread because I'm having the same issue.
I created a minimal reproduction: https://github.com/pomerantsev/db-migrate-test
If you have time to take a look, please let me know if this might be easily fixed.

On a separate note, the [docs](https://db-migrate.readthedocs.io/en/latest/API/programable/) say that the method to silence the logs is called `silent`, [but it's actually `silence`](https://github.com/db-migrate/node-db-migrate/blob/85bde6de71a609449ffb8937eba6917b34582fa7/api.js#L380)

**Comment by fmalk** [comment]
I can vow for the same issue, in another scenario: using `db-migrate` in tests cannot be silenced

```
describe('Some test', function() {
    beforeEach(function() {
        var migrations = dbmigrate.getInstance(true);
        migrations.silence(true);
        return migrations
            .reset()
            .then(function() {
                return migrations.up();
            });
    });

    // tests...
});
```
Every test on that suite will echo the entire migration on console.

**Comment by fmalk** [comment]
Fixed: actually, in my case, console output was due to boilerplate in SQL migrations:

```
exports.up = function(db) {
  var filePath = path.join(__dirname, 'sqls', '20170208214337-migration-up.sql');
  return new Promise( function( resolve, reject ) {
    fs.readFile(filePath, {encoding: 'utf-8'}, function(err,data){
      if (err) return reject(err);
      console.log('received data: ' + data); // the culprit

      resolve(data);
    });
  })
  .then(function(data) {
    return db.runSql(data);
  });
};
```

Taking that out cleared my testing logs.

**Comment by wzrdtales** [comment]
@pomerantsev @fmalk Ah that is what we are talking about, yes that makes things clear

https://github.com/pomerantsev/db-migrate-test/blob/master/migrations/20170205234615-first.js#L26

We can replace this in the template with log.verbose though, this would solve this.
