### ISSUE TITLE
db-migrate-postgress no longer available

### ISSUE THREAD

**Issue by abarcenas29** [db-migrate/node-db-migrate#456]
When I run `db-migrate up` I get this error.

>$ db-migrate up
[ERROR] No such driver found, please try to install it via npm install db-migrate-postgress or npm install -g db-migrate-postgress`

When I try to install it I get this.

> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/db-migrate-postgress npm ERR! 404
> npm ERR! 404  'db-migrate-postgress' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git
> 

According to the doc it supports `pg` package and installed that on both the project and globally. Still it doesn't work.

I am using the **DATABASE_URL** entry in the *env* file.

**Comment by abarcenas29** [comment]
Solved.

I am using `postgers://` instead of `pg://`

**Comment by wzrdtales** [comment]
@abarcenas29 Actually also just being an typo :)

`postgres´ would be correct while you've written `postgress`. It is not a problem to use either `postgres`, `pg` or `postgresql` as those are catched over here:
https://github.com/db-migrate/node-db-migrate/blob/master/lib/driver/index.js#L48-L56
