### ISSUE TITLE
How to create a column with a function as its default value?

### ISSUE THREAD

**Issue by worldspawn** [db-migrate/node-db-migrate#457]
Hi,

`id: { type: 'uuid', primaryKey: true, defaultValue: 'uuid_generate_v4()' },`

That column spec fails with
```
[WARN] Using unknown data type UUID
[ERROR] error: invalid input syntax for uuid: "uuid_generate_v4()"
    at Connection.parseE (C:\Users\critc\AppData\Roaming\npm\node_modules\db-migrate-pg\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (C:\Users\critc\AppData\Roaming\npm\node_modules\db-migrate-pg\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (C:\Users\critc\AppData\Roaming\npm\node_modules\db-migrate-pg\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

Is there some special notation to stop it being treated as a literal?

**Comment by wzrdtales** [comment]
This came up just recently, with an attempt for a solution, that did not worked out completely. See the last comment here where @yonahforst posted a solution for the problem, while there is no intended solutionfor this.

https://github.com/db-migrate/sqlite/pull/4#issuecomment-270622199

**Comment by worldspawn** [comment]
In my case that work-around works just fine. Thanks. Any reason for it not to be the _official_ way to do it?

**Comment by wzrdtales** [comment]
@worldspawn It is a bit hacky, and it would be better to have a way that is more intuitive, that is the only reaon why it is not the *official* way.

**Comment by worldspawn** [comment]
Cool thanks.

**Comment by ezy** [comment]
For anyone else looking the correct way to do this is:

```javascript
exports.up = (pgm) => { 
  pgm.createExtension('uuid-ossp'); // add uuid support to pg
  pgm.createTable('things', {
    id: { type: 'uuid', primaryKey: true, default: pgm.func('uuid_generate_v4()') },
  });
};
```

**Comment by Haharin** [comment]
> For anyone else looking the correct way to do this is:
> 
> ```js
> exports.up = (pgm) => { 
>   pgm.createExtension('uuid-ossp'); // add uuid support to pg
>   pgm.createTable('things', {
>     id: { type: 'uuid', primaryKey: true, default: pgm.func('uuid_generate_v4()') },
>   });
> };
> ```

 pgm.createExtension is not a function

can you help with this?

**Comment by webjay** [comment]
Here's what works in May of 2021:

```
const tableName = 'my_log';

exports.up = async function(db) {
  await db.runSql('CREATE EXTENSION IF NOT EXISTS "pgcrypto";');
  return db.createTable(tableName, {
    id: { type: 'uuid', primaryKey: true, defaultValue: new String('gen_random_uuid()') },
    payload: { type: 'text' },
    created_at: { type: 'timestamp', notNull: true, defaultValue: new String('now()') },
  });
};

```

You'll see _[WARN] Using unknown data type UUID_ but it works.
