### ISSUE TITLE
Error when running node_modules/db-migrate/bin/db-migrate seed

### ISSUE THREAD

**Issue by zoharsherman** [db-migrate/node-db-migrate#460]
when trying to use seed i am getting the below error:
$ node_modules/db-migrate/bin/db-migrate seed
[ERROR] TypeError: Cannot read property 'filesRegEx' of undefined
    at .../node_modules/db-migrate/lib/seed.js:123:30
    at Array.filter (native)
    at .../node_modules/db-migrate/lib/seed.js:121:19
    at FSReqWrap.oncomplete (fs.js:112:15)

**Comment by oroce** [comment]
I resolved this issue in my fork: https://github.com/db-migrate/node-db-migrate/compare/master...purposeindustries:fix/static-seed-execution

@wzrdtales what's the plan with seeders, shall I open a pull request for this or do you plan to redo it completely?
