### ISSUE TITLE
Master build fails. 

### ISSUE THREAD

**Issue by Kumjami** [db-migrate/node-db-migrate#463]
Hi!

I'm trying to use `db-migrate` in heroku, so I'm facing the same problems as discussed [here](https://github.com/db-migrate/pg/issues/8).

I thought about fixing it by myself and submit a PR following [guidelines for contributing](https://github.com/db-migrate/node-db-migrate/blob/master/CONTRIBUTING.md)

It says: 

> Run the tests. Pull requests without tests are much less likely to be merged, and it's great to know you're starting with a clean slate: npm test. Be sure to check the README for setting up your test databases first.

But the true is that test are broken on master [for 3 months](https://travis-ci.org/db-migrate/node-db-migrate/builds) now: 

![image](https://cloud.githubusercontent.com/assets/8338963/23133149/67a3a17e-f790-11e6-86d9-be377f3caad3.png)

My goal is to advance on [this issue](https://github.com/db-migrate/node-db-migrate/issues/349).
@wzrdtales you said you would probably work on that in a couple of weeks, so you may have started to work on that, is that already in progress?

Thanks

**Comment by wzrdtales** [comment]
@Kumjami Also sorry here for the late response, you're more than welcome to help out though :) And yet I haven't touched the issue again.

About the tests, if they fail b/c your changes broke something, you will need to fix that, but not if it does not, so this is not a big problem.
