### ISSUE TITLE
Question: concurrency

### ISSUE THREAD

**Issue by germanSancho** [db-migrate/node-db-migrate#464]
Hello,

First of all, thanks for this great library!

I have a concern about how concurrency is handled when executing migrations. What happens if several people (or several scripts) try to run a `db-migrate up` at the same time against the same database? Is there any locking mechanism?

This is my usecase: I want to add `db-migrate up` as part of my deployment workflow (inside my `npm run` script) so when I deploy a new version of my app in an environment, new migrations are executed automatically. In environments like heroku, kubernetes and the like, several instances can be started concurrently, so the migration scripts can be launched concurrently. Without a locking mechanism, this can result on the same migrations being executed several times, etc.

I know that in [Liquibase](http://www.liquibase.org), for example, uses a separate "lock" table to prevent this kind of problems (see http://www.liquibase.org/documentation/databasechangeloglock_table.html).

I seems to me that there is no equivalent mechanism in db-migrate currently. Am I mistaken? If not, are there any plans for implementing it in the future?

Thanks!

**Comment by wzrdtales** [comment]
>  What happens if several people (or several scripts) try to run a db-migrate up at the same time against the same database? Is there any locking mechanism?

Depending on what they going to execute some of them just die while the process is running or if you do something strange in your up or down routine even worse things could happen which could leave you in a broken state.

I actually have been asked this some time ago and yes, I am definitely going to add some locking mechanism, which will be especially important for zero downtime stuff.

**Comment by germanSancho** [comment]
Great. Let me know if you need some testing and/or help with the design :)

**Comment by fdw** [comment]
Has there been any progress with this? I'd like to use this feature as well.

**Comment by wzrdtales** [comment]
@fdw Not yet, work is starting to get traction on some items currently, also looking at this item again right now.

**Comment by wzrdtales** [comment]
State manager is in work currently, which will cover this topic as well as some other topics such as atomic actions, crash resistent migrations and ZDC.

**Comment by 1MikeMakuch** [comment]
Has there been any progress with this? I'd like to use this feature as well.

**Comment by wzrdtales** [comment]
Yes, some progress, in the beta version there is already the state manager, but it does not yet take care of concurrency control.

**Comment by wzrdtales** [comment]
tracked in #538
