### ISSUE TITLE
Issue with coffeescript

### ISSUE THREAD

**Issue by toovy** [db-migrate/node-db-migrate#465]
This project is what I need. I found that the documentation does not seem to be up-to-date. Maybe I'm missing something. The following problem arose.

Using the --coffee-file switch I can generate coffee-script files. Neat. But running

    $db-migrate up

...does not find any migration file. The issue seems to be that the regex does not match .coffee files any more. I found out that important lines were removed in a924436c79c534422b8d14e77d9a4d08c5be38cf.

@wzrdtales as author of this commit: Is saw you implemented a plugin logic. Is there an easy way to get coffee-script support back? Maybe a plugin exists? I could not find anything. So thanks in advance.

**Comment by wzrdtales** [comment]
@toovy Sorry for the late response, and yes, there is:
https://www.npmjs.com/package/db-migrate-plugin-coffee

So installing via npm install db-migrate-plugin-coffee should fix your problem.

**Comment by wzrdtales** [comment]
To note, all plugins must be prefixed with db-migrate-plugin so this is the way you can search for them.

**Comment by toovy** [comment]
@wzrdtales thank you for this hint. I've searched the documentation like hell. Is there an updated documentation describing the plugin system? Cause I think the official documentation did not mention anything about it.
