### ISSUE TITLE
No such driver found ... db-migrate-sqlite3

### ISSUE THREAD

**Issue by mbret** [db-migrate/node-db-migrate#466]
I got this exception on one of my project using db-migrate-sqlite3 as driver. I have both db-migrate and db-migrate-sqlite3 in my package and they are both installed inside root node_modules. However I still get this exception
`{ stack: 'No such driver found, please try to install it via npm install db-migrate-sqlite3 or npm install -g db-migrate-sqlite3' }`

I really have no idea since node_modules/db-migrate-sqlite3 exist and target to index.js when I require it manually in my index scritp.

Here is my code

```
DBMigrate.getInstance(true, {
            cwd: path.resolve(__dirname + "/.."),
            config: {
                dev: {
                    driver: "sqlite3",
                    filename: path.resolve(process.cwd(), "database.db"),
                }
            },
            env: "dev"
        });
```

Also when I log the driver resolution I get this path for the resolve
`resolve.sync(req, { basedir: process.cwd() }) ` => `/home/pi/chewie-app/node_modules/db-migrate-sqlite3/index.js` which is correct !

**Comment by mbret** [comment]
Okay after some investigation the real error comes from db-migrate-sqlite and is
`Error: Cannot find module '/home/pi/chewie-app/node_modules/sqlite3/lib/binding/node-v51-linux-arm/node_sqlite3.node`

**Comment by wzrdtales** [comment]
@mbret Also sorry here for the late response.

Did everything worked for you now or do still experience problems? The error above sounds like that this is an ABI problem. Which node version do you experience this with? Did you tried to reinstall the plugin and force a rebuild?

**Comment by lperichon** [comment]
I'm having this same issue on raspberry pi! it works fine on dev environment, but not on the pi.
I tried installing db-migrate, db-migrate-sqlite3 and sqlite3 both globally and locally and always get

pi@raspberrypi:~/databasesqlite $ node node_modules/db-migrate/bin/db-migrate up
[ERROR] Error: No such driver found, please try to install it via npm install db-migrate-sqlite3 or npm install -g db-migrate-sqlite3
    at Object.exports.connect (/home/pi/databasesqlite/node_modules/db-migrate/lib/driver/index.js:77:11)

**Comment by wicadmin** [comment]
same issue here as @lperichon . I have sqlite3 4.0.1 installed but when trying to install db-migrate-sqlite3 it seems it is attempting to download an older version and cannot find it?

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
```

**Comment by korzo** [comment]
@wicadmin Either fork and update sqlite3 version or you can use my fork:
```npm install https://github.com/korzo/sqlite```

**Comment by wzrdtales** [comment]
Ok, please open a new issue, since this issue is about something different.

In your case the ABI is broken, (again... yah this is a node thing :) ). I will have a look, probably, and hopefully upgrading sqlite beneath will solve it.

**Comment by wzrdtales** [comment]
And upgrading sqlite outside wont help. the db-migrate driver carries along sqlite by itself and not as a peer dependency. So it wouldn't help, but node 10 probably should be just be expected to break without upgrading the ABI again. But that is nothing new, I will look to upgrade it this weekend, should an upgrade be available to the updated ABI.

**Comment by wicadmin** [comment]
I updated the package.json of the sqlite and did an 'npm pack' and install it as a tarball to get around the issue:
```
  "dependencies": {
    "bluebird": "^3.1.1",
    "db-migrate-base": "^1.5.3",
    "sqlite3": "^4.0.1"
  },

```

**Comment by wzrdtales** [comment]
An updated version is out, tests on v10 fail currently, but this somewhere in the submodule used for testing `db-meta`. Will need to look what exactly broke there in v10.

**Comment by korzo** [comment]
Thank you very much. Everything works now.
I think the problem with test is that this.callback passed to fs.unlink is undefined.
