### ISSUE TITLE
No documentation on the usage of seeders

### ISSUE THREAD

**Issue by StlthyLee** [db-migrate/node-db-migrate#467]
Having looked through the codebase, docs and even the issues, the only thing I can find related to documentation on the usage of seeders, is lots of people asking for  documentation, one person posting a link that returns a "502 bad gateway" error and no actual documentation. 

So I thought I'd better just come straight out and ask myself, is there any documentation on creating and using seeders, whether there is a command to create a barebones seed file (like with migrations), how a seed file might look etc. 

Thanks in advance.

**Comment by michaelwittig** [comment]
you will find some information here: https://github.com/db-migrate/node-db-migrate/issues/292

**Comment by wzrdtales** [comment]
Closing and referring also to #292, just posted something over there, more later this week.
