### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by SeanJOBrien** [db-migrate/node-db-migrate#472]
Hello,

This is very much a question.

On generation of a migration using

`db-migrate create <NAME> --config config/database.json`

 The file generated looks thus.

```
'use strict';

var dbm;
var type;
var seed;

/**
  * We receive the dbmigrate dependency from dbmigrate initially.
  * This enables us to not have to rely on NODE_PATH.
  */
exports.setup = function(options, seedLink) {
  dbm = options.dbmigrate;
  type = dbm.dataType;
  seed = seedLink;
};

exports.up = function(db) {
  return null;
};

exports.down = function(db) {
  return null;
};

exports._meta = {
  "version": 1
};
```

my question is around "exports._meta" this is meta data for that particular file from what i can see, does it serve any other purpose ?

Thanks

**Comment by wzrdtales** [comment]
@SeanJOBrien Yes it does, this is really what it sounds like. It is metadata for this specific migration and should help in the future, to identify the version of your migration, to actually allow a few things.

1) Migrate migration changes into a new schema
2) Allow new versions of migrations that could look totally different

**Comment by SeanJOBrien** [comment]
Perfect thank you, sorry for the late reply.

**Comment by Diluka** [comment]
@wzrdtales Shall I change this number every time or in what situation must I change it?

**Comment by wzrdtales** [comment]
@Diluka you may never touch it.

**Comment by Diluka** [comment]
understood,thx
