### ISSUE TITLE
Error: connect ECONNREFUSED when running migration (pg driver)

### ISSUE THREAD

**Issue by abaracedo** [db-migrate/node-db-migrate#477]
I am using `postgresql` and I get this error when I try to execute a migration:

```
[ERROR] Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

In my `database.json` I have this configuration:

```
{
  "dev": {
    "driver": "pg"
  },
  "pg": {
    "driver": "pg",
    "user": "test",
    "password": "test",
    "host": "postgres://localhost:5433",
    "database": "testdb",
    "schema": "public"
  }
}
```

I can execute `sql` code inside my app but I can't using migrations

Probably the problem comes because the port I am using is different from which uses the package? I think it is a bit strange because I tried with Docker where I have the port `5432` and I get the same errors.

**Comment by felipel1292** [comment]
Try this.

"pg": {
    "driver": "pg",
    "user": "test",
    "host": "localhost",
    "port": 5433,
    "database": "testdb",
    "schema": "public"
  }

**Comment by abaracedo** [comment]
@felipel1292 I get the same error message :(

**Comment by wzrdtales** [comment]
As you encountered the error: "ECONNREFUSED", I have to assume that you're just not running a database on this host or port. B/c this is what the error states. Please check that you're really targeting the  right ip and port which postgres bound to.

**Comment by abaracedo** [comment]
@wzrdtales I have solved the problem. As you said it was about the IP, as I am using `docker-compose` I did not specify the `environment` on my `web` service and I was trying to connect two containers with `localhost`.

**Comment by wzrdtales** [comment]
I'm glad that you were able to figure it out :)

**Comment by LarrySul** [comment]
const express = require("express"),
  router = express.Router(),
  { Client } = require("pg"),
  // for connection information
  client = new Client({
    user: "larry",
    host: "localhost",
    database: "parcelApplication",
    password: "larry",
    port: 5433
  });

    
// create parcel
router.get("/", (req, res) => {
    client.connect((err, client, done)=>{
        if (err) {
           throw err;
        }else{
            client.query("SELECT * FROM public.Parcel", (err, res)=>{
               done();
               if(err){
                   throw err;
                }else{
                    res.status(200).json({
                    message: "fetch success"
                    })
                }
            })
        }
    })
})   

module.exports = router;

**Comment by Chaklader** [comment]
This is definitely related to the database connection issue. I just had it, because, I run the app without running the PostgreSQL firstly.
