### ISSUE TITLE
supporting other data type like json, array, point etc for postgres

### ISSUE THREAD

**Issue by ajaybhatt17** [db-migrate/node-db-migrate#480]
is there any provision or future plan for this ?

**Comment by wzrdtales** [comment]
@ajaybhatt17 Any driver which are external as by now, in your case https://github.com/db-migrate/pg can define its own data types.

Those extensions are usually noted as database specific extensions and render your migrations incompatible to other databases. This is not a problem, but required to be documented though.

**Comment by ajaybhatt17** [comment]
thanks for reply. Got it.

Anyway, Here one of the pull request for more column spec with respect to pg https://github.com/db-migrate/pg/pull/17 

when u are planing to merge this?

**Comment by wzrdtales** [comment]
Will take a look now.

**Comment by wzrdtales** [comment]
its merged now
