### ISSUE TITLE
Question: How to use scopes correctly?

### ISSUE THREAD

**Issue by ssljivic** [db-migrate/node-db-migrate#482]
One use of scopes is, for example, to have a "test-data" scope which inserts some test data, which is desired only in certain environments (e.g. dev, test). 

The problem how db-migrate uses scopes (at least its how I understood) is that I can run either a "default" migrations (in the root folder) or one of the scoped migrations in the subfolder.

The problem is that all migrations from root folder will be executed and after that all migrations from e.g. "test" subfolder will be executed:

```
db-migrate up
db-migrate up:test
```

Consider the following migrations files in the root folder:

1. 20170610090000-create-table (creates table with columns A and B)
2. 20170612090000-drop-col-B (drops column B)

and following migrations in test subfolder:

1. 20170611090000-insert-data (inserts test data into columns A and B)

If ran on an empty database ```db-migrate up``` followed by ```db-migrate up:test``` will produce an error since we will try to insert data in column B that does not exists (deleted by script 2 in the root folder)

A desired behaviour would be to be able to specify multiple scopes and that all migrations from all those scopes are ordered correctly based on timestamps and execute in that order. For the above example, I should be able to run "default" and "test" scopes with scripts in the following order:

1. 20170610090000-create-table (creates table with columns A and B)
2. 20170611090000-insert-data (inserts test data into columns A and B)
3. 20170612090000-drop-col-B (drops column B)

It could be that I missed docs on how to do that, so maybe you could help me with this. If this is not possible, than this is a serious limitation of db-migrate.

Thanks

**Comment by wzrdtales** [comment]
@ssljivic This is not there yet, targets are to add grouping and manual sort adjustments to scopes. Feel free to open a PR for this though :)

**Comment by cyrilnie** [comment]
Any plans to bring this feature in?
