### ISSUE TITLE
Wrong instruction in error message tips

### ISSUE THREAD

**Issue by jfmmm** [db-migrate/node-db-migrate#483]
When you try to do `db:create` on a mongodb without having installed the driver for it, you get this message :

`[ERROR] No such driver found, please try to install it via npm install db-migrate-mongo or npm install -g db-migrate-mongo`

But the package was renamed to `db-migrate-mongodb` so you get a 404 if you do `npm install db-migrate-mongo`.

Edit: 

Actually even after installing the other one I get the same no driver error.. not sure if it's a bug or what.

**Comment by wzrdtales** [comment]
Your config should look like:

```json
   "mongo": {
    "driver": "mongodb",
    "host": "localhost",
    "database": "testing"
   }
```

If you specify the correct driver, it should load without errors.

**Comment by jfmmm** [comment]
ok thanks

isn't the error message still wrong since there is no such thing as a repo called `db-migrate-mongo` ?

**Comment by wzrdtales** [comment]
@jfmmm 

No, b/c the top module don't know which drivers exist. **Everyone** can write a driver though. Just check and be sure to pick up the correct naming:)

**Comment by wzrdtales** [comment]
Btw. mongo was never renamed, it has never been named like this and has been named db-migrate-mongodb since its creation.

**Comment by wzrdtales** [comment]
You can just search for everything starting with db-migrate-{drivername}

If maintainers correctly tagged their drivers you can also effieciently filter them like this:
https://www.npmjs.com/search?q=db-migrate%20keywords:driver&page=1&ranking=optimal

Otherwise just search for db-migrate and search for the prefixed packages.
