### ISSUE TITLE
[SQL API] Implement removeColumn or remove Not Implemented APIs in documentation

### ISSUE THREAD

**Issue by melnik-nikita** [db-migrate/node-db-migrate#486]
Please implement removeColumn and other unimplemented SQL APIs or remove them from documentation.

**Comment by wzrdtales** [comment]
What exactly are you referencing? They are implemented, are you on the wrong issue tracker?

**Comment by wzrdtales** [comment]
>Please implement removeColumn and other unimplemented SQL APIs or remove them from documentation.

Also to add this is an issue tracker and not your personal command and control board, at least show some respect, coming in here and giving commands is not a proper behavior and is also not tolerated. Especially if you seem to have rather a question than an actual improvement, as your stated unimplemented function is there. 

You're very welcome to ask questions, write suggestions and even better help and contribute to open source by contributing PRs yourself, but the way you wrote this ticket is considered to be very rude.

Thank you.

**Comment by melnik-nikita** [comment]
Sorry, didn't want to be rude (i hoped the word "please" tells that).
But i was a bit confused when i saw:
db-migrate down
[INFO] Defaulting to running 1 down migration.
[ERROR] Error: not implemented
during the execution of db.removeColumn(table, column) method

**Comment by wzrdtales** [comment]
@melnik-nikita No the english language does not work that way :) Please is rather a phrase creating pressure than being polite. "Could you please", would be the proper term though, but apart from that it is more the way how you communicate things, and to tell somebody he should implement something or remove it instead is actually taken as rude though. As this is out of the world now. You're experiencing something that is totally normal. db-migrate is just the framework that does orchestration and some other stuff that sits at the top. On the lower level there are drivers and plugins, for once there are official ones, those are all those one you can find in this github organization, and the community ones.

So your driver relates to a specific driver in this case, this driver did or still does not implement the function you called out. Without completely communicating all details needed.

For the future I recitate my default quote for issues with non, or too less information.

Please provide  all informations necessary to reproduce your case.

This means, **always** post:
- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

**Comment by wzrdtales** [comment]
Closing this as solved, if there are open questions, please feel free to ask!
