### ISSUE TITLE
Heroku DATABASE_URL

### ISSUE THREAD

**Issue by mmowris** [db-migrate/node-db-migrate#488]
We cannot use pg native functionality. We've tried changing this in the module but aren't having any luck. We're able to get the DATABASE_URL read and show this through console.log in pg db-migrate module, but SSL is always undefined and off. None of the other answers here are of use, all look to lead to commits that are changed or code that has been modified and as such are deprecated :( Please help!

database.json: _have tried many iterations of this_

`{
  "default": "pg",
  "pg": { 
    "ENV": "DATABASE_URL",
    "addIfNotExists": {
      "ssl": true
    },
    "overwrite": {
      "native": true
    }
  }
}` 

error:
`[ERROR] error: no pg_hba.conf entry for host "204.14.239.17", user "user", database "database", SSL off
    at Connection.parseE (/Users/mmowris/Workspace/csa-portal/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/mmowris/Workspace/csa-portal/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/mmowris/Workspace/csa-portal/node_modules/db-migrate-pg/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
mmowris-ltm2:csa-portal mmowris$ sub`

cc: @joeyjmorales

**Comment by wzrdtales** [comment]
Ahh I guess you're coming from https://github.com/db-migrate/node-db-migrate/issues/349, yes this is not there yet.

Let me have a look, maybe I can just quickly push this out.

**Comment by wzrdtales** [comment]
Ok, you're lucky wasn't that a big deal.

Release under

+ db-migrate@0.10.0-beta.22

**Comment by mmowris** [comment]
@wzrdtales thank you so much for the quick response! very helpful module!

**Comment by kasongoyo** [comment]
This does not seems to work even with the current version. The content of overwrite and addIfNotExists does not seem to be returned by loadObject fn here https://github.com/db-migrate/node-db-migrate/blob/ac850c33b87e54a71cc306d6fdbcb16740b29354/lib/config.js#L154

**Comment by kasongoyo** [comment]
Inorder to overwrite or modify DATABASE_URL then you need to write it like this

```
{
    "default": "pg",
    "pg": {
        "url":{"ENV": "DATABASE_URL"},
        "addIfNotExists": {
            "ssl": true
        },
        "overwrite": {
            "native": true
        }
    }
}
```
