### ISSUE TITLE
--migration-table (or -table) does not work

### ISSUE THREAD

**Issue by trungdq88** [db-migrate/node-db-migrate#491]
I see `--migration-table` in the code but not in the docs. Is this option ready yet?

**Comment by wzrdtales** [comment]
@trungdq88 It is in the docs, maybe not explicitly mentioned though: https://db-migrate.readthedocs.io/en/latest/Getting%20Started/installation/

And yes, for sure you can use it.

**Comment by trungdq88** [comment]
Thanks for your response.
