### ISSUE TITLE
Rename DB field

### ISSUE THREAD

**Issue by BorntraegerMarc** [db-migrate/node-db-migrate#502]
We need the feature to be able to rename a column or nosql attribute....

**Comment by wzrdtales** [comment]
@BorntraegerMarc There is `renameColumn` though, I guess you wanted to target this at a specific driver? If so open the ticket on that driver instead :)

**Comment by BorntraegerMarc** [comment]
We are using ‘update’ now and it works well for nosql. So I’m just gonna close this issue 😄
