### ISSUE TITLE
Question: how to use switchDatabase?

### ISSUE THREAD

**Issue by WClouds** [db-migrate/node-db-migrate#507]
Hi, I am working with multiple dbs on the same mysql server/instance, and I need to switch db when migrate.
Is there any examples about how to use switchDatabase?

**Comment by wzrdtales** [comment]
Hey @WClouds ,

This actually depends on the database. this works for mysql though:
https://github.com/db-migrate/mysql/blob/master/index.js#L183


Using it in your migrations might only work within a single migration and you would need to switch back as the migration table would be missing. This is currently not yet completely available on that level. However, there is support at scoping level to switch databases. Please refer to the scoping config example over here:
https://db-migrate.readthedocs.io/en/latest/Getting%20Started/the%20commands/#scope-configuration

Also notice this only works for some databases. There are dbs where there are known issues. Talking especially about postgres here, which has no support for switching the db on the same connection. There are a couple of things that will change in the near future concerning this. I will keep you updated as soon as I have news for you on that topic here. Don't hesitate to bug me again shouldn't you hear from me again though :)
