### ISSUE TITLE
Use mongodb driver directly?

### ISSUE THREAD

**Issue by BorntraegerMarc** [db-migrate/node-db-migrate#526]
Hi @wzrdtales sorry if I'm asking something that has already been posted - but I didn't find anything in the documentation or in the existing issues.

I wanted to ask if it is possible to use the mongodb driver directly? Like this for example:
```
exports.up = function (db) {
  return db.driver.collectionName.find({id: 'ID'}).then((collection) => {
    collection.property = 'newValue';
    return collection.save();
  });
}
```

The idea: I want to only update one property in one entry in the DB.

The reason: We have "base data" defined in our app that get's initialized (and updated) with every release. This base data needs maintenance and it would be awesome if maintenance could be done with `node-db-migrate`.

Thanks for answering!

**Comment by BorntraegerMarc** [comment]
Friendly ping to @wzrdtales 🙂

**Comment by wzrdtales** [comment]
Thanks for bugging me :)

The answer is: not yet really, but this was asked a few times already, i wouldn't be against such option, as this would be an equivalent to runSql. Do you want to give this a shot?

**Comment by wzrdtales** [comment]
And merry christmas btw. :)

**Comment by BorntraegerMarc** [comment]
Merry Christmas to you too :)

Could you point me to the correct place where an export would need to be added? I tried to dig into the new code but the new structure is a bit confusing to me 😄

**Comment by wzrdtales** [comment]
For sure!

Here you go edit the mongo driver:

https://github.com/db-migrate/mongodb/blob/master/index.js#L10

When you add a new method that needs to be added to one of the interfaces, here is an example on how to do that:

https://github.com/db-migrate/mysql/blob/master/index.js#L420

**Comment by Aron4u** [comment]
i saw that the functions are there and merged ... how do i use this feature now? like you discribed in your inital post?
i get for 
db.driver  => undefined

**Comment by BorntraegerMarc** [comment]
Use it like this:
```
return db._run('getDbInstance')
        .then(dbDriver => {})
```

**Comment by ks-s-a** [comment]
You could faced to migration terminating problem. Just close the dbDriver to avoid it. 

```
return db._run('getDbInstance').then((dbDriver) => {
    return dbDriver.collection('collection_name')
      .findAll({
        prop: 'value'
      })
      .then(() => {
        return dbDriver.close();
      });
  });
```
