### ISSUE TITLE
Remove the commitlint & DCO bot

### ISSUE THREAD

**Issue by BorntraegerMarc** [db-migrate/node-db-migrate#528]
I have the feeling this repository needs as many contributors as possible and the entry bar for new contributors should be as low as possible. Mainly because the whole `db-migrate` project does not have that many developers that are actually helping out with PR's. The bots feel like overkill to me.

So my suggestion is to remove the commitlint & DCO bot for PR's as they make contributing overly complicated as also seen in my own PR: https://github.com/db-migrate/node-db-migrate/pull/525 -> I just wanted to make a small effort and add a template but am blocked now by these bots because I never had the time to actually dig into the commitlint topic (and somehow the DCO bot didn't work at all for me; but that is a seperate topic).

I suggest to remove them completely to lower the entry bar of new contributors to the `db-migrate` project so the community can benefit more.

**Comment by wzrdtales** [comment]
@BorntraegerMarc No, removing really simple conventions from a project is not a solution and you can just go ahead to any other project where you will find this stuff as well. The commitlint stuff is fairly easy, it means you have to comply to the standards for commit messages. Which the commitlint bot now fortunately also documents it now.

For the DCO it is even more simple, you just need to commit with `-s` if you've configured your git properly it will work out just fine. This project already had several contributions while these new standards are active and all got it working quite properly. Removing standards just for the comfort of others is not the solution. To note all those standards are things that are quite easy to get. And as soon as you did it once, you will never think again about it. B/c nothing of this stuff is complicated in any way, it is just setting standards in favour of quality and automation.

**Comment by BorntraegerMarc** [comment]
I didn't get it to work because I made contributions directly from GitHub without cloning it :) I think this topic is just a general disagreement and will close the issue. I will of course follow the guidelines of the project owner :)

**Comment by wzrdtales** [comment]
AS a tip you also need to ammend commits when you try to fix such issues and I'm very open to help getting through the standards.
