### ISSUE TITLE
Create migration under custom migrations directory

### ISSUE THREAD

**Issue by dwiajik** [db-migrate/node-db-migrate#543]
## Current behavior
I put my database migrations under ./data/migrations directory. However, when I ran `db-migrate create --config data/config.json -e pg --migration-dir data/migrations users` it created migration file under ./migrations directory. Is this behavior expected?

## Expected behavior
I expected it would create migration file under ./data/migrations directory.

## Minimal reproduction of the problem with instructions
Run `db-migrate create --config data/config.json -e pg --migration-dir data/migrations users`

## Environment

<pre><code>
db-migrate version: 0.10.5
db-migrate-pg driver with versions:0.3.0

Additional information:
- Node version: 9.5.0
- Platform:  Ubuntu 17.10

</code></pre>

**Comment by wzrdtales** [comment]
You have an error in your command line, it is plural `migrations-dir` not `migration-dir`.

**Comment by dwiajik** [comment]
Oh silly mistake, thanks @wzrdtales

**Comment by jonbmorgan02** [comment]
Is there a way to config this in databse.json?
