### ISSUE TITLE
Migration record is inserted/deleted, when migration command failed

### ISSUE THREAD

**Issue by winnycnua** [db-migrate/node-db-migrate#544]
## I'm submitting a...

<pre><code>
[ X] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

`$ db-migrate up` produces an error, but record is added into migrations table
`$ db-migrate down` produces an error, but record is deleted from migrations table

## Expected behavior

`$ db-migrate up` produces an error, and record is not added into migrations table
`$ db-migrate down` produces an error, and record is not deleted from migrations table

## Minimal reproduction of the problem with instructions
Create migration file with SQL statement error. For example:
`db.runSql('abracadabra', [], (err) => {
        console.log('err', err);
    });`

## What is the motivation / use case for changing the behavior?

It does not make sense to log failed migration as completed.

## Environment

<pre><code>
db-migrate version: 0.10.15 
db-migrate driver with versions:  mysql v1.1.10

Additional information:
- Node version: 8.9.4  
- Platform:  Linux 

</code></pre>

**Comment by wzrdtales** [comment]
This is not a bug, you're just using migrations wrong in that case. You should not use the callback at all of any driver method to log anything to the console and if you do then pass the error correctly. Instead use the new way to work with migrations and work with the returned promises instead.

If you however swallow the errors, then db-migrate can't know that your migration failed, so not a bug.
