### ISSUE TITLE
Specify migrations directory over progamable API

### ISSUE THREAD

**Issue by BorntraegerMarc** [db-migrate/node-db-migrate#553]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [X] Question

## Current behavior

I have the following code:
```
const dbm = dbMigrate.getInstance(true, {
            cwd: './',
            env: 'dev'
});
await dbm.up(100, '');
```

My problem is now that the migrations are not under `./root/migrations` but under `./root/build/migrations`. How can I specify programatically to search in a different folder for the migrations?

But my `package.json` & `database.json` are under `./root`

## Environment

<pre><code>
db-migrate version: 0.10.5

Additional information:
- Node version: 8.9.1
- Platform:  Windows

Others:

</code></pre>

**Comment by wzrdtales** [comment]
Good question and good catch!

Is not possible currently, the module branch just returns the default config currently:

https://github.com/db-migrate/node-db-migrate/blob/5ee386b423e3a91ef25eb294a516552506a441f2/lib/commands/set-default-argv.js#L100-L106

Which should be however easy to fix though.

**Comment by BorntraegerMarc** [comment]
@wzrdtales should I take a shot at this or do you want to fix it? :)

**Comment by wzrdtales** [comment]
Feel free to do so, PRs are always welcome :)

**Comment by wzrdtales** [comment]
I would have thought of a simple `Object.assign` with the defaultObject and the options object.
