### ISSUE TITLE
getInstance is not respecting cmdOptions correctly

### ISSUE THREAD

**Issue by BorntraegerMarc** [db-migrate/node-db-migrate#557]
## I'm submitting a...

 - [X] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

With this PR https://github.com/db-migrate/node-db-migrate/pull/555 we introduced the feature to pass in `cmdOptions` programatically. So I included it in my project like this:
```
dbMigrate.getInstance(true, {
            cwd: '../komed-emr',
            env: 'dev',
            cmdOptions: {
                'migrations-dir': './build/src/migrations'
            }
});
```

But I noticed that it does not work. The `cmdOptions` actually never are considered. So I added in this line: https://github.com/db-migrate/node-db-migrate/blob/master/lib/commands/set-default-argv.js#L101 a console.log: `console.log(internals);`

This was the output:
```
{ onComplete: [Function],
  migrationProtocol: 1,
  isModule: true,
  plugins: { overwrite: [Function: overwrite], hook: [Function: hook] },
  dbm:
   {  },
  currentEnv: 'dev',
  cwd: '../komed-emr' }
```

As seen the passed in `cmdOptions` are never included.

## Expected behavior

The `cmdOptions` are included and passed into the method.

I tried to debug the lib but couldn't find the root cause. Maybe you @wzrdtales could point me again to the place where the bug occurs and I could do a new PR to fix it.

## Environment

<pre><code>
db-migrate version: 0.10.6
db-migrate driver with versions: mongodb 1.4.0 

Additional information:
- Node version: v8.9.1  
- Platform: Windows 

Others:

</code></pre>

**Comment by BorntraegerMarc** [comment]
Friendly ping to @wzrdtales :)

**Comment by wzrdtales** [comment]
Argh...

Actually internals does not include the options object itself, but evaluates bits of it here:

https://github.com/db-migrate/node-db-migrate/blob/efb8f3601fd89b96d18d3c64c8da3eb830b70d70/api.js#L48-L64

So this is where the bug sits :/

**Comment by dschinkel** [comment]
usage of it, an example here in case this helps anyone: [767](https://github.com/db-migrate/node-db-migrate/issues/767)
