### ISSUE TITLE
Getting issue while installing it

### ISSUE THREAD

**Issue by jitendrapawar** [db-migrate/node-db-migrate#559]
Please find attached file for the error.
[npm-debug.log](https://github.com/db-migrate/node-db-migrate/files/1844302/npm-debug.log)

Getting error while installing the package with command 

`npm install -g pg-db-migrate`

**Comment by wzrdtales** [comment]
This is not db-migrate, this is a different package. If you want to use db-mgirate with pg then install db-migrate and db-migrate-pg
