### ISSUE TITLE
Migration is fine but it's not terminating

### ISSUE THREAD

**Issue by vicke4** [db-migrate/node-db-migrate#561]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior
I ran a migration, changes are reflecting but it's not terminating.

![migration not terminating](https://i.imgur.com/QJandWu.png)

## Expected behavior
It has to return that's it...:D

## Minimal reproduction of the problem with instructions
I tried with both `callback`  and `Promise` versions still I'm not able to make it work.

### Callback version
````
const _ = require('lodash');
const { selectQuery } = require('../utils/db');

const updateOrders = (db, callback) => {
    const ordersQuery = `
      SELECT orderId, orderBuyDetails FROM orders
    `;

    selectQuery(ordersQuery, [], [], (err, orders) => {
        orders.forEach((order, index) => {
            const buyDetails = JSON.parse(order.orderBuyDetails);
            const orderUpdateQuery = `
              UPDATE orders SET quantity = ${buyDetails ? _.sumBy(buyDetails, 'quantity') : 0}
              WHERE orderId = ${order.orderId}
            `;

            db.runSql(orderUpdateQuery, () => {
                if (index === orders.length - 1) callback();
            });
        });
    });
};

exports.up = (db, callback) => {
    updateOrders(db, () => callback());
};

exports.down = (db) => {
    const query = `
      UPDATE orders SET quantity = NULL
    `;

    return db.runSql(query);
};

````

### Promise version

````
const _ = require('lodash');
const { selectQuery } = require('../utils/db');

const updateOrders = (db) => {
    const ordersQuery = `
      SELECT orderId, orderBuyDetails FROM orders
    `;
    const queries = [];
    const queryPromise = new Promise((resolve) => {
        selectQuery(ordersQuery, [], [], (err, orders) => {
            orders.forEach((order) => {
                const buyDetails = JSON.parse(order.orderBuyDetails);
                const orderUpdateQuery = `
                UPDATE orders SET quantity = ${buyDetails ? _.sumBy(buyDetails, 'quantity') : 0}
                WHERE orderId = ${order.orderId}
            `;
                queries.push(orderUpdateQuery);
            });

            resolve(queries);
        });
    });

    return queryPromise.then((dbQueries) => {
        dbQueries.reduce((promise, query) => promise.then(db.runSql(query)), Promise.resolve());
    });
};

exports.up = db => updateOrders(db);

exports.down = (db) => {
    const query = `
      UPDATE orders SET quantity = NULL
    `;

    return db.runSql(query);
};

````
I'm sure that I'm missing something. Can anybody help me with this?

## Environment
````
db-migrate version: 0.10.0-beta.24
db-migrate driver with versions: MySQL driver v1.1.10

Additional information:
- Node version: 6.14.1 
- Platform: Ubuntu 16.04 
````

**Comment by wzrdtales** [comment]
you will need to close all connections, since you include an external component here `const { selectQuery } = require('../utils/db');` it is quite likely that this is the fault. I suggest to never work with callbacks as of today, they're supported backwards and will be for a while. However, this is not due to `db-migrate` which I can assure from what you've posted, but most probably the external stuff you introduced here. Just note that everything that waits for data on the loop will stop node from exiting.

**Comment by wzrdtales** [comment]
In the meantime while you search for what you've missed closing or unregistering, you can also use force-exit, which forcefully exits, just as the name says.

**Comment by vicke4** [comment]
Thanks @wzrdtales, the MySQL connection was not terminated. Now, all fine.
