### ISSUE TITLE
Error: No such driver found, please try to install it via npm install db-migrate-sqlite3 or npm install -g db-migrate-sqlite3

### ISSUE THREAD

**Issue by lperichon** [db-migrate/node-db-migrate#566]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior

Can't run or create migrations for sqlite3 on raspberry pi. Always get:
 
[ERROR] Error: No such driver found, please try to install it via npm install db-migrate-sqlite3 or npm install -g db-migrate-sqlite3

## Expected behavior

[INFO] No migrations to run
[INFO] Done

## Minimal reproduction of the problem with instructions

Tried installing db-migrate, db-migrate-sqlite3 and sqlite3 both locally and globally.
It works on development environment (ubuntu), but not on raspberry pi

## Environment

<pre><code>
db-migrate version: 0.11.1
db-migrate-sqlite3 with version: 0.2.1

Additional information:
- Node version: 8.9.4
- Platform:  Raspberry pi (Raspbian)

Others:
- sqlite3 with version: 3.1.13
</code></pre>

**Comment by wzrdtales** [comment]
Seems like there is something going wrong. You will need however to provide more sufficient amount of information, as I have nothing at all right now to reproduce or help you.

First of all, please post all information including the OS version and the full output of the verbose run.

Next post the output of the following commands

    ls -lah node_modules

    node -e "require('db-migrate-sqlite3')"
