### ISSUE TITLE
no way to change migration table name?

### ISSUE THREAD

**Issue by cs4inctec** [db-migrate/node-db-migrate#572]
## I'm submitting a...

 - [ ] Bug report  
 - [x] Feature request
 - [x] Question

## Current behavior
no documented way to change the migration table name.

## Expected behavior
Due to a comment in #192 , I thought there would be a way since 0.10.0.

## What is the motivation / use case for changing the behavior?
I have different applications that need a database. For testing I use one database for all applications. I migrated one application to use migrations and like it. But before converting more, I think it would be not good to have one migration table for multiple disjunct migrations.

## Environment
<pre><code>
db-migrate version: 0.11.1
db-migrate-pg: v0.4.0

Additional information:
- Node version: 8.11.2
- Platform:  Mac, Linux

**Comment by U-4-E-A** [comment]
in .db-migraterc: -

`
{
  "table": "_migrations"
}
`

**Comment by juandm** [comment]
This information should be in the docs!!

**Comment by wzrdtales** [comment]
then feel free to add it https://github.com/db-migrate/english-docs!!!!!!11111eleven ...

**Comment by juandm** [comment]
I created the PR including this in the docs. Sorry for the (!!), that was not my intention. 

 https://github.com/db-migrate/english-docs/pull/43

**Comment by wzrdtales** [comment]
Thank you for your contribution!
