### ISSUE TITLE
Error with the mongodb driver package name

### ISSUE THREAD

**Issue by jderuere** [db-migrate/node-db-migrate#581]
## I'm submitting a...

 - [ x] Bug report 

Trying to use it with the mongodb driver but have this error

` [ERROR] Error: No such driver found, please try to install it via npm install db-migrate-mongo or npm install -g db-migrate-mongo`

Unfortunatly the name of your driver is not db-migrate-mongo but db-migrate-mongodb

Did I miss something?

**Comment by wzrdtales** [comment]
It is not a bug, but you use it wrong.
The thing is easy, the driver is named mongodb, so you also need specify the driver name as mongodb and not mongo, then everything works.

**Comment by wzrdtales** [comment]
Actually you find it named correctly in the docu

https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/
driver "mongodb"

should be just fine using and adjusting this.

**Comment by jderuere** [comment]
Thanks, that was it. Wrong copy/paste
