### ISSUE TITLE
How to close connection programmatically

### ISSUE THREAD

**Issue by KingRial** [db-migrate/node-db-migrate#583]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior
I would like to close the DB connection when DB-migrate programmatically:
- only creates a database
- fires the "up/down" migration without loosing promises

## Expected behavior
When creating only the Database:
```
const DBMigrate = require('db-migrate');
let _oHandler = DBMigrate.getInstance(true);
return _oHandler.createDatabase('Foo')
      .then( () => {
// I would like to stop using DBMigrate, clean it and close the DB connection and continue the code execution
      })
;
```
Using "onComplete" as describe [here](https://db-migrate.readthedocs.io/en/latest/API/programable/) can't work since createDatabase won't fire onComplete

When launching Up/Down:
```
const DBMigrate = require('db-migrate');
let _oHandler = DBMigrate.getInstance(true);
return _oHandler.up()
      .then( () => {
// I would like to stop using DBMigrate, clean it and close the DB connection and continue the code execution
      })
;
```
Using "onComplete" as describe [here](https://db-migrate.readthedocs.io/en/latest/API/programable/) kills the the promise chain

## What is the motivation / use case for changing the behavior?
Keeping open connection/instance after all the desired actions are done it's not usefull and far from being acceptable. 

## Environment
<pre><code>
db-migrate version: 0.11.3
db-migrate driver with versions: mongoose 5.2.14

Additional information:
- Node version: 8.12.0
- Platform:  Linux, Windows
</code></pre>

**Comment by KingRial** [comment]
Any hint would be really appreciated!

**Comment by Levino** [comment]
I came here and was just about to join @KingRial in his complaints. But I double checked and in my case the open connection came from `knex` which you can close with `knex.destroy()`. So I recommend double checking whether or not other connections your are using are still open @KingRial

**Comment by KingRial** [comment]
My bad; double checked and I just misunderstood the logging.
