### ISSUE TITLE
Use transactions in runSql (mysql)

### ISSUE THREAD

**Issue by ShaharMynd** [db-migrate/node-db-migrate#588]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior

When i run ``` db-migrate up:all -e dev-mysql ```

## Expected behavior

When I use db.runSql it will start in a transaction, 
if for whatever reason it fail, it will use rollback.

## Minimal reproduction of the problem with instructions
create sql migration file:
```
db-migrate create [file-name] --sql-file -e dev-mysql
```
create multiple statement query
one query should also has syntax error or somthing to fail.

use db-migrate up
```
db-migrate up:all -e dev-mysql
```
Observe that the db was not rolledback.

## What is the motivation / use case for changing the behavior?

You already made the function to support it:
startMigration and endMigration.

It kind of funny that some tables updated, and some not.
You can't properly migrate down because of it too.

## Environment

<pre><code>
db-migrate version: 0.11.3
plugins with versions: no plugins.
db-migrate driver  with versions: mysql 1.1.10 

Additional information:
- Node version: 8.11.3
- Platform:  Mac

**Comment by team-bat** [comment]
I've got the same problem, can you look on it?

**Comment by vipulw2011** [comment]
Do we have any update on this ?
