### ISSUE TITLE
Custom Datasource connector

### ISSUE THREAD

**Issue by simonefuoco** [db-migrate/node-db-migrate#591]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Question
Hello,
I'm trying to develop a system that sync different datasource (one-way-sync) and I found node-db-migrate. Is it possible to develop some custom driver to connect to specific database or other datasource? For example to connect to MSSQL or to REST API. I'm ready to develop it and share with the world if this is possible. I think synchronization is a common task for a developer and it is not necessary to reinvent the wheel.

Thanks, best regards.

**Comment by wzrdtales** [comment]
You can develop a driver for db-migrate, for any database (or REST-API if this really applies) you want. Just take a look at the existing ones in the db-migrate organization or in one of the community contributed ones. There is also a section in the docs dedicated to this.

However, what you're trying is probably something different. You could use db-migrate to keep your definition in sync, means schema and modifications around changing the schema. But what you search for is probably more a target for ETL tools like Talend.

**Comment by simonefuoco** [comment]
Thanks for the response, I really appreciate your help. ETL tool is what I've been searching. 🥇 💯
