### ISSUE TITLE
Error when setting only "migrationsDir" in database.json

### ISSUE THREAD

**Issue by JZumun** [db-migrate/node-db-migrate#597]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior
I currently want to place the migrations directory somewhere else, and since I'm using the DATABASE_URL environment variable, I placed the following in database.json:
```json
{
	"migrationsDir": "./src/db/migrations"
}
```

However, running `npx db-migrate create sample` returns the following error:
```
[ERROR] Error: Environment(s) 'dev, development' not found.
    at Config.exports.setCurrent (/project-root/node_modules/db-migrate/lib/config.js:25:11)
    at Object.exports.loadObject (/project-root/node_modules/db-migrate/lib/config.js:189:9)
    at Object.exports.loadFile (/project-root/node_modules/db-migrate/lib/config.js:95:18)
    at loadConfig (/project-root/node_modules/db-migrate/lib/commands/helper/load-config.js:12:18)
    at new dbmigrate (/project-root/node_modules/db-migrate/api.js:68:43)
    at Object.module.exports.getInstance (/project-root/node_modules/db-migrate/index.js:62:10)
    at /project-root/node_modules/db-migrate/bin/db-migrate:32:25
    at /project-root/node_modules/resolve/lib/async.js:48:21
    at ondir (/project-root/node_modules/resolve/lib/async.js:199:27)
    at onex (/project-root/node_modules/resolve/lib/async.js:107:32)
```

Even placing a defaultEnv, with configuration:
```json
{
        "defaultEnv":"other",
	"migrationsDir": "./src/db/migrations",
        "other": {"ENV": "DATABASE_URL"}
}
```
results in `[ERROR] Error: Environment(s) 'other' not found.`

## Expected behavior
This should work without errors

## Minimal reproduction of the problem with instructions
Have the following database.json at the root of the project and run `npx db-migrate create sample`
```json
{
	"migrationsDir": "./src/db/migrations"
}
```

## What is the motivation / use case for changing the behavior?
I want to change the migrations directory while keeping everything their default behavior, without having to repeatedly pass the `--migrations-dir` option in the command line.

## Environment

<pre><code>
db-migrate version: 0.11.4
db-migrate driver with versions:  pg 0.4.0

Additional information:
- Node version: v11.0.0
- Platform:  Mac

Others:

</code></pre>

**Comment by JZumun** [comment]
It is interesting to note for the second scenario, where I specify a defaultEnv, that in the `setCurrent` function in `db-migrate/lib/config.js` the error occurs because in this check:
```  
if (dbmUtil.isString(current) && this[current]) {
```
`dbmUtil.isString(current)` is false because `current` is now an object `{ [String: 'other'] driver: 'postgresql', database: 'qd', host: 'localhost' }` and so `typeof current === "object"`

**Comment by brirtch** [comment]
Did you ever resolve this issue?
