### ISSUE TITLE
Baseline existing db

### ISSUE THREAD

**Issue by SergeyCherman** [db-migrate/node-db-migrate#604]
## I'm submitting a...

 - [ ] Bug report  
 - [ X] Feature request
 - [X ] Question

Is there a way to baseline an existing database? For example if adding db-migrate to an existing database we might not want to run some of the migrations. Is there a way to only run migrations newer then the baseline?

**Comment by wzrdtales** [comment]
No, there is no way of skipping them. I would suggest you simply backup the migrations table as well. Maybe you could provide a use case should this be still from interest.

**Comment by tchar** [comment]
Hello, I am checking to see if this is something that is/could be implemented.

Here is a use case:
1. I have already a database with all the migrations in SQL files and I don't want to run them as they already exist and I was not using any tool up to this point. I want to keep track of the migrations from this point and onward.
2. I usually test my migrations on some development SQL. After I am happy with the result, I save the code to the migration file. So for development, I want to mark the migration as complete/baseline so it does not run again. Then when I run it on production it runs properly
3. A more important use case which is similar to 2 when you have to issue hotfixes is explained by flyway [here](https://flywaydb.org/blog/skipexecutingmigrations).

Although 2 and 3 are important. 1 is the one that does not allow people to start using the tool midway. They either have to start using it from the beginning or not use it at all.

Cheers
tchar
