### ISSUE TITLE
Client does not support authentication protocol requested by server

### ISSUE THREAD

**Issue by danielb2** [db-migrate/node-db-migrate#610]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior
> [ERROR] Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

for this DATABASE_URL: `mysql://root:@localhost:3306/samsxci`

What would cause the above issue ?

( *however, no issues with another db url.* )

```
$ mysql --version
mysql  Ver 8.0.13 for osx10.12 on x86_64 (Homebrew)
```

## Expected behavior

should connect just fine. Just running the `db-migrate check` command

## Environment

```
  db-migrate: '^0.11.5',
  db-migrate-mysql: '^1.1.10',
  mysql2: '^1.6.4',
```

Additional information:
- Node version: v10.15.0 ( also tried v6.9.1)
- Platform:  Mac

**Comment by danielb2** [comment]
I switched to using mysql 5.7 locally to get things to work. but why doesn't it work with 8.x ?

**Comment by danielb2** [comment]
I ended up downgrading MySQL. Was there there another solution?

**Comment by cymen** [comment]
@danielb2 I was able to work around this with https://stackoverflow.com/a/50547109/122868

**Comment by gkrinc** [comment]
Can we update `db-migrate-mysql` to using `mysql2`? According to the SO post, this authentication issue has been around for a long time on `mysql` with no movement. Seems pretty bad to not support new security protocols. https://stackoverflow.com/a/56509065/596979

**Comment by wzrdtales** [comment]
Feel free to work on validating all functionalities on mysql2 and shoot a PR afterwards :) @gkrinc
