### ISSUE TITLE
Can the requirement of package.json and/or database.json be avoided?

### ISSUE THREAD

**Issue by AxelTerizaki** [db-migrate/node-db-migrate#612]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

The app I'm working on is packaged into a single executable file using zeit/pkg . However, when including db-migrate in the app and using it via its API, I'm running into several issues. Some of them have simple workarounds (like including `node_modules/db-migrate/lib/commands/**` to the `scripts` array of pkg's configuration (or else it complains about some missing files at runtime))

My main problem is the requirement of the package.json file. As it is I understand it's required by db-migrate to check which plugins are installed. I don't include the package.json of my project with the app I'm distributing since it's a single exe file. Same goes with database.json actually. What I'm doing as a work around is to create those ones (a fake package.json and a real database.json) at runtime. This is not ideal, but it works.

Could db-migrate's API accept a configuration object for the database (instead of looking through the database.json file) ? Same goes for package.json for plugins.

Thanks in advance :)

**Comment by wzrdtales** [comment]
You're asking for programmatic use. For the database.json, no changes are needed. This is defacto already possible in programmatic use. The docs need some love on that part (PRs welcome are welcome <3), but some is documented: https://db-migrate.readthedocs.io/en/latest/API/programable/#programable-api

But for your part: https://github.com/db-migrate/node-db-migrate/blob/b03c3f02e955a232681b7b99f23913ddb39ee459/index.js#L49. See this part, you can pass an options parameter and if you pass in here a config object, this will be used directly, for this see here: https://github.com/db-migrate/node-db-migrate/blob/b03c3f02e955a232681b7b99f23913ddb39ee459/api.js#L51

For the package.json, this is also already possible. you can pass the options param noPlugins see here https://github.com/db-migrate/node-db-migrate/blob/b03c3f02e955a232681b7b99f23913ddb39ee459/index.js#L56

And combine this with the options param plugins (you now need to gather the plugins completely by yourself) to pass in plugins by your logic: https://github.com/db-migrate/node-db-migrate/blob/b03c3f02e955a232681b7b99f23913ddb39ee459/index.js#L61

**Comment by wzrdtales** [comment]
Closing since everything you asked for is already there. Feel free to reach out again shouldn't this solve your request.

**Comment by AxelTerizaki** [comment]
Thanks for your help ! Indeed the docs could need some love, because I've read them and was pretty sure I didn't see anything about that :)
