### ISSUE TITLE
Gracefully handle non-migration files under migrations/

### ISSUE THREAD

**Issue by emlai** [db-migrate/node-db-migrate#616]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

If I have a non-migration .js file in the migrations/ directory, db-migrate chokes on it when I run the migrations:

```
[ERROR] TypeError: Cannot read property '1' of null
    at Class.parseName (/Users/emlai/src/resiflow/node_modules/db-migrate/lib/skeleton.js:164:17)
    at Class.init (/Users/emlai/src/resiflow/node_modules/db-migrate/lib/migration.js:20:24)
    at Class.prototype.(anonymous function) [as init] (/Users/emlai/src/resiflow/node_modules/db-migrate/lib/class.js:46:26)
    at new Class (/Users/emlai/src/resiflow/node_modules/db-migrate/lib/class.js:59:17)
    at /Users/emlai/src/resiflow/node_modules/db-migrate/lib/migration.js:339:14
    at Array.map (<anonymous>)
    at /Users/emlai/src/resiflow/node_modules/db-migrate/lib/migration.js:338:35
    at FSReqWrap.oncomplete (fs.js:135:15)
```

because the file path doesn't match the regex in: 

https://github.com/db-migrate/node-db-migrate/blob/d53369d5606d23e1fe3fac5eb0f612c336a477f4/lib/file.js#L78-L81

## Expected behavior

Handle the unexpected file gracefully, for example:

- Report the error, stop running the migrations and exit.
- Skip the file and continue processing as if it didn't exist.
- Skip the file and continue processing, but warn about the file.

## Minimal reproduction of the problem with instructions

Put a file named e.g. foo.js in the migrations/ directory and run `db-migrate up`.

## What is the motivation / use case for changing the behavior?

To save developers' time by not printing TypeErrors that we have to go debug to resolve the issue.

## Environment

<pre><code>
db-migrate version: 0.11.5
db-migrate driver with versions: db-migrate-pg v0.5.0

</code></pre>

**Comment by wzrdtales** [comment]
This is not a bug, it is not intended to have any files that are not controlled and used by db-migrate within the migrations folder.
