### ISSUE TITLE
db.changeColumn tries DROP INDEX

### ISSUE THREAD

**Issue by iamraffe** [db-migrate/node-db-migrate#626]
## I'm submitting a...

 - [X] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

Upon attempting to run db.changeColumn as follows:

`  db.changeColumn(
    "professionals",
    "estrellas",
    { type: "string", length: 2, notNull: false, unique: false },
    callback
  );`

When the migration runs, the first thing we're seeing is DROP INDEX "estrellas" which obviously causes an error, which is the following:

`[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP INDEX `estrellas`; check that it exists`

## Expected behavior

To not attempt to drop an index when only looking to change the column spec.

## Minimal reproduction of the problem with instructions
We're trying to change a col VARCHAR 255 to a col VARCHAR 2 in this case. 

## What is the motivation / use case for changing the behavior?

Change the colum spec.

## Environment

<pre><code>
db-migrate version: ^0.11.3
db-migrate-mysql: ^1.1.10

Additional information:
- Node version: 10.0.0
- Platform:  Mac

Others:
Nothing that comes to mind!
</code></pre>

**Comment by iamraffe** [comment]
Turns out removing `{ unique: false }` fixed the issue.

I still think it's somewhat weird, but it must be just how it works.

**Comment by wzrdtales** [comment]
@iamraffe Nothing weird here. If you provide `unique: false` you're actively stating: I don't want the unique key here drop it. When there is no key, it will of course cause a failure on that side and pre checking for existence is not a requirement, however a ifExists option for the unique index could be added in a future version.

**Comment by wzrdtales** [comment]
The same goes for `unique: true` you're actively stating: give me a unique key.
