### ISSUE TITLE
Cannot create new database

### ISSUE THREAD

**Issue by padcom** [db-migrate/node-db-migrate#648]
## I'm submitting a...

 - [X] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

I am trying to use `db:create <dbname>` to create a new MySQL database. When the `database.json` is populated with connection information _with_ the `database` specified the command fails stating that the database does not exist (doh! I am trying to create it!)
```
$ ./node_modules/.bin/db-migrate db:create todos
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ER_BAD_DB_ERROR: Unknown database 'todos'
```

## Expected behavior

The `database` key in `database.json` is ignored when running `db:create`

## Minimal reproduction of the problem with instructions
1. Make sure the "todos" database does not exist in your MySQL database

2. `database.json`
```
{
  "dev": {
    "driver": "mysql",
    "host": "127.0.0.1",
    "user": "root",
    "password": "root",
    "database": "todos"
  }
}
```
3. Run
```
$ db-migrate db:create todos
```

## What is the motivation / use case for changing the behavior?

To be able to provide stable way to create and seed database for developers when they start working on the project.

## Environment

<pre><code>
db-migrate version: 0.11.6
no plugins used
db-migrate driver with versions: db-migrate-mysql 1.1.10

Additional information:
- Node version: v12.4.0
- Platform: Linux (but I assume this is not platform specific :) )

</code></pre>

**Comment by DrobyshevAlex** [comment]
I have the same error.

If i remove 'database' param form my config then db:create work.

It like look db:create try connect to mysql with db-name before db created.
