### ISSUE TITLE
Help with config to enable ES6 syntax

### ISSUE THREAD

**Issue by U-4-E-A** [db-migrate/node-db-migrate#650]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [ x] Question

Really hoping someone can help me with this as it's driving me crazy.

Node v12.4.0

package.json: -

```
{
"name": "@mypackage/db-migrate",
"private": true,
"version": "1.0.0",
"main": "index.js",
"license": "ISC",
"workspaces": {
"packages": [
"common/models"
]
},
"dependencies": {
"@babel/core": "^7.6.0",
"@babel/preset-env": "^7.6.0",
"@babel/register": "^7.6.0",
"@mypackage/models": "1.0.0",
"db-migrate-mysql": "^1.1.10",
"db-migrate-plugin-babel": "^2.0.1",
"npm-upgrade": "^2.0.2"
}
}
```

.babelrc: -

```
{
"presets": [
"@babel/preset-env"
]
}
```

Directory structure: -

common->models - this contains the source lib for @mypackage/models

migrations - contains all the migration files

Yarn installs all the dependencies without issue.

So when I run a migration command ("db-migrate down -c 1", for example), I get the following: -

```
export { CONSTANT_ONE, CONSTANT_TWO, CONSTANT_THREE };

^^^^^^

SyntaxError: Unexpected token export
```

This is happening when I am trying to export/import from one of the @mypackage/models files.

```
var CONSTANT_ONE = "foo_one";
var CONSTANT_TWO = "foo_two";
var CONSTANT_THREE = "foo_three";

export { CONSTANT_ONE, CONSTANT_TWO, CONSTANT_THREE };
```

I have tried placing the @mypackage/models file in a directory inside of the directory containing the migrations themselves and this appears to import and export without issue. Is this a root directory issue? I am complete baffled and utterly frustrated. Any help VERY welcome.

**Comment by wzrdtales** [comment]
That would need to hook in, so a plugin for babel would be needed. There is a plugin for coffee script already, so have a look here https://github.com/db-migrate/plugin-coffee/blob/master/index.js and feel free to publish a plugin for babel.

**Comment by wzrdtales** [comment]
https://www.npmjs.com/package/db-migrate-plugin-babel

In fact there is a plugin already.

**Comment by U-4-E-A** [comment]
Solved by changing .babelrc to babel.config.js.
