### ISSUE TITLE
Database Driver Module Resolution doesn't work

### ISSUE THREAD

**Issue by ThisIsMissEm** [db-migrate/node-db-migrate#651]
## I'm submitting a...

 - [x] Bug report
 - [ ] Feature request
 - [ ] Question

## Current behavior

Setup a new project using `DATABASE_URL` set to postgresql; installed using:

```yarn add db-migrate```

Created a migration, then ran `db-migrate up` and the output was:

```
$ db-migrate up
# no output
$ db-migrate up --verbose
[INFO] Detected and using the projects local version of db-migrate. '/Users/emeliasmith/Development/[redacted[/node_modules/db-migrate/index.js'
[INFO] Using urlConfig settings: { driver: 'postgres',
  user: '[redacted[',
  password: '******',
  database: '[redacted[',
  host: '[redacted[',
  port: '5432' }
[INFO] require: db-migrate-pg
[INFO] require: ./pg
```

And then db-migrate exited with a zero exit code. However, no migrations were actually run, and the database remained unchanged.

The attentive person would notice that I'd forgotten to install a driver, which isn't actually mentioned as a step in the [documentation](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/installation/).

## Expected behavior

db-migrate should tell me I'm wrong and that I need to install a database driver.

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

Developer friendliness. I only was able to work out what was happening by running with `NODE_DEBUG=*` to find that there was a module resolution that looked weird:

```
MODULE 6636: looking for "/Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/db-migrate-pg" in ["/Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/lib/driver"]
MODULE 6636: Module._load REQUEST ./pg parent: /Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/lib/driver/index.js
MODULE 6636: RELATIVE: requested: ./pg set ID to: /Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/lib/driver/index.js/pg from /Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/lib/driver/index.js
MODULE 6636: looking for "/Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/lib/driver/index.js/pg" in ["/Users/emeliasmith/Development/[redacted]]/node_modules/db-migrate/lib/driver"]
```

The whole: `driver/index.js/pg` was what tipped me off because `index.js` is definitely isn't/shouldn't be a folder.

I then looked into the db-migrate code, and it seems that you have a custom database driver module resolution algorithm: https://github.com/db-migrate/node-db-migrate/blob/master/lib/driver/index.js#L56-L88

I'm guessing that something in that algorithm is broken and that it doesn't work as intended. Additionally, it seems like the rationale behind having this custom module resolution algorithm is now no longer holding true:

>         // Fallback to internal drivers, while moving drivers to new repos

Perhaps it's worth cleaning up this code and improving the developer experience at the same time? If you'd like, I can send a pull request.

## Environment

<pre><code>
db-migrate version: ^0.11.6
plugins with versions: n/a
db-migrate driver with versions: n/a — the cause of the bug

Additional information:
- Node version: v10.16.3
- Platform: Mac

Others: n/a
</code></pre>

**Comment by ethanwllms** [comment]
I am having a nearly exact same issue with mongodb in place of pg. I have started a test env locally with no auth and it is still giving the same result.

**Comment by ThisIsMissEm** [comment]
@ethanwllms the fix for me was to actually install `db-migrate-pg`, it just seems that db-migrate doesn't warn when your choice of database adapter isn't installed.

Maybe I'm misreading, but it sounds like you're seeing a connection issue?

Try running with `NODE_DEBUG=*` basically if it's this issue it'll stop logging with some module resolution lines, and won't go any further.

**Comment by wzrdtales** [comment]
@ThisIsMissEm Good catch on that, the fallback for internal drivers is due removal!
