### ISSUE TITLE
Generating a migration script using the programmable API does not use the name provided in the arguments

### ISSUE THREAD

**Issue by andyautida14** [db-migrate/node-db-migrate#652]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior
The migrationName parameter provided on create method of the programmable API is ignored when creating a migration. It instead uses the first command-line argument as the name.

## Expected behavior
Use the migrationName parameter passed to the create method as the name of the new migration.

## Minimal reproduction of the problem with instructions
index.js:
```js
const program = require('commander')
const dbMigrate = require('db-migrate')

program
  .command('migration <name>')
  .description('create a new migration script')
  .action(async function(name) {
    console.log('name:', name)
    const instance = dbMigrate.getInstance(true)
    await instance.create(name)
  })

program.parse(process.argv)

```
running the command above will produce the following output:
```bash
$ DATABASE_URL=postgres://localhost:5432/sample node . migration this-should-be-the-name-of-migration
name: this-should-be-the-name-of-migration
[INFO] Created migration at /Users/user/db-migrate-bug/migrations/20191014092749-migration.js
```
The filename produced is the same as the one logged above.

## What is the motivation / use case for changing the behavior?
to be able to create migration files with correct file names programmatically

## Environment

<pre><code>
db-migrate version: 0.11.6
db-migrate-pg version: 1.0.0

Additional information:
- Node version: v12.7.0
- Platform:  Mac

**Comment by andyautida14** [comment]
Any updates on this?

**Comment by wzrdtales** [comment]
This is due to the following

https://github.com/db-migrate/node-db-migrate/blob/bd165a55ced394de508b14f73d6426786e8db6c6/lib/commands/create-migration.js#L51

This is shifting out the variable, while this is pushing in

https://github.com/db-migrate/node-db-migrate/blob/bd165a55ced394de508b14f73d6426786e8db6c6/api.js#L332

needs to be fixed in the api.js

thank you for reporting!
