### ISSUE TITLE
`prepare` runs before internal.locTitle set, so scopes do not apply

### ISSUE THREAD

**Issue by RobertLowe** [db-migrate/node-db-migrate#663]
## I'm submitting a...

 - [X ] Bug report  

## Current behavior

Scopes do not apply when using `db-migrate up:thing`

Specifically, https://github.com/db-migrate/node-db-migrate/blob/master/lib/commands/up.js#L23 before https://github.com/db-migrate/node-db-migrate/blob/master/connect.js#L67

![Screen Shot 2020-01-26 at 3 21 26 PM](https://user-images.githubusercontent.com/601141/73141354-1d84ea00-4051-11ea-89e3-0867ed5a0785.png)

## Expected behavior

They should run

## Minimal reproduction of the problem with instructions

1. Create a migrate `db-migrate create:thing example` works as expected and creates the migration file

2. Run `DATABASE_URL="mongodb://localhost:3001/meteor" db-migrate up:thing`

No migrations run, looks in just default `./migrations` folder

## Environment

<pre><code>
```
    "db-migrate": "0.11.6",
    "db-migrate-mongodb": "1.5.0",

    "@babel/core": "^7.8.3",
    "db-migrate-plugin-babel": "^2.0.1",
```

Additional information:
- Node version:  v8.11.4
- Platform:  mac (nvm)
</code></pre>

--- 

I'm creating a hack to work around this by just changing https://github.com/db-migrate/node-db-migrate/blob/master/lib/commands/up.js#L23 to use `internals.migrationMode` instead

Thoughts? Might be some weird async/promise behaviour, I'm not sure.

**Comment by RobertLowe** [comment]
See patch here: https://github.com/RobertLowe/node-db-migrate/commit/204e38e2d669def596ffd36c6e7b911c49a279c4 do not use, there are additional changes to `template.js` that need to be reverted as I updated them to be ES6 for ease of use

**Comment by jydenberg** [comment]
I  had this same issue in the driver i created, except for the "down" case.
I end up with a path that looks like
/a/b/c/scopename/scopename/migrationname

instead of 

/a/b/c/scopename/migrationname

and an error is thrown. Same issue?
