### ISSUE TITLE
Feature Request: Add AFTER mysql param.

### ISSUE THREAD

**Issue by k1T4eR** [db-migrate/node-db-migrate#669]
## I'm submitting a...

 - [ ] Bug report  
 - [x] Feature request
 - [ ] Question

## Minimal reproduction of the problem with instructions
Trying to add column **after** specified column. `ADD altPhoto VARCHAR(255) AFTER mainPhoto`

```
exports.up = function(db) {
  db.addColumn('users', 'altPhoto', {type: 'string', length: 50, after: 'mainPhoto'})
};
```
## Environment
```
db-migrate version: 0.11.16
db-migrate driver with versions: mysql v2.1.0
```

**Comment by dyankov91** [comment]
+1
