### ISSUE TITLE
How to set precision and scale for decimal data type

### ISSUE THREAD

**Issue by bahung1221** [db-migrate/node-db-migrate#671]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [X] Question

## Current behavior

I can't add `precision` and `scale` options to `decimal` data type. (it always use `decimal(10,0)`)

## Expected behavior

It should be able to specific `precision` and `scale` when i use below config:
```
price: { type: 'decimal', length: '16,4' },
```

db-migrate version: latest
plugins with versions: latest
db-migrate driver with versions: mysql latest

Additional information:
- Node version: v11
- Platform: Macos

Thank you very much for a nice job! 😄

**Comment by andrescuco** [comment]
Bump

**Comment by patebry** [comment]
If you use this it works.
`{ type: "decimal(16,4)" }`

**Comment by michael-caraiani** [comment]
yup `{}` seems to work 👍 
but it's generating warnings
![image](https://user-images.githubusercontent.com/33863860/166116469-a614dd3a-9ea8-42ef-9e2e-6b40a29fd4a3.png)

so I'm still confused, what would be the correct way to add precision/scale to a decimal ? 🤔

**Comment by wzrdtales** [comment]
this has not been carried to every driver, but is certainly something that should.

https://github.com/db-migrate/mysql/blob/d2fdff16239c455a5ef02699a0cabf1cca5d4215/index.js#L78-L81

for MySQL you could use `{ type: 'decimal', precision: x, scale: x }`, that would need to be added to the base driver to work everywhere though.
