### ISSUE TITLE
Down/rollback a specific migration?

### ISSUE THREAD

**Issue by aprilmintacpineda** [db-migrate/node-db-migrate#672]
## I'm submitting a...

 - [ ] Bug report
 - [x] Feature request
 - [x] Question

## Current behavior

Docs doesn't mention how to `rollback` a specific migration.

## Expected behavior

There should be a way to rollback specific migration(s).

## Environment

db-migrate version: ^0.11.6
db-migrate driver with versions: db-migrate-mysql^2.1.0

Additional information:
- Node version: N/A
- Platform: N/A

**Comment by aprilmintacpineda** [comment]
I tried running `npx db-migrate down 20200229212850-my-migration` because in `up` it said I can do `db-migrate up 20150207135259-myFancyMigration` so I though I could do the same with down, but the behavior I got was unexpected. I rolled back 5 migrations.

**Comment by aprilmintacpineda** [comment]
Don't!

**Comment by aprilmintacpineda** [comment]
Don't you dare.

**Comment by tomsiwik** [comment]
Nice. I need this behaviour too and/or invalidating single migrations rather than whole sequences.
