### ISSUE TITLE
Doesn't support coffeescript

### ISSUE THREAD

**Issue by ovikholt** [db-migrate/node-db-migrate#673]
It doesn't seem to support (migrations written in ) coffeescript anymore, even though it's mentioned a few times in your changelog, and you having an options --coffee-file. Any plans to finish it?

There's an especially offensive line in  migrations.js:
var filesRegEx = /\.js$/;
but correcting this doesn't alone solve the problem, hehe, interpretation further down the rabbit hole seems to assume js files.

Do I have to implement this myself in order to get my beatiful, beloved coffeescript everywhere? If so, I could use some hints...

**Comment by wzrdtales** [comment]
It should normally still work, but it is an optional component by now. Did you install the coffee plugin in the project using db-migrate?

https://www.npmjs.com/package/db-migrate-plugin-coffee

**Comment by ovikholt** [comment]
No I hadn't installed that, and it worked!! Thank you!!
