### ISSUE TITLE
Run specific migration

### ISSUE THREAD

**Issue by JoaquinDelPrado** [db-migrate/node-db-migrate#677]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

How can i run just one migration?, an specific migration?. Something like:
`db-migrate up myMigrationFile`

i been trying to do this and looking in the issues but i dont find anything

**Comment by chhsu0222** [comment]
I have the same issue.
I'm using the version 0.11.10

node_modules/db-migrate/bin/db-migrate up 20200430073129-newModel
[INFO] Processed migration 20200430073047-AiUser
[INFO] Processed migration 20200430073129-newModel
[INFO] Done
