### ISSUE TITLE
.npmignore doesn't cover all build artifacts and configs

### ISSUE THREAD

**Issue by Marsup** [db-migrate/node-db-migrate#683]
## I'm submitting a...

 - [X] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

I've just noticed it in the latest release but it's not new. The npm package seems to contain many files that should not be shipped, like the coverage results, CI, linting and tern configs, etc...

## Expected behavior

I think it's preferable to have a clean package.

**Comment by wzrdtales** [comment]
we certainly can extend the npmignore, feel free to open a PR about that.
