### ISSUE TITLE
Migrations not executed with Node 14

### ISSUE THREAD

**Issue by otigges** [db-migrate/node-db-migrate#692]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

After upgrading to Node 14 db-migrate does not execute the migrations but exits silently without any error message.

We are using a PostgreSQL db. db-migrate seems to try connect, but no matter if the database is running or not, the process exists without any notice.

After going back to Node v12.16.3 everything works again as expected. 

## Minimal reproduction of the problem with instructions

Install/upgrade to Node 14.

Add a database.json like:

     {
	"defaultEnv": "dev",
	"dev": {
		"driver": "pg",
		"user": "postgres",
		"password": "secret",
		"host": "localhost",
		"database": "my-db
	}
    }

(database should not exists or be started.)

run db-migrate with some sample migration, it will exit without error message.

## Environment

<pre><code>
db-migrate version: 0.11.11
db-migrate-pg: 1.2.1

Additional information:
- Node version: 14.0.2
- Platform:  Mac

Others:

</code></pre>

**Comment by miv** [comment]
Same thing happening to me. Tested with `1.0.0-beta.2`, same result.

**Comment by miv** [comment]
I'm pretty sure it should be broken right now. `executeUp(internals, config)` returns a promise, but it's not awaited. 

I propose using eslint 'require-await' rule to catch such errors.

@wzrdtales

**Comment by wzrdtales** [comment]
ahh yah, every time the same thing with node :) I will have a look if it is really an API change or if it is just again a ABI change.

**Comment by wzrdtales** [comment]
just an ABI change, please update the pg driver should work fine now

**Comment by jmls** [comment]
what version of the pg driver should we be using ? I'm hitting this error with any 14 version of node

**Comment by paulmiller3000** [comment]
> what version of the pg driver should we be using ? I'm hitting this error with any 14 version of node

@jmls, try 1.2.2. I ran into a similar problem and updated mine based on the reply from @wzrdtales .

**Comment by wzrdtales** [comment]
never post in closed issues, open a new one and include sufficient information to reproduce your case.
