### ISSUE TITLE
RC Configuration Ignored

### ISSUE THREAD

**Issue by nmccready** [db-migrate/node-db-migrate#698]
Re-opening:

https://github.com/db-migrate/node-db-migrate/issues/451#issuecomment-641319838

I asked the question as the actual fix was not referenced in the Issue itself. Therefore referencing the PR that resolved the issue is advised.

Lastly, I just tried utilizing the latest codebase and the `.db-migraterc` was completely ignored.

**Comment by wzrdtales** [comment]
it is referenced...  #498 

Please make the effort and stick to the issue template or at least provide all the informations asked otherwise we can't help you.
