### ISSUE TITLE
Programmatic API not working as expected

### ISSUE THREAD

**Issue by germanflighel** [db-migrate/node-db-migrate#701]
## I'm submitting a...

 - [X] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior
I have two migrations defined, and I'm trying to execute just one of them, via the `dbm.up()` method, specifying which one. It executes an older migration.

## Expected behavior
Should behave like de CLI command `db-migrate up 20200716180320-example-migration`, execute only the specified migration.

## Minimal reproduction of the problem with instructions
* Define two migrations
* Try upping a specific one (via API)

I currently have two migrations defined:
* 20200713133447-add-cars.js
* 20200716180320-add-people.js

As you see, add-people is a newer migration. When running `dbmigrate.up('20200716180320')`, it should **just** run add-people, but instead, it's runs both migrations!

## What is the motivation / use case for changing the behavior?
Handling a database schema change.

## Environment

<pre><code>
db-migrate version: 0.11.11
db-migrate driver with versions:  mongodb 1.5.0

Additional information:
- Node version: 12.18.2  
- Platform:  Linux

</code></pre>

**Comment by CorridoniMatias** [comment]
I have the same problem, when trying to `up` a specific migration, passed via the first parameter as a string, it just ignores that specification and restores the oldest file in the `migrations` folder.

**Comment by wzrdtales** [comment]
it is not a bug, this is indeed the same behavior that also up has, so everything is right. db-migrate never supported out of order execution (https://github.com/db-migrate/node-db-migrate/blob/bb842e0e557972d2c7e0e8f0328d0f6fd32000cd/lib/walker.js#L158). When you specify a target migration, which is what you're doing here, then it will always execute everything until this migration.

This is in the nature of good migrations, they don't change as soon as they're submitted to the common development tree. **NEVER**. And there is an order to the migrations for a reason, it is b/c it is the easiest way to ensure their dependency that might resolve to one another, it would be a pain in the ass to support every second developer making the same stupid mistakes b/c the framework allowed him to do the horrible wrong things (executing out of order and then breaking stuff). That is why it is what it is and it will not change until there comes a new ordering scheme, which is a thing that might happen in the future, but is not right now. However even then there would be no out of order execution, just a different ordering scheme.

**Comment by wzrdtales** [comment]
in general, if you need to revert a specific migration, create a new one and revert it in there. surprisingly simple

**Comment by wzrdtales** [comment]
And about planned different ordering schemes, there are already groups available which extend on the basic functionality of ordered migrations and allow some kind of separation, there were however thoughts about having tagged migrations which would allow to bind a group of migrations to a tag. For example a semver version (or any other version).

**Comment by wzrdtales** [comment]
To add on top of that: tagged migrations are already possible, but unhandy. The migrations folder supports sub folders (scoping) which is documented here https://db-migrate.readthedocs.io/en/latest/Getting%20Started/commands/#scoping. That can be used for tag binding already, however might be or not be the best solution for what one is aiming for, but it certainly displays the order in the organizational structure as well as in logic.
