### ISSUE TITLE
API migrations-dir configuration ignored, default always used.

### ISSUE THREAD

**Issue by gjbaxter** [db-migrate/node-db-migrate#705]
## I'm submitting a...

 - [ X] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

Using the API rather than a database.json file, the migrations directory is ignored.. or rather it is overwritten by the defaults (argv).  

## Expected behavior

Configuration of migration-dir should be honored.

## Minimal reproduction of the problem with instructions

     const options = {
                env: "mongo",
                config: {
                    mongo: {
                        driver: "mongodb",
                        database: config.get("database.mongo.name"),
                        host: config.get("database.mongo.hosts"),
                        user: config.get("database.mongo.user"),
                        password: config.get("database.mongo.pass"),
                        ssl: config.get("database.mongo.ssl.enabled"),
                        "migrations-dir": `${process.cwd()}/database/migrations`,
                    },
                },
        };
       const dbMigrate = DBMigrate.getInstance(true, options);
       dbMigrate.up();

The configuration is correct and is passed around appropriately.  The migrator correctly has the migration-dir defined. However, in commands/up.js:

        if (internals.locTitle) {
          migrator.migrationsDir = path.resolve(internals.argv['migrations-dir'],
            internals.locTitle);
        } else { migrator.migrationsDir = path.resolve(internals.argv['migrations-dir']); }

internals.locTitle is not defined and thus migrator.migrationsDir is overwritten by the default value (cwd/migrations).

## What is the motivation / use case for changing the behavior?

API should be able to define the migrations directory.

## Environment

<pre><code>
db-migrate version: 0.11.11
db-migrate driver with versions: db-migrate-mongodb : 1.5.0

</code></pre>

**Comment by lasergoat** [comment]
I'm not sure if this will help, but for my code (which uses MySQL) it works like this...

my migrations get put into the dist folder when I run `tsc` (typescript build) and then, my code is like this:

```
  const path = require("path");
// ...

  const dbmigrate = DBMigrate.getInstance(true, {
    // only run migrations from the dist/migrations folder, never the root migrations folder
    cwd: path.resolve("dist"),
    config: "./database.json",
    cmdOptions: {
        table: migrationsTableName,
        // would also set migrations-dir in here.
    },
    env: process.env.NODE_ENV,
  });
```

The migrations are in dist/migrations/[scope]
