### ISSUE TITLE
Error cannot find module when running down with scopes - migration mis-named in DB

### ISSUE THREAD

**Issue by lasergoat** [db-migrate/node-db-migrate#707]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [ ] Question

## Current behavior

Migration filename: `dist/migrations/cde/20200807173805871-test3.js`
Migration recorded in migrations table as `cde/00807173805871-test3`
Migration down not possible, results in error:

```
Cannot find module '/Users/lasergoat/Projects/migrations/dist/migrations/cde/00807173805871-test3
```

![Screen Shot 2020-08-07 at 4 34 18 PM](https://user-images.githubusercontent.com/15964/89690638-9ac8cb80-d8cc-11ea-8a4b-f3b0466f2715.png)

**Then, when I correct the name in the DB like this:**

![Screen Shot 2020-08-07 at 4 34 46 PM](https://user-images.githubusercontent.com/15964/89690641-9dc3bc00-d8cc-11ea-9bda-1df5b5be34db.png)

I can run down, and the migration down method is called and all sql is reversed, BUT the record isn't removed from the migrations table.

## Expected behavior

The name should be recorded as the correct filename, not with `202` truncated.

ie. 

```
cde/20200807173805871-test3
```

And when I call down, the migration record should be removed. (right?)

## Minimal reproduction of the problem with instructions

NOTE: I can repro in node js as module and in the cli with `db-migrate`

When I run up with my scope, the migration is saved in the migrations table with a different file name (the first three chars are truncated)

**My migration filename:**

`dist/migrations/cde/20200807173805871-test3.js`

**My scope config:**

`dist/migrations/cde/config.json`

```
{
  "database": "cde",
  "schema": "cde"
}
```

**To run UP:**

```
./node_modules/.bin/db-migrate up:cde --migrations-dir dist/migrations --table migrations_v2
```

- OR in nodeJs code:
```
  // typescript that gets compiled into dist folder
  const dbmigrate = DBMigrate.getInstance(true, {
    // only run migrations from the dist/migrations folder, never the root migrations folder
    cwd: path.resolve("dist"),
    config: "./database.json",
    cmdOptions: { table: "migrations_v2" },
    env: process.env.NODE_ENV,
  });

  await dbmigrate.createDatabase(dbName);
  await dbmigrate.up(null, dbName);
```

Both of these methods result in the correct migration being run. The migration is recorded properly in `cde.migrations_v2` BUT the name is wrong. It's recorded as: `cde/00807173805871-test3`

The db-migrate log output also shows the wrong name:

```
[INFO] loaded extra config for migration subfolder: "cde/config.json"
[INFO] Processed migration 00807173805871-test3
[INFO] Done
```

So, when I run down OR rollback in nodeJs it cannot find the module:

```
./node_modules/.bin/db-migrate down:cde --migrations-dir dist/migrations --table migrations_v2
```

**OR from nodeJs as a module**

```
  const dbmigrate = DBMigrate.getInstance(true, {
    // only rollback migrations from the dist/migrations folder, never the root migrations folder
    cwd: path.resolve("dist"),
    config: "./database.json",
    cmdOptions: { table: "migrations_v2" },
    env: process.env.NODE_ENV,
  });

  await dbmigrate.down(null, dbName);
```

**Full Error:**

```
[ERROR] Error: Cannot find module '/Users/lasergoat/Projects/migrations/dist/migrations/cde/00807173805871-test3'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Class.setup (/Users/lasergoat/Projects/migrations/node_modules/db-migrate/lib/skeleton.js:158:12)
    at /Users/lasergoat/Projects/migrations/node_modules/db-migrate/lib/migrator.js:292:39
    at tryCatcher (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/lasergoat/Projects/migrations/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:773:18)
```

**⚠️ HOWEVER:** 

When I name the file correctly in the migrations_v2 table, I can run down or rollback in the code just fine. BUT the migration record stays put in the migrations table - before I used scopes, it was removing the record.

## Environment

<pre><code>
db-migrate version: `db-migrate@0.11.10`
plugins with versions: 
db-migrate driver with versions: 
db-migrate-base@2.3.0
db-migrate-shared@1.2.0 
db-migrate-mysql@2.1.1 

Additional information:
- Node version: v12.16.1  
- Platform:  Mac 10.15.6 (Catalina)

Others:

</code></pre>

**Comment by wzrdtales** [comment]
mhhh, sounds indeed weird... I will have a look.

**Comment by wzrdtales** [comment]
ok, the problem is: you did create this timestamp by hand...

Never do that, always use `db-migrate create` to create  a migration. 

This is a proper timestamp of db-migrate

`20200808090752`

This is yours

`20200807173805871`

That is the issue, it is not in db-migrates format.

**Comment by lasergoat** [comment]
Ahhh very good! 

**I forgot I did that!** 🤦 . The reason I chose to do that is because there was no way to get the new file name as a return value from db migrate `create()` - it only logs the value to the output buffer. Plus, I'm using typescript for the migrations, so I wanted a way to use my own migration template for each newly made migration (and give them a `.ts` ext) and I couldn't figure how to do any of that with db migrate. So i decided to make my own migrations - so I'll just fix the timestamp!

**Comment by lasergoat** [comment]
Here's the formula I'll be using:

```
  // DB migrate uses a specific format which we must match in order for
  // it to run the migrations properly
  // make a timestamp without any non-digits, YYYYMMDDHHMMSS
  return new Date()
    .toISOString()
    .replace(/T|Z|\-|\:|\./g, "")
    .substr(0, 14);
```

`20200808090752` <- db migration output
`20200810140329` <- output of this method
`YYYYMMDDHHMMSS` <- format
