### ISSUE TITLE
 No such driver found ... db-migrate-pg

### ISSUE THREAD

**Issue by pnjha** [db-migrate/node-db-migrate#714]
- ✅ Bug report 

 I am currently using **db-migrate@0.11.11** and **db-migrate-pg@1.2.2**, and constantly getting following error
```[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: No such driver found, please try to install it via npm install db-migrate-postgressql or npm install -g db-migrate-postgressql```
 
Node version is v12.19.0 and using yarn as my package manager
Error comes when I do `db-migrate up`

database.json contents:

```
{
  "dev": {
    "driver": "pg",
    "user": "postgres",
    "password": "***",
    "host": "localhost:5432",
    "database": "dbname",
    "schema": "public"
  },
  "sql-file": true
}
```
My operating system is windows 10

**Comment by wzrdtales** [comment]
you're having some hickup somewhere in your config (not the one you posted but some config). please check it more thoroughly. `postgressql` is already having a typo...
