### ISSUE TITLE
There should be a way to load config from environment variables instead of config.json

### ISSUE THREAD

**Issue by rw3iss** [db-migrate/node-db-migrate#725]
## I'm submitting a...
Feature Request

## Current behavior
Loading config from config.json forces us to send DB credentials around different deployment environments (ie. cloud providers and devs, etc).
We typically want a way to keep the information private per environment, which would require loading from environment variables.

## Expected behavior
Have an option to load config from pre-defined environment variables.

**Comment by rw3iss** [comment]
Nevermind, I see the DATABASE_URL environment option. Thanks.

**Comment by wzrdtales** [comment]
database_url is limited sometimes. if that doesn't work, look in the docs for the configuration file and the environment references. here a quick example of a config with more advanced details

```json
{
  "dev": {
    "user": {"ENV": "user"},
    "driver": "cockroachdb",
    "database": {"ENV": "database"},
    "native": true,
    "host": { "ENV": "host" },
    "port": 26257,
    "ssl": {
      "sslrootcert": { "ENV": "ca_crt" },
      "sslcert": { "ENV": "ssl_cert" },
      "sslkey": { "ENV": "ssl_key" },
      "sslmode": { "ENV": "ssl_mode" }
    }
  }
}
```

**Comment by rw3iss** [comment]
Ah, thank you @wzrdtales !

**Comment by vipulwairagade** [comment]
@wzrdtales Is there any way we can load config from a js file which exports config const. My script looks like this 
`db-migrate --config '%INIT_CWD%\\db\\dbmrc.js' -m '%INIT_CWD%\\db\\migrations'`

And my `dbmrc.js` is :

```
require("dotenv-defaults").config({
  path: "./.env",
  encoding: "utf8",
  defaults: "./.env.local" // This is new
});

const {
  CONFIG_DB_SERVER,
  CONFIG_DB_PORT,
  CONFIG_DB_USERNAME,
  CONFIG_DB_PASSWORD,
  CONFIG_DB_NAME
} = process.env;

const config = {
  driver: "mysql",
  multipleStatements: true,
  host: CONFIG_DB_SERVER,
  port: CONFIG_DB_PORT,
  database: CONFIG_DB_NAME,
  user: CONFIG_DB_USERNAME,
  password: CONFIG_DB_PASSWORD,
  "sql-file": true
};

module.exports = config;
```

If I replace config file with standard `json` file as per docs, it works. I was trying to load my `env` variables as on production I will have `.env` file and on local I'll have `.env.local`
