### ISSUE TITLE
Db migrate not running migrations for mysql

### ISSUE THREAD

**Issue by Xexnon** [db-migrate/node-db-migrate#749]
## I'm submitting a...

 - [x] Bug report  
 - [ ] Feature request
 - [x] Question

## Current behavior

Throws a syntax error while running migrations but runs correctly on MySQL workbench

## Expected behavior

should run migration correctly

## Minimal reproduction of the problem with instructions

This is the MySQL migration file.
```
/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS user_info(
  id BINARY(16) PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()
);

CREATE TABLE IF NOT EXISTS wallet(
  id BINARY(16) PRIMARY KEY,
  user_id BINARY(16) NOT NULL,
  balance DECIMAL(19,4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  FOREIGN KEY (user_id) REFERENCES user_info(id)
);
 
```
is it that I can't run multiple create at once cos this works on `db-migrate-pg` driver whats the problem with MySQL driver

## Environment

<pre><code>
db-migrate version: 0.11.12
plugins with versions: X.Y.Z
db-migrate driver with versions: mysql 2.1.2  

Additional information:
- Node version: 14.x  
- Platform: Mac 

Others:

</code></pre>

**Comment by wzrdtales** [comment]
please red the docs: https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/

**Comment by Xexnon** [comment]
> please read the docs: https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/
is this config correct

```
{
  "development": {
    "ENV": "PATRONIZE_DATABASE_DEV_URL"
  },
  "test": {
    "ENV": "PATRONIZE_DATABASE_TEST_URL"
  },
  "production": {
    "ENV": "PATRONIZE_DATABASE_URL"
  },
  "defaultEnv": {
    "ENV": "PATRONIZE_NODE_ENV"
  },
  "sql-file": true,
  "multipleStatements": true
}
```

**Comment by Xexnon** [comment]
> please read the docs: https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/

I did that already and set my database.json file it wan't working
