### ISSUE TITLE
Multiple migration directories?

### ISSUE THREAD

**Issue by jrj2211** [db-migrate/node-db-migrate#756]
## I'm submitting a...

 - [ ] Bug report  
 - [x] Feature request
 - [x] Question

## Question/Request

I'm switching from postgres with Knex to mongodb and am looking for a migration tool. A nice feature that Knex has is the ability to specify multiple migration directories and I'm wondering if this can support my needs.

The reason for multiple migration directories is I have a bunch of "generic" migrations that I apply to all clients. I also need to be able to customize a DB for specific clients. In Knex, I had a general migration folder and then a folder for each client. I could then specify both folders, it would take and merge them together and run all of the migration files.

I see that this supports scoping, but I don't believe I can accomplish this with that? Could this scoping have a flag to run migrations above it?

For example:

- migrations/1633521000_users.js
- migrations/1633572000_sales.js
- migrations/client_1/1633553000_users.js

Then possibly specifying an --recursive flag?

`db-migrate up:client_1 --recursive`

Which would load all of the migrations in the main and client_1 folder in the correct order:

1. migrations/1633521000_users.js
2. migrations/client_1/1633553000_users.js
3. migrations/1633572000_sales.js

I do plan on using the API, so additionally it would be nice to have this in there as well. Maybe like this?

```
create(migrationName[, [scope], [recursive], [callback]])
up([[specification][count], [scope], [recursive], [callback]])
down([[specification][count], [scope], [recursive], [callback]])
```

Alternatively, maybe it would be easier to follow next and just allow the config to specify either a string or array for migration dirs (tho I don't see anywhere in the configs to specify migration dir except via the command line flag?). Snippet from Knex's documentation:

> directory: a relative path to the directory containing the migration files. Can be an array of paths (default ./migrations)

## Workaround
Maybe its already possible by just running each one separately but I'm not sure how this keeps track of its last migration. Im assuming if I ran `db-migrate up` and then `db-migrate up:client_1`, the client_1 migration wouldn't run because its timestamp is older than the last migration in the main folder?

**Comment by wzrdtales** [comment]
> Maybe its already possible by just running each one separately but I'm not sure how this keeps track of its last migration. Im assuming if I ran db-migrate up and then db-migrate up:client_1, the client_1 migration wouldn't run because its timestamp is older than the last migration in the main folder?

The scopes will run individually to answer that question also. So the timestamp from any other scope will not influence the others.
