### ISSUE TITLE
Add support for migration .js files being ES modules (ESM)

### ISSUE THREAD

**Issue by mo** [db-migrate/node-db-migrate#784]
When "db-migrate create" is executed it created a new .js file that uses commonjs. However, my project uses ES modules (ESM) i.e. I have "type": "module" in my main package.json file. For this reason I'm interested in one of these two features:

* Command line switch that makes "db-migrate create" create a .cjs file instead of a .js file.
* Command line switch that makes "db-migrate create" output an ES module (ESM) with "import" instead of require etc.

**Comment by wzrdtales** [comment]
already fixed in https://github.com/db-migrate/node-db-migrate/pull/724 (you can use the current latest beta version without worrying)
