### ISSUE TITLE
What is the proper way to migrate DB on heroku?

### ISSUE THREAD

**Issue by g-pavlik** [db-migrate/node-db-migrate#79]
Can't possibly make that working, probably there's need to force migration to use ssl, but how to do it?

Code pushed to heroku then

```
heroku run ./db-migrate up
```

does not finds any migrations (db-migrate is symbolic link to node_modules/db-migrate/bin/db-migrate)

please refer to #49 as there's some info about fallback to database.js (which is not working as I checked), and there's no info what to return there? 

Manually changing 

```
var pg = require('pg')
```

to 

```
var pg = require('pg').native
```

triggers segmentation fault error:

```
WARNING: ev_io is deprecated, use uv_poll_t
Segmentation fault
```

**Comment by apires** [comment]
Hi all, doing some thread necromancing here.

If you do what we do and only specify a connect string you can do "native=true" in the string itself since db-migrate will bring all those query params to the config as-is.

**Comment by wzrdtales** [comment]
ouh wow this was an old dead one, well at least it is answered now, I'm sure that is going to help someone that searches for this.

Thanks @aspires

**Comment by GreatKikale** [comment]
"Native: true" worked for me.

Now I can run my migrations in heroku from command line.

Thanks guys!!  Great job

**Comment by ririlapraline** [comment]
@GreatKikale could you show me your database.json file ? Thank you

**Comment by GreatKikale** [comment]
Sure! Here it is, in my case I have two environments:

```
{
  "devPg": {
    "driver": "pg",
    "host":"localhost",
    "database":"yourdbname",
    "user": "youruser",
    "password": "yourpassword",
    "multipleStatements": true
  },

  "prod": {
    "driver": "pg",
    "native": "true"
  }
}
```

**Comment by ririlapraline** [comment]
@GreatKikale Thanks !
