### ISSUE TITLE
Reasoning behind using template.js tog generate a files for each migration?

### ISSUE THREAD

**Issue by wunderkind2k1** [db-migrate/node-db-migrate#791]
## I'm submitting a...

 - [ ] Bug report  
 - [ ] Feature request
 - [x] Question

I was just wondering why we need to generate a new .js file for every migration? I think almost 99% of the code of each generated
.js file is identical? On a project with a lot of migrations this behaviour results in a very long and repetitive folder full of js files of almost the same content.

In respect to "Chesterton's fence" I would like to just kindly ask what the reasoning behind that design decision could have been?

Thank you. Sven

**Comment by wzrdtales** [comment]
this is an open source project, we're not due you a reasoning. If you think you can improve something, go ahead work on it and open a PR.

**Comment by wunderkind2k1** [comment]
I completely understand your answer. Thank you. Now I know why you use the templates.
