### ISSUE TITLE
postgres array types not supported

### ISSUE THREAD

**Issue by ryanflorence** [db-migrate/node-db-migrate#86]
I expected `integer[]` to work just like `integer` does, but it doesn't.

For now I can just use runSql, so no big deal, but maybe you want to support it. Feel free to close this w/ no explanation if you don't want to!

sample code:

``` js
var pcb = require('parallel_callback');
var dbm = require('db-migrate');
var type = dbm.dataType;

exports.up = function (db, done) {
  db.createTable('recipes', {
    name: 'string'
    // direction_ids: 'integer[]' // <-- doesn't work
  }, function(a) {
    // but this does
    db.runSql("ALTER TABLE recipes ADD COLUMN direction_ids integer[];", done);
  });
};
```
##

**Comment by FearZee** [comment]
Issue is still a thing? Haven't found any docs for the PG Array....

**Comment by wzrdtales** [comment]
well first of all, do not post in issues from the stone age. second, just write type: 'STRING[]' and it will work
