### ISSUE TITLE
addColumn if not exist

### ISSUE THREAD

**Issue by bikashrai** [db-migrate/node-db-migrate#94]
errors out if the column already exist during "addColumn({'table',{pec},callback});
Is there any way to achieve this when adding a column that already exists ?

**Comment by wzrdtales** [comment]
I'm currently resorting all the issues, so don't wonder for a feedback almost 3 years later.

I'm going to close this issue, I do see this similar to kunklejr, also to mention that there is an if not exists for tables which is mostly b/c the database itselfs does supports this. This is just as wrong as doing this on addColumn and also dangerous. Such behavior might end up in loosing control and having issues that no one knows why they do exist.

To say `if exists` is handy when you're working directly on the database and writing manual queries. But in migrations where you want to have reproduceable state, one may probably not want this behavior as this could end up in unwanted side effects. The only good use case is `if exists` together with drop table when one wants to make sure that we're creating a new table. While I still think that this is possibly dangerous to do such a thing, as this could end up in actions you don't really want to do.

For now I won't look into any implementation for this feature though.
